// yjp_sRig
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc yjp_RSJointNameGet(int $GetName)
{
	string $tfjn[] = {"yosStartJointText","yosEndJointText","yosCollideText","yosPVlocatorText"};
	string $JointSelect[],$JCheck;
	int $Jexist = 0;
	$JointSelect = `ls -sl`;
	if(!size($JointSelect))return ;
	$JCheck = `nodeType $JointSelect[0]`;
	$Jexist = `gmatch $JCheck "joint"`;
	$Jexist = $Jexist + `gmatch $JCheck "transform"`;
	if($Jexist == 0)return;
	
	string $TextFieldArray[] ={"yosStartJointText","yosEndJointText","yosPVlocatorText",
		"RF_HeelNodeText","RF_BankInNodeText","RF_BankOutNodeText","RF_SwivelNodeText"};
	
	RigSetUpTextFieldDel $GetName;
	textField -e -ip 0 -it $JointSelect[0] $TextFieldArray[$GetName];
	return;
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc doyjp_rig_GroundCTRL()
{
	global string $ss_RigCharaID ;
	string $posjoint = `textFieldGrp -q -text GroundPosField`;
	if(size($posjoint) == 0)error"Specify the node to be the center";
	
	$ss_RigCharaID = `textField -q -text yjp_CharactorIDText`;
	if(size($posjoint) == 0)error"Please specify ID name";
	
	yjp_rig_GroundCTRL $posjoint $ss_RigCharaID ;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Center
global proc doyjp_RigCenterCtrlCreate()
{
	global string $ss_RigCharaID ;
	string $posjoint = `textFieldGrp -q -text PosNodeField`;
	if(size($posjoint) == 0)error"Specify the node to be the center";
	
	$ss_RigCharaID = `textField -q -text yjp_CharactorIDText`;
	
	string $charaSetName = `textField -q -text yjp_CharactorIDText`;
	
	yjp_rig_GroundCTRL $posjoint $ss_RigCharaID ;
	yjp_rig_CenterCtrlCreate $posjoint $ss_RigCharaID;
	Rig_CharactorIDMenu;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//IKFKControls creation//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc YOS_IKFKControls()
{
	string $yosSJointName = `textFieldGrp -q -text IK_FK_setUpRootField`;
	string $yosEJointName = `textFieldGrp -q -text IK_FK_setUpEndField`;
	string $PVlocator = `textFieldGrp -q -text IK_FK_setUpPvField`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	string $charaSetName = `optionMenu -q -v Rig_CharactorIDListMenu`;
	int $ReverseKnee = `checkBox -q -v ReverseKneeCheckBox`;
	global string $ss_RigCharaID ;
	$ss_RigCharaID = $charaID;
	yjp_rig_makeMetaRoot "none" $charaSetName;
	//yjp_rig_GroupCreate $charaID;
	//yjp_rig_SwichesAddAttr $yosSJointName;
	yjp_rig_IKFKSetUp $yosSJointName $yosEJointName $PVlocator $ReverseKnee ;
}

global proc YOS_IKFKfootControls()
{
	string $yosSJointName = `textFieldGrp -q -text IK_FK_setUpRootField`;
	string $yosEJointName = `textFieldGrp -q -text IK_FK_setUpEndField`;
	string $PVlocator = `textFieldGrp -q -text IK_FK_setUpPvField`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	string $charaSetName = `optionMenu -q -v Rig_CharactorIDListMenu`;
	string $Heel = `textFieldGrp -q -text RF_HeelNodeText`;
	string $Swivel = `textFieldGrp -q -text RF_SwivelNodeText`;
	string $BankIn = `textFieldGrp -q -text RF_BankInNodeText`;
	string $BankOut = `textFieldGrp -q -text RF_BankOutNodeText`;
	
	if($yosEJointName == "")$yosEJointName = "none";
	
	int $ReverseKnee = `checkBox -q -v ReverseKneeCheckBox`;
	global string $ss_RigCharaID ;
	$ss_RigCharaID = $charaID;
	yjp_rig_makeMetaRoot "none" $charaID;
	//yjp_rig_GroupCreate $charaSetName;
	//yjp_rig_SwichesAddAttr $yosSJointName;
	//IKFKFootRigSetUp $yosSJointName $yosEJointName $PVlocator $Heel $Swivel $BankIn $BankOut $ReverseKnee $charaSetName;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc YOS_FKControls()
{
	string $yosSJointName = `textFieldGrp -q -text FKsetUpRootField`;
	string $yosEJointName = `textFieldGrp -q -text FKsetUpEndField`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	string $charaSetName = `optionMenu -q -v Rig_CharactorIDListMenu`;
	global string $ss_RigCharaID ;
	$ss_RigCharaID = $charaID;
	yjp_rig_makeMetaRoot "none" $charaID;
	//yjp_rig_GroupCreate $charaSetName;
	//yjp_rig_FKSetUp.mel
	yjp_rig_FKSetUp $yosSJointName $yosEJointName 6;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc YOS_ControlDivide()
{
	string $yosSJointName = `textFieldGrp -q -text yosStartJointText`;
	string $yosEJointName = `textFieldGrp -q -text yosEndJointText`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	yjp_rig_GroupCreate $charaID;
	ControlDivideRigSetUp $yosSJointName $yosEJointName;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*
global proc YOS_Add_IK_RigSetUp()
{
	string $yosSJointName = `textFieldGrp -q -text yosStartJointText`;
	string $yosEJointName = `textFieldGrp -q -text yosEndJointText`;
	string $PVlocator = `textFieldGrp -q -text yosPVlocatorText`;
	string $charaID = `textFieldGrp -q -text yjp_CharactorIDText`;
	string $charaSetName = `optionMenu -q -v Rig_CharactorIDListMenu`;
	int $ReverseKnee = `checkBox -q -v ReverseKneeCheckBox`;
	global string $ss_RigCharaID ;
	$ss_RigCharaID = $charaID;
	yjp_rig_makeMetaRoot "none" $charaSetName;
	yjp_rig_GroupCreate $charaID;
	yjp_rig_SwichesAddAttr $yosSJointName;
	Add_IK_RigSetUp $yosSJointName $yosEJointName $PVlocator $ReverseKnee;
}
*/
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc YOS_ControlParent()
{
	string $childName,$parentName;
	
	$childName = `textFieldGrp -q -text Ctrl_ChaildField`;
	$parentName = `textFieldGrp -q -text Ctrl_ParentField`;
	
	string $ctrl[] = `ls -sl`;
	if(`size$ctrl` == 2 && $childName == "" && $parentName == "")
	{
		$childName = $ctrl[0];
		$parentName = $ctrl[1];
	}
	
	yjp_rig_ControlParent $childName $parentName;
	return ;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Spline-specific controller setup
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


global proc YOS_SplineControls()
{
	string $yosSJointName = `textFieldGrp -q -text SplineRootJointField`;
	string $yosEJointName = `textFieldGrp -q -text SplineEndJointField`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	string $charaSetName = `textField -q -text yjp_CharactorIDText`;
	
	string $Up = "3";
	
	int $wup = `radioButtonGrp -q -sl sIKupRadioButton`;
	if($wup == 1){$Up = 0;}
	
	int $Split = `intSliderGrp -q -v sIKsplitSlider`;
	int $usetwist = `checkBox -q -v sIKtwistCheckBox`;
	int $Stretch = `checkBox -q -v sIKStretchCheckBox`;
	//ikHandle ns=2 use=1 upZ=3 Stretch=0
	yjp_rig_GroupCreate $charaID;
	yjp_rig_SplineIK $yosSJointName $yosEJointName $Split $usetwist $Up $Stretch $charaSetName;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc doAddMetaNoIkAttr()
{
	string $node[] = `ls -sl`;

    if(! size(ls($node[0]))) error ("addMetaNoIkAttr: node does not exist '" + $node[0] + "'.\n");
    if(!attributeExists("metaNoIk", $node[0]))
			Rig_ControlParentSource $node[0];
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Object display non-display switch(exclusive)/////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc doMeshSwichesSet()
{
	string $charaSetName = `textField -q -text yjp_CharactorIDText`;
	
	string $mesh = `textFieldGrp -q -text MeshDisplaySwichesField`;
	string $meshAttrname = `textFieldGrp -q -text MeshDisplaySwichesNameField`;
	string $List[] = stringToStringArray($mesh, ",");
	
	string $cond[] = `MeshDisplaySwiches $List`;
	
	int $num = size($cond);
	string $handle[] = `yjp_ui_numSwitchBar $meshAttrname 0 $num `;
	yjp_ui_numSwitchConnect $handle[2] "out" $cond;
	
	//character -forceElement $charaSetName ($handle[2] + ".tx");
}
global proc doyjp_UV_pattern()
{
	string $mat = `textFieldGrp -q -text UVpatternMaterialField`;
	string $ctrlname = `textFieldGrp -q -text UVpatternNameField`;
	string $charaID = `textField -q -text yjp_CharactorIDText`;
	
	string $fLayout[] = `columnLayout -q -ca UVpatternPosColumnLayout`;
	int $n;
	float $u[] ;
	float $v[] ;

	for($n=0;$n<size($fLayout);$n++){
		$u[$n] = `floatFieldGrp -q -v1 $fLayout[$n]`;
		$v[$n] = `floatFieldGrp -q -v2 $fLayout[$n]`;
	}
	
	yjp_UV_pattern $mat $u $v $ctrlname;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////AimRig     Aim Constrain the FK Controller
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc doyjp_AimRig()
{
	string $AimNode = `textFieldGrp -q -text AimSetNodeField`;
	string $parentNoad = `textFieldGrp -q -text AimUpParentNodeField`;
	string $TargetNoad = `textFieldGrp -q -text AimTargetParentNodeField`;
	string $AimDir = `optionMenu -q -v AimDiroptionMenu`;
	string $UpDir = `optionMenu -q -v UpDiroptionMenu`;
	
	yjp_rig_Aim $AimNode $parentNoad $TargetNoad $AimDir $UpDir;
	
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////CtrlScaleConnect
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc doyjp_CtrlScaleConnect()
{
	string $ctrlName = `textField -q -text yosStartJointText`;
	yjp_CtrlScaleConnect $ctrlName;
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc doyjp_rig_MultiConstraint()
{
	string $constrainedNode =`textFieldGrp -q -text MConstraintCtrlField`;
	string $array = `textFieldGrp -q -text MConstraintTargetField`;
	string $transOption = `checkBox -q -v MultiConstraintTCheckBox`;
	string $rotOption = `checkBox -q -v MultiConstraintRCheckBox`;
	
	string $targets[] = stringToStringArray($array, ",");
	
	yjp_rig_MultiConstraint($constrainedNode, $targets, $transOption, $rotOption);
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////リグパターンリストをリロード/////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc RigPatternListReLoad()
{
	source getReferenceName.mel;
	$file_path = (`textField -q -text RigPatternListFolderField` + "/");
	string $rigpllist[] = `getFileList -fld $file_path -fs "*.rigp"`;
	string $chara[],$rigpname[];
	textScrollList -e -ra RigPatternScrollList;
	string $joint[] = `ls -type joint`;
	string $ID;
	int $IDexist = -1;
	int $n,$f;
	int $c =0;
	string $localpath = `workspace -q -rd`;
	string $RefFile[] = `file -q -r`;

	if(size($joint) != 0)
	{
		$ID = `getReferenceName $joint[0]`;
	}
	//$locallist = `sort $locallist`;
	for($n=0;$n<`size$RefFile`;$n++)
	{
		string $scenename = `dirname $RefFile[$n]`;
		$localpath = `substitute "/scenes" $scenename "/setup"`;
		string $locallist[] = `getFileList -fld $localpath -fs "*.rigp"`;	
		for ($f=0; $f<size($locallist[$f]);$f++)
		{
			//print ($locallist[$f] +"\n");
			tokenize $locallist[$f] "." $rigpname;
			textScrollList -e -append $rigpname[0] RigPatternScrollList;
			$chara[$c] = $rigpname[0];
			if(`gmatch $rigpname[0] ($ID+"*")`)
			{
				$IDexist = $c;
				$c++;
			}			
		}
	}

	$rigpllist = `sort $rigpllist`;
	for($n=0;$n<`size$rigpllist`;$n++)
	{
		//print ($rigpllist[$n] +"\n");
		tokenize $rigpllist[$n] "." $rigpname;
		textScrollList -e -append $rigpname[0] RigPatternScrollList;
		$chara[$c] = $rigpname[0];
		if(`gmatch $rigpname[0] ($ID+"*")`)
		{
			$IDexist = $c;
			$c++;
		}
	}
	$IDexist = stringArrayFind( $ID, 0, $chara );
	if($IDexist != -1)
	{
		textScrollList -e -si $chara[$IDexist] RigPatternScrollList;
	}

}
///////////////////////////////////////////////////////////////////////////////////////////////
global proc RigPatternListEdit()
{
	print("RigPatternListEdit \n");
	
	//string $file_path = `textField -q -text RigPatternListFolderField`;
	string $charaName[] = `textScrollList -q -si RigPatternScrollList`;
	string $localpath = `workspace -q -rd`;
	string $RefFile[] = `file -q -r`;
	for ($n=0; $n<size($RefFile);$n++)
	{
		string $scenename = `dirname $RefFile[$n]`;
		$localpath = `substitute "/scenes" $scenename "/setup"`;
		string $filePassName = $localpath + "/" + $charaName[0] + ".rigp";
		print ($filePassName +"\n");
		if(`filetest -w $filePassName`){
			system ("load " + $filePassName);
			break;
		}
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc doAutoRigSetUp()
{
	global int $yjp_experiment = 0;
	global string $ss_RigCharaID ;
	global int $RIGversion = 0;
	global int $yjp_RiGctrlColor[];
	$yjp_RiGctrlColor = {17,6,13,13,6,13,7,13,17};//center,FK,IKroot,IKendT,IKendR,PV,SIKroot,SIKmid,SIKend

	string $nextLine,$StringLine[],$as,$buffer[];
	string $localpath ;
	string $sceneName = `file -q -sn`;
	string $RefFile[] = `file -q -r`;
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $charaName[] = `textScrollList -q -si RigPatternScrollList`;	
	if(!size($charaName[0]))
	{
		error ("リストを選択して"+"\n");
	}
	float $startTime = `timerX`;

	int $fileModelList;
	int $n = 0;

	file -f -o $sceneName;
	select -cl ;
	currentTime 0 ;
	//if(`window -ex "scriptEditorPanel1Window"`)deleteUI "scriptEditorPanel1Window";
	if(`window -ex "nodeEditorPanel1Window"`)deleteUI "nodeEditorPanel1Window" ;
	//テキストファイルからリグを実行する
	for ($n=0; $n<size($RefFile);$n++)
	{
		string $sceneRefName = `dirname $RefFile[$n]`;
		$localpath = `substitute "/scenes" $sceneRefName "/setup"`;
		if(`filetest -f ($localpath + "/" + $charaName[0] + ".rigp")`){
			print("aru\n");
			
			$StringLine = `freadAllLines ($localpath + "/" + $charaName[0] + ".rigp")`;
			break;
		}
	}
	$file_path = $localpath;
	/*
	$fileModelList = `fopen ($file_path + "/" + $charaName[0] + ".rigp") "r"`;
	freadAllLines
	//print ("testssss" +"\n");
	//print ($fileModelList +"\n");
	$nextLine = `fgetline $fileModelList`;
	while ( size( $nextLine ) > 0 )
	{
		$StringLine[$n] = $nextLine;
 		$nextLine = `fgetline $fileModelList`;
		$n++;
		//print ($StringLine[$n]);
 	}
	fclose $fileModelList;
	*/
	string $ctrl[],$CharaName;
	DisableAll;
	int $sk = `autoKeyframe -q -st` ;
	if($sk == 1)
	{
		autoKeyframe -st 0;
	}
	
	string $refFilePath;
	string $node[];
	int $t = 0;
	string $meshs[];
	string $metaRoot = "";
	string $items[];
	string $sikList[];
	int $siknum = 0;
	string $constList[];
	int $consnum = 0;
	string $targets[];
	string $characetName;
	string $constrainedNode;
	string $parentNode;
	int $transOption;
	int $rotOptio;
	
	print ("Node Check" + "\n") ;
	string $jointArray[];
	string $rigArray[];
	int $rignum =0;
	string $piece[];
	string $uniquemesh[];

	string $addnodelist[];

	for($as in $StringLine)
	{
		print ($as);
		$buffer = stringToStringArray($as, ",\n");
		clear $piece;
		print(">> " + $buffer[0] + "\n");
		switch($buffer[0])
		{
			case "ID":
				print ("reference name "+$buffer[1] + "\n") ;
				if(!`namespace -exists $buffer[1]`)error"The reference name is different.";
				$ss_RigCharaID = $buffer[1];
				
				$CharaName = $ss_RigCharaID + ":";
				$rigArray[size($rigArray)] = $CharaName +"Root";
				$jointArray = `ls -type "joint" ($CharaName+"*")`;
				$jointArray = stringArrayRemoveExact ((`yjp_stringArrayGmatch "*_END" $jointArray`),$jointArray);
				//$refFilePath = `referenceQuery -filename ($buffer[1] + "RN")`;
				
				//$node = `referenceQuery -n $refFilePath`;
				//$CharaName = `getNodeNamespace $node[0]` + ":";
				string $meshNode[] = `listRelatives -ad -ni -type "mesh" ($CharaName + "JOINT")`;
				string $HandList[] = {$CharaName +"HandLa",$CharaName +"HandLb",$CharaName +"HandRa",$CharaName +"HandRb"};
				
				int $num = 0;
				print ("mesh list ////////////////////////////\n");
				for($obj in $meshNode){
					string $mesh = shortNameOf(firstParentOf($obj));
					if(stringArrayCount($mesh, $uniquemesh)==0 && stringArrayCount($mesh, $HandList)==0){
						$uniquemesh[$num] = $mesh;
						print ($uniquemesh[$num]+"\n");
						$num++; 
					} 
				}
				print ("mesh list END /////////////////////////////\n");
				break;
			case "ADDNODE":
				$addnodelist[size($addnodelist)] = $CharaName + $buffer[1];
				break;
			case "FK":
				$buffer[1] = $CharaName + $buffer[1];
				$buffer[2] = $CharaName + $buffer[2];
				$rigArray[size($rigArray)] = $buffer[1];
				
				if(!`objExists $buffer[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("\nNo " + $buffer[1]);
				}
				
				if($buffer[2] != ($CharaName + "none")){
					$rigArray = stringArrayCatenate($rigArray , `SelectJointArray $buffer[1] $buffer[2]`);
					if(!`objExists $buffer[2] `){
						if(stringArrayFind($buffer[2], 0, $addnodelist) == -1)error("\nNo " + $buffer[2]);
					}
				}
				break;
			case "EFK":
				$buffer[1] = $CharaName + $buffer[1];
				$buffer[2] = $CharaName + $buffer[2];
				$rigArray[size($rigArray)] = $buffer[1];
				if(!`objExists $buffer[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("\nNo " + $buffer[1]);
				}
				if(!`objExists $buffer[2]`){
					if(stringArrayFind($buffer[2], 0, $addnodelist) == -1)error("\nNo " + $buffer[2]);
				}
				break;
			case "IK":
			case "aIK":
			case "iIK":
				$buffer[1] = $CharaName + $buffer[1];
				$buffer[2] = $CharaName + $buffer[2];
				$buffer[3] = $CharaName + $buffer[3];
				//$rigArray = stringArrayCatenate($rigArray , `SelectJointArray $buffer[1] $buffer[2]`);
				//$rigArray[$rignum] = $buffer[3];
				//$rignum++;				
				if(!`objExists $buffer[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("No " + $buffer[1]);
				}
				
				if(!`objExists $buffer[2]`){
					if(stringArrayFind($buffer[2], 0, $addnodelist) == -1)error("No " + $buffer[2]);
				}
				
				if($buffer[3] != ($CharaName + "none"))
				{
					if(!`objExists $buffer[3] `){
						if(stringArrayFind($buffer[3], 0, $addnodelist) == -1)error("No " + $buffer[3]);
					}
				}
				break;
			case "SIKa":
				$sikList[$siknum] = $buffer[1];
				$siknum++;
				if(stringArrayCount($buffer[1],$sikList)>1)error("Exists "+$buffer[1]);
				$sikList[$siknum] = $buffer[2];
				$siknum++;
				if(stringArrayCount($buffer[2],$sikList)>1)error("Exists "+$buffer[2]);			
				$buffer[1] = $CharaName + $buffer[1];
				$buffer[2] = $CharaName + $buffer[2];
				$buffer[3] = $CharaName + $buffer[3];
				$piece = `SelectJointArray $buffer[1] $buffer[2]`;
				$piece[0] = $buffer[1];
				if(size($piece)>0)
				{
					string $string2[] = `listRelatives -ad -type "joint" $buffer[1]`;
					$piece = stringArrayCatenate($piece, $string2);
				}
				$rigArray = stringArrayCatenate($rigArray , $piece );
				if(!`objExists $buffer[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("No " + $buffer[1]);
				}
				
				//if(!`objExists $buffer[2]`)error("No " + $buffer[2]);

				break;
			case "SIKFK":
				$buffer[1] = $CharaName + $buffer[1];
				$buffer[2] = $CharaName + $buffer[2];
				$buffer[3] = $CharaName + $buffer[3];
				//$piece = `SelectJointArray $buffer[1] $buffer[2]`;
				$rigArray = stringArrayCatenate($rigArray , $piece );
				if(!`objExists $buffer[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("No " + $buffer[1]);
					}
				//if(!`objExists $buffer[2]`)error("No " + $buffer[2]);
				break;
				/*
			case "RIB":
				string $piece[];
				$piece = {$buffer[4],$buffer[5],$buffer[6],$buffer[7],$buffer[8],$buffer[9],$buffer[10],$buffer[11],$buffer[12],$buffer[13],$buffer[14],$buffer[15]};
				$piece = stringArrayAddPrefix($piece,$CharaName);
				$rigArray = stringArrayCatenate($rigArray , $piece);

				if(!`objExists $piece[0]`){
					if(stringArrayFind($buffer[0], 0, $addnodelist) == -1)error("No " + $buffer[0]);
				}
				if(!`objExists $piece[1]`){
					if(stringArrayFind($buffer[1], 0, $addnodelist) == -1)error("No " + $buffer[1]);
				}
				
				break;
			*/
			case "NoIK":
				$buffer[1] = $CharaName + $buffer[1];
				$rigArray[$rignum] = $buffer[1];
				$rignum++;
				if(!`objExists $buffer[1]`)error("No " + $buffer[1]);
				break;
			case "Multi":
				print($buffer[3] + "\n");
				$constList[$consnum] = $buffer[3];
				$consnum++;
				if(stringArrayCount($buffer[3],$constList)>1)error("Exists "+$buffer[3]);
				/*
				$targets = stringArrayRemove($items, $buffer);
				for ($n=0;$n<size($targets);$n++)
				{
					if($targets[$n] != "Ground")
					{
						$targets[$n] = $CharaName + $targets[$n];
						if(!`objExists $targets[$n]`)error("No " + $targets[$n]);
					}
				}*/
				break;
			case "Swiche":
				for ($n=3;$n<size($buffer);$n++)
				{
					$meshs[$t] = $CharaName + $buffer[$n];
					if(!`objExists $meshs[$t]`)error("No " + $meshs[$t]);
					$t++;
				}
				clear $meshs;
				break;
			case "UnityVis":
				
				if($buffer[1] == "etcVis"){
					print($buffer[1] + " UnityVisチェック\n");
					for ($n=2;$n<size($buffer);$n++)
					{
						$meshs[$t] = $CharaName + $buffer[$n];
						$t++;
					}
					$uniquemesh = stringArrayRemoveExact($meshs, $uniquemesh) ;
					clear $meshs;				
				}break;

		}
	}
	clear $addnodelist;
	if(size($uniquemesh)>0){
		//Objects with undefined visibility
		for ($n=0; $n<size($uniquemesh);$n++)
		{
			print($uniquemesh[$n] + "\n");
		}
		//error("Objects with undefined visibility ");		
	}
	//
	print("SIK_Joint const check\n");
	for ($n=0; $n<size($sikList);$n++)
	{
		string $sikctrl = $sikList[$n] + "_2_IK_ctrl";
		if(`gmatch $sikList[$n] "*_END"`)$sikctrl = $sikList[$n] + "_IK_ctrl";
		if(stringArrayCount($sikctrl,$constList)==0)print("No setting > "+$sikctrl+"\n");
	}
	/*
	$rigArray = stringArrayRemoveDuplicates($rigArray);
	string $noRigArray[] = stringArrayRemove($rigArray ,$jointArray);
	string $passjoint[] ={($CharaName + "Root")};
	$noRigArray = stringArrayRemove($passjoint ,$noRigArray);
	if(size($noRigArray) != 0)
	{
		python("import winsound as ws");
		python("ws.PlaySound( 'SystemAsterisk', ws.SND_ALIAS )");	
		string $objname = stringArrayToString($noRigArray, "\r");
		print ("\nSome joints have no rig settings/////////////\n" + $objname+ "\n/////////////////////////////\n") ;
		if(size($objname)>100)
		{
			$objname = "Please check in the script editor";
		}
		string $dwImportmode = `confirmDialog
		-title "confirmation"
		-message ("Some joints have no rig settings\n"+ $objname)
			-button "setup"
			-button "cancel"
			-icn "warning"
			-defaultButton "cancel"
			-cancelButton "cancel"
			-dismissString "cancel"`;
		if($dwImportmode == "cancel"){return;}
	}
	*/
	int $countLine = 0;
	int $MaxLine = (size($StringLine));
	//window -e -vis 0 "MayaWindow";
	
	progressWindow
	-title "RigSetUp"
	-progress $countLine
	-isInterruptable true
	-min 0
	-maxValue $MaxLine;
	
	string $CharaSet[];
	int $charasetnum =0;
	string $PV_node;
	string $IKrootNode;
	string $IKendNode;
	string $cond[];
	int $versionnum =0;
	string $metaroot;
	string $FKnode;
	string $FKrootNode;
	string $setName;
	//string $ctrlarray[];

	for($as in $StringLine){
		print ($as +"\n");
		clear $buffer;
		$as = strip( $as ); 
		$buffer = stringToStringArray($as, ",\n");
		switch($buffer[0])
		{
			case "//*":
			break;
			
			case "MEL":
				eval( $buffer[1] );
				$versionnum += 100;
				print($buffer[1] + "\n") ;
			break;
			case "ID":
				print ("ID "+ $buffer[1] +"\n") ;
				string $rootnode;
				if($buffer[2] == ""){
					$rootnode = $buffer[1] +":JOINT";
				}
				if(!`objExists $rootnode`){
					$rootnode = $buffer[1] +":Dummy01";
				}
				string $c[] = `listRelatives -c -type "joint" $rootnode`;

				$rootnode = $c[0];	
				print($rootnode + " rootnode\n");
				
				string $joint[] = `listRelatives -ad -type "joint" $rootnode`;
				for ($n=0; $n<size($joint);$n++){
					setAttr ($joint[$n] +".segmentScaleCompensate") 0;
				}

				//create a set
				$setName = $buffer[1] + "_ctrl";
				sets -em -n $setName;

				//metaroot creation
				print ("yjp_rig_makeMetaRoot " + $rootnode+ " "+$buffer[1] + "\n");
				$metaroot = `yjp_rig_makeMetaRoot $rootnode $buffer[1]`;
				
				//Creating Groups
				yjp_rig_GroupCreate $buffer[1];
				
				//ground controller creation
				print ("yjp_rig_GroundCTRL " + $rootnode+ " "+$buffer[1] + "\n");
				yjp_rig_GroundCTRL $rootnode $buffer[1];
				//$charasetnum++;
				print ("Ground" + "\n");
				
				yjp_Createswiches_ctrl $rootnode $buffer[1];
				global string $yjp_ParentRoot;
				$yjp_ParentRoot = $buffer[1] + ":Root_FK_ctrl";
				$versionnum += 100;
				break;
				
			case "CSET":
				yjp_rig_CharactorIDShortName $buffer[1] $buffer[2];
				$versionnum += 100;
				break;
				
			case "COLLIDER":
				select -r ($CharaName+$buffer[1]);
				makePassiveCollider;
				break;
				
			case "CENTER":
				$ctrlarray[0] = `yjp_rig_CenterCtrlCreate ($CharaName+$buffer[1]) $ss_RigCharaID` ;
				
				sets -e -in $setName $ctrlarray[0];
				//$CharaSet[$charasetnum] = $buffer[2];
				//$charasetnum++;
				print ("CenterCtrl_end:" +"\n");
				Rig_CharactorIDMenu;
				$versionnum += 100;
				break;
				
			case "FK":
				print ("FK_start:" + $buffer[1] + "-" + $buffer[2] + "-" + $buffer[3]+"\n");
				
				if(!`objExists ($CharaName + $buffer[2])`)
				{
					$FKnode = "";
				}
				else
				{
					$FKnode = ($CharaName + $buffer[2]);
				}
				string $FKrootNode = $CharaName+$buffer[1];
				$parentNode = $CharaName+$buffer[3];
				yjp_rig_FKSetUp $FKrootNode $FKnode 6;
				
				if(`objExists $parentNode`){
					yjp_rig_ControlParent $FKrootNode $parentNode;
				}
				//$CharaSet[$charasetnum] = $buffer[4];
				//$charasetnum++;
				print ("FK_end:" + $buffer[1] +"\n");
				$versionnum += 100;
				break;
			case "EFK":
				print ("EFK_start:" + $buffer[1] + "-" + $buffer[2] +"\n");
				$FKrootNode = $CharaName+$buffer[1];
				$parentNode = $CharaName+$buffer[3];
				yjp_rig_EmptyFK $FKrootNode $buffer[2];
				if(`objExists $parentNode`){
					yjp_rig_ControlParent $FKrootNode $parentNode;
				}
				//$CharaSet[$charasetnum] = $buffer[4];
				//$charasetnum++;
				print ("EFK_end:" + $buffer[1] +"\n");
				$versionnum += 100;
				break;
			case "ADDNODE":
				print ("ADDNODE_start:" + $buffer[1] +"\n");
				$FKrootNode = $CharaName+$buffer[1];
				$parentNode = $CharaName+$buffer[8];
				
				float $tr[] = {float($buffer[2]) ,float($buffer[3]), float($buffer[4])};
				float $rot[] = {float($buffer[5]) ,float($buffer[6]), float($buffer[7])};
				if(`gmatch $FKrootNode "*:*_joint"`){
					select -cl ;
					$FKrootNode = `substitute "_joint" $FKrootNode ""`;
					joint -n $FKrootNode;
					setAttr ($FKrootNode+".t") $tr[0] $tr[1] $tr[2];
					setAttr ($FKrootNode+".r") $rot[0] $rot[1] $rot[2];
					parent $FKrootNode ($CharaName + ":RIG_DO_NOT_TOUCH");
					yjp_rig_FKSetUp $FKrootNode "none" 6;
				}
				else{
					spaceLocator -p 0 0 0  -n $FKrootNode;
					print($FKrootNode + " 2\n");
					setAttr ($FKrootNode+".t") $tr[0] $tr[1] $tr[2];
					setAttr ($FKrootNode+".r") $rot[0] $rot[1] $rot[2];
					parent $FKrootNode ($CharaName + ":RIG_DO_NOT_TOUCH");
					if(`objExists $parentNode`){
						yjp_rig_EmptyFK $FKrootNode 1;
					}
				}
				if(`objExists $FKrootNode` && `objExists $parentNode`){
					print($parentNode + "\n");
					yjp_rig_ControlParent $FKrootNode $parentNode;
				}
				print ("ADDNODE_end:" + $buffer[1] +"\n");
				$versionnum += 100;
				break;
			case "IK":
			case "iIK":
			case "aIK":
				print ("IK_start:"+ $CharaName+$buffer[1] +"\n");
				int $mode = 0;
				if($buffer[0] == "iIK"){$mode = 1;} 
				else if($buffer[0] == "aIK"){$mode = 2;}
				$PV_node = $CharaName+$buffer[3];
				if($buffer[3] == "none")
				{
					$PV_node = "none";
				}
				$IKrootNode = $CharaName+$buffer[1];
				$IKendNode = $CharaName+$buffer[2];
				$parentNode = $CharaName+$buffer[4];

				yjp_rig_IKFKSetUp $IKrootNode $IKendNode $PV_node $mode;
				
				if(`objExists $parentNode`){
					yjp_rig_ControlParent $IKrootNode $parentNode;
					yjp_rig_ControlParent ($IKrootNode+"PV_IK_ctrl") $parentNode;
				}
				//$CharaSet[$charasetnum] = $buffer[5];
				//$charasetnum++;
				$versionnum += 200;
				print ("IK_end:" + $CharaName+$buffer[1] + "\n");
				break;
			
			case "IKfoot":
				print ("IKfoot_start:"+ $CharaName+$buffer[1] +"\n");
				string $rootJoint = $CharaName + $buffer[1];
				string $AnkleJoint = $CharaName + $buffer[2];
				string $pvnode = $CharaName + $buffer[3];
				string $HeelNode = $CharaName + $buffer[4];
				string $SwivelNode = $CharaName + $buffer[5];
				string $BankInNode = $CharaName + $buffer[6];
				string $BankOutNode = $CharaName + $buffer[7];
				int $ReverseLeg = $CharaName + $buffer[8];
				string $charaName = $CharaName + $buffer[9];
				
				if($buffer[3] == "none")
				{
					$pvnode = "none";
				}
				//IKFKFootRigSetUp(string $yosSJointName , string $yosEJointName , string $PVlocator , string $Heel , string $Swivel , string $BankIn , string $BankOut ,int $ReverseLeg , string $charaName)
				//IKFKFootRigSetUp $rootJoint $AnkleJoint $pvnode $HeelNode $SwivelNode $BankInNode $BankOutNode $ReverseLeg $charaName;
				print ("IKfoot_end:" + $rootJoint + "\n");
				$versionnum += 300;
				break;
			
			case "Parent":
				//Pair controllers with each other
				$ctrl[0] = $CharaName + $buffer[1] ;
				$ctrl[1] = $CharaName + $buffer[2] ;
				if(!`objExists $ctrl[0]` || !`objExists $ctrl[1]`){
					print (" no parent " + $ctrl[0]+ " " +$ctrl[1]+"\n") ;
					window -e -vis 1 "MayaWindow";
					return;
				}
				yjp_rig_ControlParent $ctrl[0] $ctrl[1];
				$versionnum += 100;
				break;
			
			case "SIK":
				print ("\nSIK:start\n") ;
				string $SIKrootJoint = $CharaName + $buffer[1];
				string $SIKendJoint = $CharaName + $buffer[2];
				int $numSpan = $buffer[3];
				int $usetwist = $buffer[4];
				string $upvec = $buffer[5];
				int $Stretch = $buffer[6];
				string $rootParent = $CharaName + $buffer[7];
				string $endParent = $CharaName + $buffer[8];
				//global proc string[] yjp_rig_SplineIK(string $startjoint ,string $endjoint,int $numSpan,int $usetwist,string $up,int $Stretch, string $charaName)
				string $SIKctrl[] = `yjp_rig_SplineIK $SIKrootJoint $SIKendJoint $buffer[3] $buffer[4] $buffer[5] $buffer[6] $buffer[9]`;
				//print ("SIKrootJoint>" + $SIKrootJoint + " rootParent>" +$rootParent+ "\n") ;
				if(`objExists $rootParent`)
				{
					string $si;
					for($si in $SIKctrl)
					{
						print($si + " "+$rootParent+"\n");
						
						yjp_rig_ControlParent $si $rootParent;
					}
				}
				//yjp_rig_ControlParent $SIKrootJoint $rootParent;
				int $sikn;
				/*
				if(`objExists $endParent`)
				{
					for($sikn=1;$sikn<`size$SIKctrl`;$sikn++)
					{
						print ("\nsik_rig "+$SIKctrl[$sikn]+ "\n") ;
						yjp_rig_ControlParent $SIKctrl[$sikn] $endParent;
					}
				}
				*/
				sets -e -in $setName $SIKctrl;
				//$CharaSet[$charasetnum] = $buffer[9];
				//$charasetnum++;
				$versionnum += 2000;
				break;
			case "SIKFK":
				print ("\nSIKFK:start\n") ;
				$SIKrootJoint = $CharaName + $buffer[1];
				$SIKendJoint = $CharaName + $buffer[2];
				$numSpan = $buffer[3];
				$usetwist = $buffer[4];
				$upvec = $buffer[5];
				$Stretch = $buffer[6];
				$rootParent = $CharaName + $buffer[7];
				$endParent = $CharaName + $buffer[8];
				//global proc string[] yjp_rig_SplineIK(string $startjoint ,string $endjoint,int $numSpan,int $usetwist,string $up,int $Stretch, string $charaName)
				if($yjp_experiment == 1){
					$SIKctrl = `yjp_rig_SplineIKFK2 $SIKrootJoint $SIKendJoint $buffer[3] $buffer[4] $buffer[5] $buffer[6] $buffer[9]`;
				}
				else
				{
					$SIKctrl = `yjp_rig_SplineIKFK $SIKrootJoint $SIKendJoint $buffer[3] $buffer[4] $buffer[5] $buffer[6] $buffer[9]`;
				}
				//print ("SIKrootJoint>" + $SIKrootJoint + " rootParent>" +$rootParent+ "\n") ;
				if(`objExists $rootParent`)
				{
					string $si;
					for($si in $SIKctrl)
					{
						print("SIKFKparent " + $si + " "+$rootParent+"\n");
						
						yjp_rig_ControlParent $si $rootParent;
					}
				}
				//yjp_rig_ControlParent $SIKrootJoint $rootParent;
				/*
				if(`objExists $endParent`)
				{
					for($sikn=1;$sikn<`size$SIKctrl`;$sikn++)
					{
						print ("\nsik_rig "+$SIKctrl[$sikn]+ "\n") ;
						yjp_rig_ControlParent $SIKctrl[$sikn] $endParent;
					}
				}
				*/
				sets -e -in $setName $SIKctrl;
				//$CharaSet[$charasetnum] = $buffer[9];
				//$charasetnum++;
				$versionnum += 2000;
				break;
			case "RIB":
				print ("\nRIB:start\n") ;
				//$num $charaName $parent
				$items = {$buffer[0],$buffer[1],$buffer[2],$buffer[3]};
				$targets = stringArrayRemove($items, $buffer);
			
				string $parentNode = $CharaName + $buffer[3];
				$targets = `stringArrayAddPrefix $targets $CharaName`;
			
				string $baseCubectrl = `yjp_rig_Ribbon $buffer[1] $buffer[2] $targets`;
				print ("\n\n\n\n\n\n\n"+$baseCubectrl + " "+$parentNode +"\n\n\n\n\n\n\n\n\n") ;
				if(`objExists $parentNode`)parent $baseCubectrl $parentNode ;
				
				//$CharaSet[$charasetnum] = $charaName;
				//$charasetnum++;
				$versionnum += 3000;
				break;
			case "SIK2":
				print ("\nSIK2:start\n") ;
				$SIKrootJoint = $CharaName + $buffer[1];
				$SIKendJoint = $CharaName + $buffer[2];
				$usetwist = $buffer[3];
				$rootParent = $CharaName + $buffer[4];
				$endParent = $CharaName + $buffer[5];
				//$SIKctrl = `yjp_rig_SplineIKFK $SIKrootJoint $SIKendJoint $buffer[3] $buffer[4] $buffer[5] $buffer[6] $buffer[9]`;
				//$SIKctrl = `yjp_rig_SplineIK2 $SIKrootJoint $SIKendJoint $usetwist $buffer[6]`;
				if(`objExists $rootParent`)yjp_rig_ControlParent $SIKrootJoint $rootParent;
				if(`objExists $endParent`)
				{
					for($sikn=1;$sikn<`size$SIKctrl`;$sikn++)
					{
						print ("\nsik_rig "+$SIKctrl[$sikn]+ "\n") ;
						yjp_rig_ControlParent $SIKctrl[$sikn] $endParent;
					}
				}
				//$CharaSet[$charasetnum] = $buffer[9];
				//$charasetnum++;
				$versionnum += 2000;
				
				break;
			case "AIM":
				print ("AIM:start"+ "\n") ;
				
				string $AimNode = $CharaName + $buffer[1];
				string $UpParentNoad = $CharaName + $buffer[2];
				string $TargetParentNoad = $CharaName + $buffer[3];
				string $AIMDir = $buffer[4];
				string $AIMUpDir = $buffer[5];
				print ($CharaName + $AimNode+" "+ $UpParentNoad + " " + $TargetParentNoad +" "+ $AIMDir +" "+ $AIMUpDir + "\n") ;
				//global float $yjp_AimTargetLen = $buffer[6];
				//global float $yjp_AimUpLen = $buffer[7];
				yjp_rig_Aim $AimNode $UpParentNoad $TargetParentNoad $AIMDir $AIMUpDir ;
				print ("AIM:end"+ "\n") ;
				$versionnum += 3000;
				break;
			
			case "SWING":
				yjp_rig_SwingJointFKsetup ($CharaName + $buffer[1]) ($CharaName + $buffer[2]) ($CharaName + $buffer[3]) ($CharaName + $buffer[4]) $buffer[5];
				break;
			
			case "ADDIK":
			/*
				Add_IK_RigSetUp ($CharaName+$buffer[1]) ($CharaName + $buffer[2]) ($CharaName + $buffer[3]) $buffer[4] ;
				$CharaSet[$charasetnum] = $buffer[4];
				$charasetnum++;
				break;
			
			case "SourceP":
				//Follow the controller to the original joint.
				if(`objExists ($CharaName + $buffer[1] + "_FK_ctrl")`)
				{
					Rig_ControlParentSource ($CharaName + $buffer[1] + "_FK_ctrl");
				}
				break;
			*/
			case "SourcePsdk":
				string $sourecNode;
				//For spline IK to follow the controller to the original joint
				$sourecNode = ($CharaName + $buffer[2]);
				
				string $sdk[] = `listRelatives -p ($CharaName + $buffer[1])`;
				parentConstraint -mo -weight 1 $sourecNode $sdk[0];
				break;
			
			case "Div":
			case "Divide":
				//Percentage rotation-following controller $buffer[3]
				$ctrl[0] = $CharaName + $buffer[2] + "_FK_ctrl";
				ControlDivideRigSetUp $ctrl[0] ($CharaName + $buffer[1]);
				break;
			case "CLAMP":
				//Percentage rotation-following controller $buffer[3]
				$ctrl[0] = $CharaName + $buffer[2] + "_FK_ctrl";
				string $CtrlNode = $CharaName + $buffer[1];
				string $targetjoint = $CharaName + $buffer[2];
				string $BasePoint = $CharaName + $buffer[3];
				float $min[]={float($buffer[4]),float($buffer[5]),float($buffer[6])};
				float $maX[]={float($buffer[7]),float($buffer[8]),float($buffer[9])};
				float $mag[]={float($buffer[10]),float($buffer[11]),float($buffer[12])};
				int $dir = int($buffer[13]);
				float $offset[]={float($buffer[14]),float($buffer[15]),float($buffer[16])};
				string $pa[] = `yjp_rig_AimClamp $CtrlNode $targetjoint $BasePoint $min[0] $min[1] $min[2] $maX[0] $maX[1] $maX[2] $mag[0] $mag[1] $mag[2] $dir`;
				setAttr ($pa[2] + ".target[0].targetOffsetTranslate") $offset[0] $offset[1] $offset[2] ;
				break;
			case "NoIK":
			
				//Add node to ignore IK
				addMetaNoIkAttr ($CharaName + $buffer[1]);
				break;
			
			case "Multi":
				$items = {$buffer[0],$buffer[1],$buffer[2],$buffer[3]};
				$targets = stringArrayRemove($items, $buffer);
				$constrainedNode = $CharaName + $buffer[3];
				print ("ctrl>>" + $constrainedNode + "\n") ;
				string $cNode[] = `pickWalk -d up $constrainedNode`;
				print (">>>>" + $cNode[0] + "\n") ;
				string $constrainetJoint[] = `pickWalk -d up $cNode[0]`;
				
				print ("...." + $constrainetJoint[0] + "\n") ;
				$transOption = $buffer[1];
				$rotOption = $buffer[2];
				for($n=0;$n<`size$targets`;$n++){
					//Ground_FK_ctrl
					print ("hazime "+$targets[$n]+ "\n") ;
					print ($CharaName+ "\n") ;
					$versionnum += 1;
					
					if(!`gmatch $targets[$n] ("*:*")`){
						$targets[$n] = $CharaName + $targets[$n];
					}
					else{
						$targets[$n] = `substitute $CharaName $targets[$n] ""`;
					}
					print ("kaitou " + $targets[$n]+ "\n") ;
				}
				yjp_rig_MultiConstraint($constrainedNode, $targets , $transOption, $rotOption);
				//yjp_rig_MultiConstraint2($constrainedNode, $targets , $transOption, $rotOption);
				//yjp_matrixConstraint($constrainedNode,$cNode[0],$transOption , $rotOption , $targets);
				resetAttrs $constrainedNode;
				$versionnum += 1000;
				break;
			case "Swiche":
				print ("Swiche_start:" +"\n");
				//string $title, int $min, int $max, int $float, string $typeAttr[]
				
				$t=0;
				clear $cond;
				clear $meshs;
				int $dummyCheck =0;
				for ($n=3;$n<size($buffer);$n++)
				{
					$versionnum += 1;
					$meshs[$t] = $CharaName + $buffer[$n];//
					//$meshs[$t] = $buffer[$n];//
					//connectAttr -f ($meshs[$t] + ".visibility") ($meshs[$t] + "Shape.visibility");
					print ("Swiche:" +$meshs[$t]+ "\n");
					if(isParentOf(($CharaName+"NOTOUTPUT"), $meshs[$t])){
						$dummyCheck=1;
					}
					$t++;
				}
				$cond = `MeshDisplaySwiches  $meshs`;
				
				int $num = size($cond);
				string $handle[] = `yjp_ui_numSwitchBar ($CharaName + $buffer[2]) 0 $num`;
				yjp_ui_numSwitchConnect $handle[2] "out" $cond;
				
				if($dummyCheck){
					
				}
				//character -forceElement $buffer[1] ($handle[2]+".tx");
				$metaRoot = `yjp_rig_getMetaRoot $ss_RigCharaID`;
				string $ControlsGrp[] = `listConnections -d 1 ($metaRoot + ".Controls")`;
				parent $handle[0] $ControlsGrp[0];
				
				//$CharaSet[$charasetnum] = $buffer[1];
				//$charasetnum++;
				print ("Swiche_end:" + "\n");
				$versionnum += 1000;
				break;
			case "UnityVis":
				print ("UnityVis_start:" +"\n");
				//A single attribute toggles between showing and hiding.
				//string $title, int $min, int $max, int $float, string $typeAttr[]
				
				$t=0;
				for ($n=2;$n<size($buffer);$n++)
				{
					$versionnum += 1;
					$meshs[$t] = $CharaName + $buffer[$n];//Processed with character ID prefix
					//$meshs[$t] = $buffer[$n];//Use rigp-file mesh names
					//connectAttr -f ($meshs[$t] + ".visibility") ($meshs[$t] + "Shape.visibility");
					print ("SwicheVis:" +$meshs[$t]+ "\n");
					$t++;
				}
				yjp_unity_SwicheVis ($CharaName + $buffer[1]) $meshs;
				
				//$CharaSet[$charasetnum] = $buffer[1];
				//$charasetnum++;
				print ("UnityVis_end:" + "\n");
				$versionnum += 1000;
				break;
			/*
			case "Swiche2":
				print ("SwicheID_start:" +"\n");
				//Switching by attribute value
				//string $title, int $min, int $max, int $float, string $typeAttr[]
				
				$t=0;
				for ($n=3;$n<size($buffer);$n++)
				{
					$meshs[$t] = $CharaName + $buffer[$n];//Processed with character ID prefix
					//$meshs[$t] = $buffer[$n];//Use rigp-file mesh names
					//connectAttr -f ($meshs[$t] + ".visibility") ($meshs[$t] + "Shape.visibility");
					print ("Swiche:" +$meshs[$t]+ "\n");
					$t++;
				}
				$cond = `MeshDisplaySwiches $meshs`;
				//Based on 8 patterns
				//int $num = size($cond);
				string $handle[] = `yjp_ui_numSwitchBar ($CharaName + $buffer[2]) 0 8`;
				yjp_ui_numSwitchConnect $handle[2] "out" $cond;
				
				character -forceElement $buffer[1] ($handle[2]+".tx");
				$metaRoot = `yjp_rig_getMetaRoot $ss_RigCharaID`;
				string $ControlsGrp[] = `listConnections -d 1 ($metaRoot + ".Controls")`;
				parent $handle[0] $ControlsGrp[0];
				
				$CharaSet[$charasetnum] = $buffer[1];
				$charasetnum++;
				print ("Swiche_end:" + "\n");
				break;
			
			case "UnityVis2":
				print ("UnityVis_start:" +"\n");
				//Switching by attribute value
				//string $title, int $min, int $max, int $float, string $typeAttr[]
				
				$t=0;
				for ($n=2;$n<size($buffer);$n++)
				{
					$meshs[$t] = $CharaName + $buffer[$n];//Processed with character ID prefix
					//$meshs[$t] = $buffer[$n];//Use rigp-file mesh names
					//connectAttr -f ($meshs[$t] + ".visibility") ($meshs[$t] + "Shape.visibility");
					print ("SwicheVis:" +$meshs[$t]+ "\n");
					$t++;
				}
				yjp_unity_SwicheVis2 ($CharaName + $buffer[1]) $meshs;
				
				$CharaSet[$charasetnum] = $buffer[1];
				$charasetnum++;
				print ("UnityVis_end:" + "\n");
				break;
			*/
			case "Bridge":
				$constrainedNode = $CharaName + $buffer[1];
				print ("ctrl>>" + $constrainedNode + "\n") ;
				$U = $buffer[2];
				$V = $buffer[3];
				
				$items = {$buffer[0],$buffer[1],$buffer[2],$buffer[3]};
				$targets = stringArrayRemove($items, $buffer);
			
				string $posnode[],$bindjoint[];
				for($n=0;$n<`size$targets`;$n++)
				{
					$targets[$n] = $CharaName + $targets[$n];
					if(`gmatch $targets[$n] "*!*"`)
					{
						$bindjoint[size($bindjoint)] = `substitute "!" $targets[$n] ""`;
					}
					else
					{
						$posnode[size($posnode)] = $targets[$n];
					}
				}
				yjp_rig_interpolation($constrainedNode ,$U,$V,$posnode,$bindjoint);
			
				//resetAttrs $constrainedNode;
				$versionnum += 1000;
				delete $posnode;
				break;

			case "Bend":
				//ADDNODE
				print ("Bend_start:" + $buffer[1] +"\n");
				string $Driven = $CharaName+$buffer[1];
				string $Driver = $CharaName+$buffer[2];
				string $ctrl = $CharaName+$buffer[3];

				float $bendVal = float($buffer[4]);
				float $rollVal = float($buffer[5]);
				float $axisvalx = float($buffer[6]);
				yjp_rig_BendConst( $Driven, $Driver, $ctrl, $bendVal, $rollVal, $axisvalx);
				//$charasetnum++;
				print ("Bend_end:" + $buffer[1] +"\n");
				$versionnum += 100;
				break;

			case "eCurve":
				string $eCurvename = $CharaName + $buffer[1];
				print ("eCurve>>" + $constrainedNode + "\n") ;
				string $curveName = $CharaName + $buffer[2];
				
				string $edgeID[];
				for($n=3;$n<`size$buffer`;$n++)
				{
					$edgeID[size($edgeID)] = $buffer[$n];
				}
				yjp_polyToCurve($eCurvename,$curveName,$edgeID);

				$versionnum += 1000;
				break;

			case "AngleRe":
				string $ARbaseNode = $CharaName + $buffer[1];
				string $ARtarget = $CharaName + $buffer[2];

				string $ReactNode = $CharaName + $buffer[6];

				string $ARctrl;
				$ARctrl = $CharaName + $buffer[9];
				float $max = 0;
				if(size($buffer)>10){
					$max = $buffer[9];
					$ARctrl = $CharaName + $buffer[10];
				}
				
				yjp_rig_AngleReaction $ARbaseNode $ARtarget $buffer[3] $buffer[4] $buffer[5] $ReactNode $buffer[7] $buffer[8] $max $ARctrl;

				$versionnum += 1000;
				break;

			case "Dist":
				string $DDbaseNode = $CharaName + $buffer[1];
				string $DDtarget = $CharaName + $buffer[2];

				string $DDReactNode = $CharaName + $buffer[4];
				string $DDctrl = $CharaName + $buffer[9];

				yjp_rig_distanceDriven $DDbaseNode $DDtarget $buffer[3] $DDReactNode $buffer[5] $buffer[6] $DDctrl;
				$versionnum += 1000;
				break;
			case "Scale":
				yjp_CtrlScaleConnect ($CharaName + $buffer[1] + "_FK_ctrl");
				$versionnum += 1000;
				break;
				
			case "CTRL":
				//Replaces CTRL
				print ("CTRL_UI change start:" + $buffer[1] + "-" + $buffer[2] +"\n");
				string $newcurve ;
				string $UIchangeNode = $CharaName+$buffer[1];
				int $CTRLcolor = 6;
				if($buffer[11] != "")$CTRLcolor = $buffer[11];

				if(`getAttr -se ($UIchangeNode + ".visibility")`)setAttr ($UIchangeNode + ".visibility") 1;
				
				if($buffer[2] == "Square")$newcurve = `RigCurveSquare "newcurve" $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Square2")$newcurve = `RigCurveSquare2 "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Circle")$newcurve = `RigCurveCircle "newcurve" $buffer[3] 6`;
				if($buffer[2] == "Circle2")$newcurve = `RigCurveCircle2 "newcurve"  $buffer[3] 6`;
				if($buffer[2] == "Box")$newcurve = `RigCurveBox "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Cross")$newcurve = `RigCurveCross "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Sphere")$newcurve = `RigCurveSphere "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Pyramid")$newcurve = `RigCurvePyramid "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "Rhombus")$newcurve = `RigCurveRhombus "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "BoxCenter")$newcurve = `RigCurveBoxCenter "newcurve"  $buffer[3] $buffer[4] 6`;
				if($buffer[2] == "FootBox")$newcurve = `RigFootCurveBox "newcurve"  $buffer[3] $buffer[4] 6`;

				if(size($buffer)>5){

					rotate -r -pgp -ws -fo $buffer[8] $buffer[9] $buffer[10] ;
					move -r -cs -pgp $buffer[5] $buffer[6] $buffer[7] ;
				}

				yjp_rig_ReplaceCurve $UIchangeNode $newcurve;
				string $Layercheck[] = `listConnections -d 0 -s 1 ($UIchangeNode + ".drawOverride")`;
				if(size($Layercheck)==0){
					setAttr ($UIchangeNode + ".overrideColor") $CTRLcolor;
				}
				
				print ("CTRL_UI change:" + $buffer[1] +"\n");
				$versionnum += 1;
				break;
		}
		$countLine ++;
		print ($countLine+ "\n") ;
		progressWindow -edit
			-progress $countLine
			-status $countLine;
		
		if(`progressWindow -q -ic`)
		{
			progressWindow -endProgress;
			print ("Cancel Setup"+ "\n") ;
			window -e -vis 1 "MayaWindow";
			return ;
		}
		
	}
	setAttr ($metaroot + ".Version") $versionnum;
	
	progressWindow -edit -endProgress;
	EnableAll;
	if($sk == 1)
	{
		autoKeyframe -st 1;
	}
	/*
	string $csc;
	$CharaSet = stringArrayRemoveDuplicates($CharaSet);
	
	for($n=0;$n<`size$CharaSet`;$n++)
	{
		if(`objExists $CharaSet[$n]`)
		{
			if(!`objExists($CharaSet[$n] + "_T")`)
			{
				//select -r ($CharaSet[$n] + "_T");
				//print ($CharaSet[$n]+ " yjp_ClipDeleteAndSource \n") ;
				//yjp_ClipDeleteAndSource;
			
			//string $members[] = `character -q $CharaSet[$n]`;
			//select -r $members ;
				//select -r $CharaSet[$n];
				setKeyframe -breakdown 0 -preserveCurveShape 0 -hierarchy none -controlPoints 0 -shape 1 $CharaSet[$n];
				clip -name ($CharaSet[$n] + "_T") -sc 1 -allAbsolute -startTime 0 -endTime 5 $CharaSet[$n];
				$csc = `character -q -sc $CharaSet[$n]`;
				//clipSchedule -t 1 -e -m 1 $csc;
				setAttr ($CharaSet[$n] + "_T.startFrame") -10;
			}
		}
	}
	*/
	if(`objExists ($CharaName + ":NOTOUTPUT")`)
	{
		string $locList[] = `listRelatives -c ($CharaName + ":NOTOUTPUT")`;
		for($n=0;$n<`size$locList`;$n++)
		{
			print($locList[$n] + "\n");
			string $yjpshape[] = `listRelatives -c -s -ni $locList[$n]`;
			print($yjpshape[0] + "\n");
			if($yjpshape[0]!="")
			{
				if(nodeType($yjpshape[0]) == "locator")
				{
					if(`getAttr -se ($locList[$n] + ".visibility")`)
					{
						setAttr ($locList[$n] + ".visibility") 0;
						print($locList[$n] + " visibility 0\n");
					}
				}
			}
		}
	}
	select -r -ne $setName;

	select -r $setName;

	string $CTRLlist[] = `ls -type "transform" -sl`;

	select -r  $CTRLlist[0];

	yjp_Base_MirrorSetUp ;

	select -r  $CTRLlist[0];

	post_add_swingIntensity;

	select -r  $CTRLlist[0];

	yjp_rig_followParentStringEdit;

	select -r  $CTRLlist[0];
	
	yjp_rig_ReplaceCTRLfile;

	//////////////////////////////////////////////////////////////////////////////////
	
	float $totalTime = `timerX -startTime $startTime`;
	print ("Complete of the Rig:" + $totalTime + "sec"+ "\n");
	
	python("import winsound as ws");
	python("ws.PlaySound( 'SystemAsterisk', ws.SND_ALIAS )");
	
	confirmDialog -title "Rig" -message ("Complete of the Rig:" + $totalTime + "sec") -p RigSetUpWindow;
	yjp_fps_change;
	//yjp_rigchecker;
	//yjp_OverlapNameCheck;
	window -e -vis 1 "MayaWindow";
	return ;
}
//////////////////////////////////////////////////////////////////////////////
global proc Rig_CharactorIDChange()
{
	global string $ss_RigCharaID ;
	$ss_RigCharaID = `optionMenu -q -v Rig_CharactorIDListMenu`;
	if($ss_RigCharaID !="")
	{
		textField -e -text $ss_RigCharaID yjp_CharactorIDText;
		yjp_SetUpTabLock;
	}
}
//////////////////////////////////////////////////////////////////////////////
global proc Rig_CharactorIDMenu()
{
	string $Menuitems[] = `optionMenu -q -ill Rig_CharactorIDListMenu`;
	string $scan,$ID;
	for ($scan in $Menuitems) deleteUI $scan;
	
	string $networknode[] = `ls -type "network" "*MetaRoot"`;
	int $n;
	string $IDname[];
	for($n=0;$n<size($networknode);$n++)
	{
		$IDname[$n] = `getAttr ($networknode[$n] + ".characterID")`;
	}
	for($ID in $IDname)
	{
		menuItem -p "Rig_CharactorIDListMenu" -label $ID;
	}
	yjp_SetUpTabLock;
}
//////////////////////////////////////////////////////////////////////////////
global proc Rig_CharactorIDChange()
{
	string $charaName = `optionMenu -q -v Rig_CharactorIDListMenu`;
	textField -e -text $charaName yjp_CharactorIDText;
	yjp_SetUpTabLock;
}
//////////////////////////////////////////////////////////////////////////////
global proc Rig_CharactorIDMenu()
{
	string $Menuitems[] = `optionMenu -q -ill Rig_CharactorIDListMenu`;
	string $scan,$cs;
	for ($scan in $Menuitems) deleteUI $scan;
	
	string $metalist[] = `yjp_rig_getMetaRootList`;
	string $id;
	if(!size($metalist)){
		string $file[] = `file -q -r`;
		string $rn = `basenameEx $file[0]`;
		string $buffer[];
		tokenize $rn "_" $buffer ;
		$id = $buffer[0];
		menuItem -p "Rig_CharactorIDListMenu" -label $id;
	}
	else{
		for($meta in $metalist){
			$id = `getAttr ($meta + ".characterID")`;
			menuItem -p "Rig_CharactorIDListMenu" -label $id;
		}		
	}

	yjp_SetUpTabLock;
}
//////////////////////////////////////////////////////////////////////////////

global proc yjp_SetUpTabLock()
{
	string $ID = `textField -q -text  yjp_CharactorIDText`;
	string $Set = `textField -q -text  yjp_CharactorIDText`;
	if($ID != "" && $Set != "")
	{
		tabLayout -e -en 1 SetUpTabLayout;
	}
	else
	{
		tabLayout -e -en 0 SetUpTabLayout;
	}
}
//////////////////////////////////////////////////////////////////////////////

global proc createRigPatternFile()
{
	string $fileName;
	string $file[] = `file -q -r`;
	string $rn = `basenameEx $file[0]`;
	string $result = `promptDialog
    -title "FileName"
	-text $rn
    -message "Enter Name:"
    -button "OK" -button "Cancel"
    -defaultButton "OK" -cancelButton "Cancel"
    -dismissString "Cancel"`;
	
	if ($result == "OK") 
	{
    	$fileName = `promptDialog -query -text`;
	}
	else if($result == "Cancel")
	{
		print ("createRigPatternFile Cancel\n");
		return ;
	}
	string $localpath = `workspace -q -rd`;
	$localpath = $localpath + "setup";
	if(!`filetest -d $localpath`)sysFile -md $localpath;

	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $filePassName = $localpath + "/" + $fileName + ".rigp";

	if(`filetest -s $filePassName`){
		print("Already there.\n");
		string $Replace = `confirmDialog -title "createRigFile" -message ($filePassName+" is present. \nOverride?") -p RigSetUpWindow
		-button "Create"
		-button "No"
		-defaultButton "No"
		-cancelButton "No" -dismissString "No"`;
		
		if($Replace == "No")return;
	}
	string $baseRigp = $file_path + "/BasicRig.rigp";
	int $fileNumber;
	if (`filetest -r $baseRigp`)
	{
		string $baseRigText[] = freadAllLines($baseRigp);
		//print ($filePassName +"\n");

		string $jointlist[] =`listRelatives -type "joint" -ad ($rn +":JOINT")`;
		string $jointname[] = stringArrayRemovePrefix($jointlist ,($rn+":"));
		string $bodyjoint[] = {"Root","Pelvis","Spine1","Spine2","Neck","Head","ClavicleR","ShoulderR",
		"ShoulderR","UpArmR","ElbowR","HandR","ClavicleL","ShoulderL","UpArmL","ElbowL","HandL",
		"HipR","KneeR","FootR","HipL","KneeL","FootL","ToeR","ToeL",
		"IJ_KneeR","IJ_WristR","IJ_KneeL", "IJ_WristL",
		"PalmAR", "PalmBR", "PalmCR", "PalmDR","PalmAL", "PalmBL", "PalmCL", "PalmDL",
		"Thumb0R", "Thumb1R", "Thumb2R","Thumb0L", "Thumb1L", "Thumb2L",
		"Index0R", "Index1R", "Index2R","Index0L", "Index1L", "Index2L",
		"Middle0R", "Middle1R", "Middle2R","Middle0L", "Middle1L", "Middle2L",
		"Ring0R", "Ring1R", "Ring2R","Ring0L", "Ring1L", "Ring2L",
		"Little0R", "Little1R", "Little2R", "Little0L", "Little1L", "Little2L"
		};
		//unique joint
		string $Addjoint[] = stringArrayRemove($bodyjoint,$jointname);
		string $parentjoint[];
		
		//baseRigText
		string $linesToWrite[],$stringA[],$deletelist[];
		int $n,$jn;
		int $unique = 0;

		//weapon mesh check
		string $meshlist[] = `listRelatives -c ($rn+ ":NOTOUTPUT")`;
		$meshlist = `yjp_stringArrayGmatch ($rn+ ":wp_"+$rn+"*") $meshlist`;
		$meshlist = stringArrayRemovePrefix((`sort $meshlist`) ,($rn+":"));
		string $wpString = stringArrayToString($meshlist,",");

		//etc mesh check
		string $Excluded[] = {$rn ,"HandLa","HandLb","HandLc","HandLd","HandRa","HandRb","HandRc","HandRd",
			($rn+"_hairA"),"FACE_PPP_000_FG","EYE_PPP_000_FG","TOOTH_PPP_000_FG","LEFT00_FT","T_BIG00_FT ",
			"RIGHT00_FT","UP00_FT","DOWN00_FT","CENTER00_FT","SMALL00_FT","T_OPEN00_FT ","T_OPEN01_FT",
			"M_OP_00_FT ","M_BIG_00_FT","M_BIG_01_FT","M_UP_L00_FT","M_UP_R00_FT","M_DOWN_L00_FT","M_DOWN_R00_FT",
			"E_ANG_L00_FT","E_ANG_R00_FT","E_LAU00_FT","E_SAD00_FT","E_CLO_L00_FT","E_CLO_R00_FT","M_SMALL_00_FT",
			"E_LAU01_FT","E_ANG_01_FT","E_CLO_01_FT","M_TONGUE_00_FT","F_ADD_14_FT","F_ADD_15_FT","F_ADD_16_FT",
			"F_ADD_17_FT","F_ADD_18_FT","F_ADD_19_FT"};
		$meshlist = `listRelatives -ni -ad -type "mesh" ($rn+ ":JOINT") ($rn+ ":MODEL")`;
		string $meshNodeA[];
		for($n=0; $n<size($meshlist);$n++)
		{
			string $DAGnode[] = `listRelatives -p $meshlist[$n]`;
			$meshNodeA[size($meshNodeA)] = $DAGnode[0];
		}
		$meshNodeA = stringArrayRemovePrefix((stringArrayRemoveDuplicates($meshNodeA)),($rn+":"));
		$meshNodeA = stringArrayRemove($Excluded, $meshNodeA);
		string $meshString = stringArrayToString($meshNodeA,",");

		//baseRig edit
		for ($n=0; $n<size($baseRigText);$n++)
		{
			//ID change 
			string $newtext = `substituteAllString $baseRigText[$n] "BaseRig" $fileName`;

			//weapon mesh replace
			if(`gmatch $newtext "*UnityVis,wpVis,*"`)
			{
				$newtext = `substituteAllString $baseRigText[$n] "wp_BaseRig," $wpString`;
			}
			if(`gmatch $newtext "*UnityVis,etcVis,*"`)
			{
				$newtext = `substituteAllString $baseRigText[$n] "visMeshList," $meshString`;
			}
			for ($jn=0; $jn<size($Addjoint);$jn++)
			{
				//Check if additional joints are already in place
				if(`gmatch $newtext ("*"+$Addjoint[$jn]+"*")`&& !`gmatch $newtext "*wp*vis*"` && !`gmatch $newtext "*wpSwitch3*"`)
				{
					//on
					$newtext = stringRemovePrefix ($newtext,"//");
					//If any, put them in an array and do not add them.
					$deletelist[size($deletelist)] = $Addjoint[$jn];
				}
				if(`gmatch $Addjoint[$jn] "*_END"`)
				{
					//||`gmatch $Addjoint[$jn] ("*_01")`||`gmatch $Addjoint[$jn] ("*_02")`
					$deletelist[size($deletelist)] = $Addjoint[$jn] ;
				}
			}
			if($unique)
			{
				$stringA[size($stringA)] = $newtext;
			}
			else
			{
				$linesToWrite[size($linesToWrite)] = $newtext;
			}
			if(`gmatch $newtext "//unique"`)$unique = 1;
		}
		$Addjoint = stringArrayRemove($deletelist,$Addjoint);
		$Addjoint = `stringArrayReverse $Addjoint`;
		for ($n=0; $n<size($Addjoint);$n++)
		{
			//print($Addjoint[$n] + "\n");
			string $parentj[] =`listRelatives -p ($rn+":"+$Addjoint[$n])`;
			$parentjoint[$n] = $parentj[0]; 
		}
		$parentjoint = stringArrayRemovePrefix($parentjoint ,($rn+":"));

		string $addtxt[];
		string $sikNum[] = {""};
		for ($n=0; $n<size($Addjoint);$n++)
		{

			//print("Addjoint "+$Addjoint[$n] + "\n");
			string $SpineCTRL = "";
			string $sikcenter[] = `listRelatives -c ($rn+":"+$Addjoint[$n])`;
			//print("sikcenter " + $sikcenter[0] + "\n");
			float $leng;
			float $Spacing = 0;

			if(`objExists $sikcenter[0]`)
			{
				$Spacing = `getAttr($sikcenter[0]+".tx")`;
				//print("Spacing " + $Spacing + "\n");
			}
			
			if(`gmatch $sikcenter[0] "*_01"`&& $Spacing >3.0)
			{
				//print("SIK\n");
				string $ENDjoint = `substitute "_ROOT" $Addjoint[$n] "_END"`;
				$sikNum[size($sikNum)] = `substitute "_ROOT" $Addjoint[$n] "_01"`;
				$sikNum[size($sikNum)] = `substitute "_ROOT" $Addjoint[$n] "_02"`;
				$sikNum[size($sikNum)] = `substitute "_ROOT" $Addjoint[$n] "_03"`;

				if(!`objExists ($rn+":"+$ENDjoint)`)
				{
					spaceLocator -p 0 0 0 -n "addSIKendLocator";
					matchTransform "addSIKendLocator" $sikcenter[0];
					$leng = `getAttr ($sikcenter[0]+".tx")`;
					move -r -os -wd $leng 0 0 "addSIKendLocator";
					float $tv[] = `xform -q -ws -t "addSIKendLocator"`;
					float $rv[] = `xform -q -ws -ro "addSIKendLocator"`;
					$tv = `yjp_DPointArray $tv`;
					$rv = `yjp_DPointArray $rv`;
					delete "addSIKendLocator";
					$addtxt[size($addtxt)] ="ADDNODE,"+$ENDjoint+","+$tv[0]+","+$tv[1]+","+$tv[2]+","+$rv[0]+","+$rv[1]+","+$rv[2]+",none,"+$rn+"_set";
					$addtxt[size($addtxt)] ="MEL,select -r "+$rn+":"+$Addjoint[$n]+" "+$sikcenter[0]+" "+$rn+":"+$ENDjoint;
				}
				if(`gmatch $parentjoint[$n] "Spine2"`||`gmatch $parentjoint[$n] "Head"`||`gmatch $parentjoint[$n] "Clavicle*"`)
				{
					$SpineCTRL = ",Spine2_FK_ctrl";
				}
				$addtxt[size($addtxt)] ="SIKFK,"+$Addjoint[$n]+","+$ENDjoint+",2,1,nz,0,"+$parentjoint[$n]+","+$parentjoint[$n]+","+$rn+"_set";
				$addtxt[size($addtxt)] ="Multi,1,1,"+$Addjoint[$n]+"_2_IK_ctrl,"+ $parentjoint[$n] + "_FK_ctrl"+$SpineCTRL+",Center_FK_ctrl,Root_FK_ctrl,Ground_FK_ctrl,Global_FK_ctrl,";
				$addtxt[size($addtxt)] ="Multi,1,1,"+$ENDjoint+"_IK_ctrl,"+ $parentjoint[$n] + "_FK_ctrl"+$SpineCTRL+",Center_FK_ctrl,Root_FK_ctrl,Ground_FK_ctrl,Global_FK_ctrl,";			
			}
			else if(stringArrayFind($Addjoint[$n], 0, $sikNum) == -1)
			{
				$leng = 10;
				if(`objExists $sikcenter[0]`){
					$leng = `getAttr ($sikcenter[0]+".tx")`;
					$leng = `yjp_DPoint $leng 1`;
					//print($leng + " aa\n");
					
					$leng = `abs $leng`;
				}
				$addtxt[size($addtxt)] = "FK,"+$Addjoint[$n]+",none,"+$parentjoint[$n]+","+$rn + "_set";
				$addtxt[size($addtxt)] = "CTRL,"+$Addjoint[$n]+"_FK_ctrl,Box,3," + $leng + ",0,0,0,0,0,0,6";				
			}
		}
		$linesToWrite = stringArrayCatenate($linesToWrite,$addtxt);
		$linesToWrite = stringArrayCatenate($linesToWrite,$stringA);

		fwriteAllLines($filePassName,$linesToWrite);
		clear $linesToWrite $addtxt $stringA $parentjoint $Addjoint $jointname $bodyjoint $jointlist;
	}
	else
	{
		$fileNumber = `fopen $filePassName "w"`;
		fprint ($fileNumber, ("ID," + $fileName + "\r\n"));	
		fclose $fileNumber;
	}
	
	RigPatternListReLoad;
	yjp_RigSetUpListEdit;
	
}
//////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////
//Edit rigp data
global proc yjp_RigSetUpListEdit()
{
	if(`window -q -ex yjp_RigSetUpListEditWindow`)deleteUI yjp_RigSetUpListEditWindow;
	string $yjp_RigSetUpListEditWindow = `window -wh 860 800 -s 1 -t "RigSetUpTableEdit" yjp_RigSetUpListEditWindow`;
	string $form = `formLayout`;
	string $Buttton = `columnLayout -adjustableColumn true`;
		rowLayout -nc 3 ;
			textFieldGrp -h 20 -w 300 -cw2 90 200 -l "TextSearch" -cc "yjp_RigEditTextSearch" RigEditTextSearchField;
				popupMenu;
					menuItem -label "Delete" -c ("textFieldGrp -e -tx \"\" RigEditTextSearchField");
			checkBox -h 20 -w 90 -l "AutoSave" -v 0 RigEditAutoSavecheckBox;
			button -h 20 -w 90 -l "close" -c ("deleteUI " + $yjp_RigSetUpListEditWindow );
			setParent ..;
        rowLayout -nc 12 ;
			button -h 25 -w 90 -l "Save" -c ("yjp_RigSetUpTableSave 0") -ann "保存";
			button -h 25 -w 90 -l "SaveAs" -c ("yjp_RigSetUpTableSave 1") -ann "別名保存";
			button -h 25 -w 90 -l "Add_comment" -c ("yjp_RigSetUpAddCommand comment 1000;") ;
			button -h 25 -w 90 -l "Add_CSET" -c ("yjp_RigSetUpTyjp_RigSetUpAddCommandableRefresh CSET 1000;") ;
	
			button -h 25 -w 90 -l "Add_FK" -c ("yjp_RigSetUpAddCommand FK 1000;") ;
			button -h 25 -w 90 -l "Add_IK" -c ("yjp_RigSetUpAddCommand IK 1000;") ;
	
			button -h 25 -w 90 -l "Add_SIK" -c ("yjp_RigSetUpAddCommand SIK 1000;") ;
			button -h 25 -w 90 -l "Add_SIKFK" -c ("yjp_RigSetUpAddCommand SIKFK 1000;") ;
			button -h 25 -w 90 -l "Add_RIB" -c ("yjp_RigSetUpAddCommand RIB 1000;") ;
			button -h 25 -w 90 -l "Add_Parent" -c ("yjp_RigSetUpAddCommand Parent 1000;") ;
			button -h 25 -w 90 -l "Add_Multi" -c ("yjp_RigSetUpAddCommand Multi 1000;") ;
			button -h 25 -w 90 -l "Add_Swiche" -c ("yjp_RigSetUpAddCommand Swiche 1000;") ;


			setParent ..;
	
		rowLayout -nc 12;

			button -h 25 -w 90 -l "FileOpen" -c ("yjp_RigSetUpListOpen 1") -ann "monfFileを開く";
			button -h 25 -w 90 -l "Add_MEL" -c ("yjp_RigSetUpAddCommand MEL 1000;") ;	
			button -h 25 -w 90 -l "Add_UnityVis" -c ("yjp_RigSetUpAddCommand UnityVis 1000;") ;		
			button -h 25 -w 90 -l "Add_IKfoot" -c ("yjp_RigSetUpAddCommand IKfoot 1000;") ;
	
			button -h 25 -w 90 -l "Add_SWING" -c ("yjp_RigSetUpAddCommand SWING 1000;") ;
			button -h 25 -w 90 -l "Add_NoIK" -c ("yjp_RigSetUpAddCommand NoIK 1000;") ;
			button -h 25 -w 90 -l "Add_ADDIK" -c ("yjp_RigSetUpAddCommand ADDIK 1000;") ;
			button -h 25 -w 90 -l "Add_CONNECT" -c ("yjp_RigSetUpAddCommand CONNECT 1000;") ;
			button -h 25 -w 90 -l "Add_AIM" -c ("yjp_RigSetUpAddCommand AIM 1000;") ;
			button -h 25 -w 90 -l "Add_Collider" -c ("yjp_RigSetUpAddCommand  Collider 1000;") ;
			button -h 25 -w 90 -l "Add_CTRL" -c ("yjp_RigSetUpAddCommand  CTRL 1000;") ;
			button -h 25 -w 90 -l "Add_Bridge" -c ("yjp_RigSetUpAddCommand  Bridge 1000;") ;
	
			//button -h 25 -w 90 -l "close" -c ("yjp_ClipDeleteAndSource") -ann "トラックスエディターで選択したクリップをソースごと消します" ;
		setParent ..;
	setParent ..;
    string $MLS = `scrollLayout -horizontalScrollBarThickness 16 -verticalScrollBarThickness 16 `;
    string $rigEditLayout = `columnLayout -adjustableColumn true "yjp_rigpEditcolumnLayout"`;
        setParent ..;
    setParent ..;
	formLayout -edit
		-attachForm     $Buttton    "top" 0
		-attachNone     $Buttton    "bottom"
	    -attachForm     $Buttton    "left"   5
	    -attachForm     $Buttton    "right"  5
	
		-attachForm  $MLS    "top" 80
		-attachForm     $MLS    "bottom" 0
	    -attachForm     $MLS    "left"   0
	    -attachForm     $MLS    "right"  0
		$form;
	showWindow yjp_RigSetUpListEditWindow;
	yjp_RigSetUpTableLoad;
	yjp_RigSetUpTableRefresh $rigEditLayout;
}
//////////////////////////////////////////////////////////////////////////////////////////////
//rigpデータを見るだけ
global proc yjp_RigFileReadOnly()
{
	if(`window -q -ex yjp_RigSetUpListReadWindow`)deleteUI yjp_RigSetUpListReadWindow;
	global string $RigSetUpStringLine[];
	global string $RigSetUpStringLineBackup[];
	$RigSetUpStringLineBackup = $RigSetUpStringLine ;
	string $yjp_RigSetUpListReadWindow = `window -wh 860 800 -s 1 -t "RigSetUpTableRead" yjp_RigSetUpListReadWindow`;
	float $co = 0.1;
	string $form = `formLayout -bgc $co $co $co`;
	string $Buttton = `columnLayout -adjustableColumn true -bgc $co $co $co`;
		rowLayout -nc 2 ;
			//textFieldGrp -h 20 -w 300 -cw2 90 200 -l "TextSearch" -cc "yjp_RigEditTextSearch" RigEditTextSearchField;
			button -h 25 -w 90 -l "close" -c ("deleteUI " + $yjp_RigSetUpListReadWindow);
			setParent ..;
		setParent ..;
    string $MLS = `scrollLayout -horizontalScrollBarThickness 16 -verticalScrollBarThickness 16 `;
        string $rigReadLayout = `columnLayout -adjustableColumn true -bgc $co $co $co` ;
        setParent ..;
    setParent ..;
	formLayout -edit
		-attachForm     $Buttton    "top" 0
		-attachNone     $Buttton    "bottom"
	    -attachForm     $Buttton    "left"   5
	    -attachForm     $Buttton    "right"  5
	
		-attachForm  $MLS    "top" 30
		-attachForm     $MLS    "bottom" 0
	    -attachForm     $MLS    "left"   0
	    -attachForm     $MLS    "right"  0
		$form;
	showWindow $yjp_RigSetUpListReadWindow;
	yjp_RigSetUpTableLoad;
	yjp_RigSetUpTableRefresh $rigReadLayout;
	$RigSetUpStringLine = $RigSetUpStringLineBackup;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableLoad()
{
	global string $RigSetUpStringLine[];
	clear $RigSetUpStringLine;
	global string $ss_RigCharaID ;
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $localpath = `workspace -q -rd`;
	string $RefFile[] = `file -q -r`;
	for ($n=0; $n<size($RefFile);$n++)
	{
		string $scenename = `dirname $RefFile[$n]`;
		$localpath = `substitute "/scenes" $scenename "/setup"`;

		string $fileName[] = `textScrollList -q -si RigPatternScrollList`;
		string $filePassName = $localpath + "/" + $fileName[0] + ".rigp";
		string $AutoSetupPass = $file_path + "/" + $fileName[0] + ".rigp";
		print($AutoSetupPass + "\n");
		
		if(`filetest -f $filePassName`){
			$RigSetUpStringLine = `freadAllLines $filePassName`;
			if(`filetest -w $filePassName`){
				window -e -t ("RigSetUpTableEdit   "+$filePassName) yjp_RigSetUpListEditWindow;
			}
			else{
				window -bgc 0.3 0.1 0.1 -e -t ("RigSetUpTableEdit   "+$filePassName) yjp_RigSetUpListEditWindow;
			}
			break;
		}
		else if(`filetest -f $AutoSetupPass`){
			window -e -t ("RigSetUpTableEdit   "+$AutoSetupPass) yjp_RigSetUpListEditWindow;
		}
	}
	if($ss_RigCharaID == "")
	{
		$ss_RigCharaID = `textField -q -text yjp_CharactorIDText`;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableCheck(string $tf)
{
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;	
	string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[0]`;
	string $rf = `textField -q -tx $FieldArray[3]`;
	
	float $exist = 0.0;
	string $tex = `textField -q -text $tf`;
	$tex = $rf +":" +$tex;
	print ($tex+ "\n") ;
	if(!`objExists $tex`)$exist = 0.3;
	textField -e -bgc $exist  0 0 $tf;
	if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableRefresh(string $Layout)
{
	print ("yjp_RigSetUpTableRefresh\n");
	global string $ss_RigCharaID ;
	global string $RigSetUpStringLine[];
	
	string $joint[] = `ls -type joint`;
	string $ID = $ss_RigCharaID ;
	string $RefNameSpace = $ID+":";
	string $IDset = $ID +"_set";
	string $Line,$buffer[],$win,$tf;
	string $prin;
	string $none = "";
	string $delcome[];
	string $opA;
	string $target;
	string $jointList[],$jointarray[];
	int $val,$m;
	int $num = 1;
	float $exist = 0;
	
	//string $Layout = "yjp_rigpEditcolumnLayout";
	string $clayout[] = `columnLayout -q -ca $Layout`;
	
	if(size($clayout) !=0)deleteUI $clayout;
	
	for($Line in $RigSetUpStringLine)
	{
		$target = "";
		$buffer = stringToStringArray($Line, ",\n");
		
		switch($buffer[0])
		{
			default:
				//print ("default "+$buffer[0] +"\n");
				if(size($buffer) ==1 || containsMultibyte($buffer[0]))
				{
					$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 800 -p $Layout`;
					button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
					text -l "";
					yjp_RigSetUpTableCreateButton "comment" $win $num;
					$num++;
					tokenize $buffer[0] "/" $delcome;
					textField -pht "comment" -tx $delcome[0] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
					setParent ..;
				}
				break;
			case "":
			case "//":
				break;
			case "ID":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -p $Layout`;
				
				text -l "";
				text -l "";
				button  -l "ID";
				textField -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				$ID = $buffer[1]+":";
				setParent ..;$num++;
				break;
			case "CSET":
			case "//CSET":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "characterSet";text -l "shortName";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "CSET")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "CSET" $win $num;
				$num++;
				$tf = `textField -h 25 -pht "characterSet" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				textField -h 25 -pht "short name" -bgc 0 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "CENTER":
			case "//CENTER":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "centerJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "CENTER")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "CENTER" $win $num;
				$num++;
				$tf = `textField -pht "joint or node" -bgc 0 0 0 -tx $buffer[1]`;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
				$tf = `textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[2]`;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "FK":
			case "//FK":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "FK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+" FK\n") ;
				yjp_RigSetUpTableCreateButton "FK" $win $num;
				$num++;
				$tf = `textField -pht "Root joint" -bgc 0 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[2]=="none")
				{
					$exist = 0;
				}
				else if(!`objExists ($RefNameSpace + $buffer[2])`)
				{
					$exist = 0.3;
				}
				else
				{
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;
				}
				$tf = `textField -pht "end joint" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[3] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Root" -c ("textField -e -tx \"Root_FK_ctrl\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head_FK_ctrl\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2_FK_ctrl\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL_FK_ctrl\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);
				//$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[4] `;
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[4] `;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				if(size($jointarray[0]) != 0)
				{
					$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
					$jointList = stringArrayCatenate($jointList, $jointarray);
				}
			*/
				setParent ..;
				break;
			case "EFK":
			case "//EFK":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "EFK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+" EFK\n") ;
				yjp_RigSetUpTableCreateButton "EFK" $win $num;
				$num++;
				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[2]=="none")
				{
					$exist = 0;
				}
				else if(!`objExists ($RefNameSpace + $buffer[2])`)
				{
					$exist = 0.3;
				}
				else
				{
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;
				}
				$tf = `textField -pht "size" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[3] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);;
				
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[4] `;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				if(size($jointarray[0]) != 0)
				{
					$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
					$jointList = stringArrayCatenate($jointList, $jointarray);
				}
			*/
				setParent ..;
				break;
			case "ADDNODE":
			case "//ADDNODE":
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 170 -cw 5 56 -cw 6 56 -cw 7 56 -cw 8 56 -cw 9 56 -cw 10 56 -cw 11 170 -cw 12 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "ADDNODE")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+" ADDNODE\n") ;
				yjp_RigSetUpTableCreateButton "ADDNODE" $win $num;
				$num++;
				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[1] "ADDNODEtextField_#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpNodeCreate " + $tf);
				$tf = `textField -pht "tx" -bgc $exist 0 0 -tx $buffer[2] "ADDNODEtextField_#"` ;
				$tf = `textField -pht "ty" -bgc $exist 0 0 -tx $buffer[3] "ADDNODEtextField_#"` ;
				$tf = `textField -pht "tz" -bgc $exist 0 0 -tx $buffer[4] "ADDNODEtextField_#"` ;
				
				$tf = `textField -pht "rx" -bgc 0.2 0.2 0 -tx $buffer[5] "ADDNODEtextField_#"` ;
				$tf = `textField -pht "ry" -bgc 0.2 0.2 0 -tx $buffer[6] "ADDNODEtextField_#"` ;
				$tf = `textField -pht "rz" -bgc 0.2 0.2 0 -tx $buffer[7] "ADDNODEtextField_#"` ;
				
				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[8] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Root" -c ("textField -e -tx \"Root_FK_ctrl\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head_FK_ctrl\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2_FK_ctrl\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL_FK_ctrl\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);

				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[9] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "CLAMP":
			case "//CLAMP":
				$win = `rowColumnLayout -nc 19 -cw 1 20 -cw 2 20 -cw 3 70
					-cw 4 150 -cw 5 150 -cw 6 150
					-cw 7 40 -cw 8 40 -cw 9 40
					-cw 10 40 -cw 11 40 -cw 12 40
					-cw 13 50 -cw 14 50 -cw 15 50
					-cw 16 50
					-cw 17 50 -cw 18 50 -cw 19 50 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "CLAMP")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+" CLAMP\n") ;
				yjp_RigSetUpTableCreateButton "CLAMP" $win $num;
				$num++;
				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[2]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[3]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "minX" -bgc 0 0 0 -tx $buffer[4] ` ;
				$tf = `textField -pht "minY" -bgc 0 0 0 -tx $buffer[5] ` ;
				$tf = `textField -pht "minZ" -bgc 0 0 0 -tx $buffer[6] ` ;

				$tf = `textField -pht "maxX" -bgc 0.2 0.2 0 -tx $buffer[7] ` ;
				$tf = `textField -pht "maxY" -bgc 0.2 0.2 0 -tx $buffer[8] ` ;
				$tf = `textField -pht "maxZ" -bgc 0.2 0.2 0 -tx $buffer[9] ` ;

				$tf = `textField -pht "magX" -bgc 0 0 0 -tx $buffer[10] ` ;
				$tf = `textField -pht "magY" -bgc 0 0 0 -tx $buffer[11] ` ;
				$tf = `textField -pht "magZ" -bgc 0 0 0 -tx $buffer[12] ` ;

				$tf = `textField -pht "Dir" -bgc 0.2 0.2 0 -tx $buffer[13] ` ;

				$tf = `textField -pht "tx" -bgc 0 0 0 -tx $buffer[14] ` ;
				$tf = `textField -pht "ty" -bgc 0 0 0 -tx $buffer[15] ` ;
				$tf = `textField -pht "tz" -bgc 0 0 0 -tx $buffer[16] ` ;

				setParent ..;
				break;
			case "IK":
			case "//IK":
			case "aIK":
			case "//aIK":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 170 -cw 8 170 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "IK"||$buffer[0] == "aIK")$val=1;
				string $buttonName = `substitute "//" $buffer[0] ""`;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton $buttonName $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "End joint" -bgc $exist 0 0 -tx $buffer[2]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "pv node" -bgc $exist 0 0 -tx $buffer[3]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[4])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent node" -bgc $exist 0 0 -tx $buffer[4]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "6";menuItem -label "13";menuItem -label "17";
					optionMenu -e -v $buffer[4] $opA;
			*/
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[5] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;

			case "Parent":
			case "//Parent":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Parent")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Parent" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent ctrl" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "chaild ctrl" -bgc $exist 0 0 -tx $buffer[2]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				setParent ..;
				break;
			case "SIK":
			case "//SIK":
			//SIK,mant_R_ROOT,mant_R_END,2,1,1,0,ID00_set
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 40 -cw 8 40 -cw 9 40 -cw 10 150  -cw 11 150 -cw 12 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "SIK" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "end joint" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";menuItem -label "6";
					optionMenu -e -v $buffer[3] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[4] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "py";menuItem -label "ny";menuItem -label "nz";menuItem -label "pz";menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[5] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[6] $opA;
			
				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[7]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "up node" -bgc $exist 0 0 -tx $buffer[7]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head_FK_ctrl\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2_FK_ctrl\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR_FK_ctrl\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL_FK_ctrl\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[8])`){
					$jointarray[0] = ($RefNameSpace + $buffer[8]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent joint" -bgc $exist 0 0 -tx $buffer[8] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);
			
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[9] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "SIKFK":
			case "//SIKFK":
			//SIK,mant_R_ROOT,mant_R_END,2,1,1,0,ID00_set
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 40 -cw 8 40 -cw 9 40 -cw 10 150  -cw 11 150 -cw 12 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIKFK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "SIKFK" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "end joint" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[3] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[4] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "py";menuItem -label "ny";menuItem -label "nz";menuItem -label "pz";menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[5] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[6] $opA;
			
				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[7]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "up node" -bgc $exist 0 0 -tx $buffer[7]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);

				if(`objExists ($RefNameSpace + $buffer[8])`){
					$jointarray[0] = ($RefNameSpace + $buffer[8]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent joint" -bgc $exist 0 0 -tx $buffer[8] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "Head" -c ("textField -e -tx \"Head\"" + $tf);
						menuItem -label "Spine2" -c ("textField -e -tx \"Spine2\"" + $tf);
						menuItem -label "Pelvis" -c ("textField -e -tx \"Pelvis\"" + $tf);
						menuItem -label "ClavicleR" -c ("textField -e -tx \"ClavicleR\"" + $tf);
						menuItem -label "ClavicleL" -c ("textField -e -tx \"ClavicleL\"" + $tf);
						menuItem -label "ShoulderR" -c ("textField -e -tx \"ShoulderR\"" + $tf);
						menuItem -label "ShoulderL" -c ("textField -e -tx \"ShoulderL\"" + $tf);	
						menuItem -label "ElbowR" -c ("textField -e -tx \"ElbowR\"" + $tf);
						menuItem -label "ElbowL" -c ("textField -e -tx \"ElbowL\"" + $tf);
						menuItem -label "HandR" -c ("textField -e -tx \"HandR\"" + $tf);
						menuItem -label "HandL" -c ("textField -e -tx \"HandL\"" + $tf);
						menuItem -label "HipR" -c ("textField -e -tx \"HipR\"" + $tf);
						menuItem -label "HipL" -c ("textField -e -tx \"HipL\"" + $tf);	
						menuItem -label "KneeR" -c ("textField -e -tx \"KneeR\"" + $tf);
						menuItem -label "KneeL" -c ("textField -e -tx \"KneeL\"" + $tf);
						menuItem -label "FootR" -c ("textField -e -tx \"FootR\"" + $tf);
						menuItem -label "FootL" -c ("textField -e -tx \"FootL\"" + $tf);

				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[9] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "SIK2":
			case "//SIK2":
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 150  -cw 8 150 -cw 9 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIK2")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "SIK2" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "end joint" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[3] $opA;
			
				if(`objExists ($RefNameSpace + $buffer[4])`){
					$jointarray[0] = ($RefNameSpace + $buffer[4]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "up node" -bgc $exist 0 0 -tx $buffer[4]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[5])`){
					$jointarray[0] = ($RefNameSpace + $buffer[5]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent joint" -bgc $exist 0 0 -tx $buffer[5] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[6] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "RIB":
			case "//RIB":
			//RIB,1,ID00_set,parent,jointjointjoint
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 40 -cw 5 150 -cw 6 150 -cw 7 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "RIB")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				yjp_RigSetUpTableCreateButton "RIB" $win $num;
				$num++;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[1] $opA;
			
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
			
				$tf = `textField -pht "parent" -bgc $exist 0 0 -tx $buffer[3]  -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				for($m=4;$m<size($buffer);$m++)
				{
					$target += ($buffer[$m]+",");
				}
				
				textField -pht "joint,joint,joint..." -bgc $exist 0 0 -tx $target -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "SWING":
			case "//SWING":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 150 -cw 7 150 -cw 8 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SWING")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "SWING" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[1] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){
					$jointarray[1] = ($RefNameSpace + $buffer[3]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -bgc $exist 0 0 -tx $buffer[3] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[4])`){
					$jointarray[1] = ($RefNameSpace + $buffer[4]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -bgc $exist 0 0 -tx $buffer[4] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[5] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "iIK":
			case "//iIK":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 170 -cw 8 170 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "iIK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "iIK" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "End joint" -bgc $exist 0 0 -tx $buffer[2]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "pv node" -bgc $exist 0 0 -tx $buffer[3]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[4])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent node" -bgc $exist 0 0 -tx $buffer[4]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				//$opA = `optionMenu  -h 25 `;
				//	menuItem -label "0";menuItem -label "6";menuItem -label "13";menuItem -label "17";
				//	optionMenu -e -v $buffer[4] $opA;
			
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[5] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				//$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				//$jointList = stringArrayCatenate($jointList, $jointarray);
			
				setParent ..;
				break;
			/*
			case "SourceParent":
			case "SourceP":
			case "//SourceParent":
			case "//SourceP":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -cw 5 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SourceP")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "SourceParent" $win $num;
				$num++;
				//textField -bgc $exist 0 0 -tx $buffer[1];
				if(`objExists ($RefNameSpace + $buffer[1])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "joint" -bgc $exist 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				$tf = `textField -pht "joint or none"  -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				if($buffer[2] != "")
				{
					if(`objExists $buffer[2]`){$exist = 0;}else{$exist = 0.3;}
					textField -e -bgc $exist 0 0 -tx $buffer[2] $tf;
				}
				setParent ..;
				break;
			
			case "SourcePsdk":
			case "//SourcePsdk":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -cw 5 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SourcePsdk")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "SourcePsdk" $win $num;
				$num++;
				//textField -bgc $exist 0 0 -tx $buffer[1];
				
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "joint" -bgc $exist 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			*/
			case "Multi":
			case "//Multi":
			//Multi,1,1,ID00_set,weapon_a,Grip_R,wpG_a
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 40 -cw 5 40 -cw 6 150 -cw 7 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Multi")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				yjp_RigSetUpTableCreateButton "Multi" $win $num;
				$num++;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";
					optionMenu -e -v $buffer[1] $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[2] $opA;
				
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[3]  -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				string $MultTarget[];
				for($m=4;$m<size($buffer);$m++)
				{
					if(!`stringArrayContains $buffer[$m] $MultTarget`){
						$MultTarget[size($MultTarget)] = $buffer[$m];
					}
				}
				$target = stringArrayToString($MultTarget, ",");
				textField -pht "ctrl,ctrl,ctrl..." -bgc $exist 0 0 -tx $target -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "Bridge":
			case "//Bridge":
			//Bridge,name,0.5,0.5,node,node,node,node,joint,joint
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 100 -cw 5 30 -cw 6 30 -cw 7 400 -cw 8 400-p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Bridge")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				yjp_RigSetUpTableCreateButton "Bridge" $win $num;
				$num++;
				
				$tf = `textField -pht "name" -bgc $exist 0 0 -tx $buffer[1]  -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				$tf = `textField -pht "U" -bgc 0 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				$tf = `textField -pht "V" -bgc 0 0 0 -tx $buffer[3] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				string $pos,$joint;
				for($m=4;$m<`size$buffer`;$m++)
				{
					if(`gmatch $buffer[$m] "*!*"`)
					{
						 $joint += `substitute "!" $buffer[$m] ""`+",";
					}
					else
					{
						$pos += $buffer[$m]+",";
					}
				}
				textField -pht "node or vtx" -bgc $exist 0 0 -tx $pos -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
			
				textField -pht "joint,joint,joint..." -bgc $exist 0 0 -tx $joint -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "eCurve":
			case "//eCurve":
			//Bridge,name,0.5,0.5,node,node,node,node,joint,joint
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 100 -cw 5 100 -cw 6 400-p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "eCurve")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				yjp_RigSetUpTableCreateButton "eCurve" $win $num;
				$num++;
				
				$tf = `textField -pht "node" -bgc $exist 0 0 -tx $buffer[1]  -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				$tf = `textField -pht "name" -bgc 0 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				string $edgindex;
				for($m=3;$m<`size$buffer`;$m++)
				{
					$edgindex +=  $buffer[$m] +",";
				}
				textField -pht "edgindex,edgindex,..." -bgc $exist 0 0 -tx $edgindex -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
			
				setParent ..;
				break;
				//
			case "AngleRe":
			case "//AngleRe":
				$win = `rowColumnLayout -nc 13 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 40 -cw 8 40 -cw 9 150 -cw 10 120 -cw 11 40 -cw 12 40 -cw 13 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "AngleRe")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "AngleRe" $win $num;
				$num++;
				//root joint cw 4
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "root joint" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				//Angle joint cw 5
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Angle joint" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				//axis cw 6
				$opA = `optionMenu  -h 25 `;
					menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
					optionMenu -e -v $buffer[3] $opA;
				
				//axis cw 7
				$opA = `optionMenu  -h 25 `;
					menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
					optionMenu -e -v $buffer[4] $opA;
				
				//val cw 8
				$tf = `textField -pht "90" -bgc $exist 0 0 -tx $buffer[5] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//React cw 9
				$tf = `textField -pht "React SDK" -bgc $exist 0 0 -tx $buffer[6]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				//attr cw 10
				$tf = `textField -pht "attr" -bgc $exist 0 0 -tx $buffer[7] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//attrValmin cw 11
				$tf = `textField -pht "float" -bgc $exist 0 0 -tx $buffer[8] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				string $AttrADDctrl = $buffer[9];
				float $attrValmax = 0;

				if(!`gmatch $buffer[9] "?[a-z]*"`)
				{
					$attrValmax = $buffer[9];
					$AttrADDctrl = $buffer[10];
				}
				//attrValmax cw 12
				$tf = `textField -pht "float" -bgc $exist 0 0 -tx $attrValmax ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
				
				//AttrADDctrl cw 13
				if(`objExists ($RefNameSpace + $AttrADDctrl)`){
					$jointarray[0] = ($RefNameSpace + $AttrADDctrl);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $AttrADDctrl ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "Bend":
			case "//Bend":
				//$Driven,string $Driver,string $ctrl,float $bendVal ,float $rollVal float $axisvalx)
				$win = `rowColumnLayout -nc 9 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 56 -cw 8 56 -cw 9 56 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "Bend")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+" Bend\n") ;
				yjp_RigSetUpTableCreateButton "Bend" $win $num;
				$num++;
				$tf = `textField -pht "Driven" -bgc 0 0 0 -tx $buffer[1] "BendEtextField_#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpNodeCreate " + $tf);		
				$tf = `textField -pht "Driver" -bgc 0 0 0 -tx $buffer[2] "BendEtextField_#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpNodeCreate " + $tf);
				$tf = `textField -pht "ctrl" -bgc 0 0 0 -tx $buffer[3] "BendEtextField_#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpNodeCreate " + $tf);
				$tf = `textField -pht "bendVal" -bgc $exist 0 0 -tx $buffer[4] "BendEtextField_#"` ;
				$tf = `textField -pht "rollVal" -bgc $exist 0 0 -tx $buffer[5] "BendEtextField_#"` ;
				$tf = `textField -pht "axisval" -bgc $exist 0 0 -tx $buffer[6] "BendEtextField_#"` ;
				setParent ..;
				break;
			case "Dist":
			case "//Dist":
				$win = `rowColumnLayout -nc 10 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 150 -cw 8 100 -cw 9 40 -cw 10 150  -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Dist")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Dist" $win $num;
				$num++;
				//TargetA cw 4
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "TargetA" -bgc $exist 0 0 -tx $buffer[1]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				//TargetB cw 5
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "TargetB" -bgc $exist 0 0 -tx $buffer[2] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				//maxLength cw 6
				$tf = `textField -pht "maxLength" -bgc $exist 0 0 -tx $buffer[3]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//React cw 7
				if(`objExists ($RefNameSpace + $buffer[6])`){
					$jointarray[0] = ($RefNameSpace + $buffer[4]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "React" -bgc 0 0 0 -tx $buffer[4] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
				
				//attr cw 8
				$tf = `textField -pht "attr" -bgc $exist 0 0 -tx $buffer[5] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//val cw 9
				$tf = `textField -pht "val" -bgc $exist 0 0 -tx $buffer[6]` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//ctrl cw 10
				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[7]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[7] ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "Swiche":
			case "//Swiche":
			//Swiche,ID00_set,face_upper,eye00,eye01,eye02,eye03,eye04,eye05,eye06,eye07
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 500 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Swiche")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Swiche" $win $num;
				$num++;
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				textField -pht "Add Attr Name" -bgc 0 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				for($m=3;$m<size($buffer);$m++)
				{
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "UnityVis":
			case "//UnityVis":
			//UnityVis,outNoad,mesh,mesh,mesh,mesh,mesh,mesh
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 700 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "UnityVis")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "UnityVis" $win $num;
				$num++;
				textField -pht "outputNode" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				for($m=2;$m<size($buffer);$m++)
				{
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "AIM":
			case "//AIM":
			////yjp_AimRig(,string $CtrlNode,string $BaseNode,string $AimDir,string $UpDir,string $charaName,string $TergetNode[]);
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 40 -cw 8 40 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "AIM")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "AIM" $win $num;
				$num++;
				string $UpParentNoad = $buffer[2];
				string $TargetParentNoad = $buffer[3];
				string $AIMDir = $buffer[4];
				string $AIMUpDir = $buffer[5];
				//string $AIMcharaName = $buffer[5];
				$tf = `textField -pht "ctrl" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				$tf = `textField -pht "baseNode" -bgc 0 0 0 -tx $UpParentNoad -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				$tf = `textField -pht "baseNode" -bgc 0 0 0 -tx $TargetParentNoad -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				$opA = `optionMenu  -h 25 `;
					menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
					menuItem -label "dx";menuItem -label "dy";menuItem -label "dz";menuItem -label "dxi";menuItem -label "dyi";menuItem -label "dzi";
				optionMenu -e -v $AIMDir $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
					menuItem -label "dx";menuItem -label "dy";menuItem -label "dz";menuItem -label "dxi";menuItem -label "dyi";menuItem -label "dzi";
				optionMenu -e -v $AIMUpDir $opA;
				
				//textField -pht "characterSet" -bgc 0 0 0 -tx $AIMcharaName -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				for($m=6;$m<size($buffer);$m++)
				{
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				//textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				setParent ..;
				break;
			case "Scale":
			case "//Scale":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Scale")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Scale" $win $num;
				$num++;
				$tf = `textField -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "Div":
			case "Divide":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -cw 5 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Divide")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Divide" $win $num;
				$num++;
				if(`objExists ($RefNameSpace +$buffer[1])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "joint" -bgc $exist 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace +$buffer[2])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[2] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "NoIK":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "NoIK")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "NoIK" $win $num;
				$num++;
				if(`objExists $buffer[1]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				setParent ..;
				break;

			case "IKfoot":
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 150
												-cw 7 20 -cw 8 20 -cw 9 70 -cw 10 150 -cw 11 150 -cw 12 150
												-cw 13 20 -cw 14 20 -cw 15 70 -cw 16 150 -cw 17 150 -cw 18 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "IKfoot")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "IKfoot" $win $num;
				$num++;
				if(`objExists $buffer[1]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[1]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[2]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[2]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[3]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[3]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				text -l "";text -l "";text -l "";
				
				if(`objExists $buffer[4]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[4]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[5]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[5]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[6]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[6]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				text -l "";text -l "";text -l "";
				
				if(`objExists $buffer[7]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[7]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[8]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[8]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[9]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[9]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				setParent ..;
				break;
			case "Collider":
			case "//Collider":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Collider")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				yjp_RigSetUpTableCreateButton "Collider" $win $num;
				$num++;
				textField -pht "object,object..." -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				setParent ..;
				break;
			case "MEL":
			case "//MEL":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 800 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "MEL")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ "MEL\n") ;
				yjp_RigSetUpTableCreateButton "MEL" $win $num;
				$num++;
				textField -pht "command" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				
				setParent ..;
				break;
			case "CTRL":
			case "//CTRL":
				$win = `rowColumnLayout -nc 14 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 50 -cw 7 50 -cw 8 40 -cw 9 40 -cw 10 40 -cw 11 40 -cw 12 40 -cw 13 40 -cw 14 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "CTRL")$val=1;
				checkBox -l "" -v $val -cc ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0");
				//print ($num+ $buffer[1]+"CTRL\n") ;
				yjp_RigSetUpTableCreateButton "CTRL" $win $num;
				$num++;
				$tf = `textField -pht "ctrl" -bgc 0 0 0 -tx $buffer[1] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				$opA = `optionMenu  -h 25 `;
					menuItem -label "Box";
					menuItem -label "Square";
					menuItem -label "Square2";
					menuItem -label "Circle";
					menuItem -label "Circle2";
					menuItem -label "Cross";
					menuItem -label "Sphere";
					menuItem -label "Pyramid";
					menuItem -label "Rhombus";
					menuItem -label "BoxCenter";
					menuItem -label "FootBox";
				
				optionMenu -e -v $buffer[2] $opA;
				
				$tf = `textField -pht "size" -bgc 0 0 0 -tx $buffer[3] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				$tf = `textField -pht "size" -bgc 0 0 0 -tx $buffer[4] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;

				$tf = `textField -pht "tx" -bgc 0 0 0 -tx $buffer[5] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				$tf = `textField -pht "ty" -bgc 0 0 0 -tx $buffer[6] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				$tf = `textField -pht "tz" -bgc 0 0 0 -tx $buffer[7] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;

				$tf = `textField -pht "rx" -bgc 0 0 0 -tx $buffer[8] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				$tf = `textField -pht "ry" -bgc 0 0 0 -tx $buffer[9] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				$tf = `textField -pht "rz" -bgc 0 0 0 -tx $buffer[10] -ec ("if\(\`checkBox -q -v RigEditAutoSavecheckBox\`\)yjp_RigSetUpTableSave 0")`;
				
				int $color = 6;
				if($buffer[11] !="")$color = int($buffer[11])+1;
				colorIndexSliderGrp -cw2 20 130 -min 1 -max 31 -value $color ;
				//-cw 1 20-cw 2 150
				setParent ..;
				break;
		}
		//print ($num+ "\n") ;
	}
	

	//print ("//////Joints not set up//////" + "\n") ;
	string $RestJoint[] = stringArrayRemove ($jointList, $joint);
	$RestJoint = stringArrayRemoveDuplicates($RestJoint);
	//for($prin in $RestJoint){print ($prin+ "\n");}
	select $RestJoint;
	clear $jointarray;
	
	
}
//////////////////////////////////////////////////////////////////////////////////////////////
//Save edits to file
global proc yjp_RigSetUpTableSave(int $as)
{
	//yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
	//global string $RigSetUpStringLine[];
	//save
	string $comline[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $charaName[] = `textScrollList -q -si RigPatternScrollList`;
	//
	string $localpath = `workspace -q -rd`;
	$localpath = $localpath + "setup";
	
	if(!`filetest -d $localpath`)sysFile -md $localpath;

	string $filePassName = `window -q -t  yjp_RigSetUpListEditWindow`;
	$filePassName = `substitute "RigSetUpTableEdit   " $filePassName ""`;
	$charaName[0] = `basename $filePassName ".rigp"`;

	if($as)
	{
		string $bakehistory = `promptDialog
			-title "Save As"
			-message "New Name:"
			-button "Save As" -button "Cancel"
			-defaultButton "Save As" -cancelButton "Cancel"
			-dismissString "Cancel"`;
		if($bakehistory == "Save As")
		{
			$charaName[0] = `promptDialog -query -text`;
			$filePassName = $localpath +"/" + $charaName[0] + ".rigp";
		}
		else if($bakehistory == "Cancel")
		{
			return;
		}
	}

	$file_path = dirname($filePassName);

	//$filePassName = $file_path + "/" + $charaName[0] + ".rigp";
	string $daya =`date -sd`;
	$daya = `substitute "/" $daya ""`;
	string $time =`date -st`;
	$daya = "_" + $daya + `substitute ":" $time ""`;
	string $backupfilePassName = $file_path + "/backup/" + $charaName[0] + $daya+".rigp";
	//

	if(!`filetest -f $filePassName`)
	{
		$PFile =`fopen ($filePassName)`;
		fclose $PFile;
	}
	if(!`filetest -w $filePassName`)error"ファイルが書き込み出来ない状態です";
	if(!`filetest -d ($file_path + "/backup/")`)
	{
		sysFile -md ($file_path + "/backup/");
	}
	int $n;
	string  $slash;
	string $rowl[],$cm,$script;
	$script += ("//\n");
	for($n=0;$n<size($comline);$n++)
	{
		//print ("comline "+$comline[$n] +"\n");
		$rowl = `rowColumnLayout -q -ca $comline[$n]`;
		//print ("$rowl " + $rowl[2] +"\n");
		$cm =`button -q -l $rowl[2]`;
		if($cm !="comment" && $cm !="ID" && $cm !="")
		{
			if(`checkBox -q -v $rowl[1]`)
			{$slash = "";}
			else
			{$slash = "//";}
		}
		//print ($cm +"\n");
		switch($cm)
		{
			case "comment":
				$script += ("//" + `textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "ID":
				$script += ($slash + "ID,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "CSET":
				$script += ($slash + "CSET," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "\n" );
				break;
			
			case "CENTER":
				$script += ($slash + "CENTER," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "\n" );
				break;
			
			case "FK":
				$script += ($slash + "FK," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;

			case "EFK":
				$script += ($slash + "EFK," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;

			case "ADDNODE":
				$script += ($slash + "ADDNODE," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ "," );
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]`+ "," );
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]`+ "\n");
				break;

			case "CLAMP":
				$script += ($slash + "CLAMP," );
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");

				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");

				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]`+ ",");

				$script += (`textField -q -text $rowl[12]`+ ",");
				$script += (`textField -q -text $rowl[13]`+ ",");
				$script += (`textField -q -text $rowl[14]`+ ",");

				$script += (`textField -q -text $rowl[15]`+ "," );

				$script += (`textField -q -text $rowl[16]`+ ",");
				$script += (`textField -q -text $rowl[17]`+ ",");
				$script += (`textField -q -text $rowl[18]`+ "\n");
				break;

			case "IK":
				$script += ($slash + "IK,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`textField -q -text $rowl[7]` + "\n");
				break;
			case "aIK":
				$script += ($slash + "aIK,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`textField -q -text $rowl[7]` + "\n");
				break;			
			case "iIK":
				$script += ($slash + "iIK,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`textField -q -text $rowl[7]` + "\n");
				break;
			
			case "Parent":
				$script += ($slash + "Parent,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "IKfoot":
				//
				$script += ($slash + "IKfoot,");
				$script += (`textField -q -text $rowl[2]`+ ",");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`floatField -q -v $rowl[5]`+ "\n");
				break;
			
			case "SourceP":
			case "SourceParent":
				$script += ($slash + "SourceP,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "SIK":
				//
				$script += ($slash + "SIK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + ",");
				$script += (`optionMenu -q -v $rowl[8]` + ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]` + "\n");
				break;
			case "SIKFK":
				//
				$script += ($slash + "SIKFK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + ",");
				$script += (`optionMenu -q -v $rowl[8]` + ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]` + "\n");
				break;
			case "SIK2":
				//
				$script += ($slash + "SIK2,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]` + "\n");
				break;
			case "RIB":
				//
				$script += ($slash + "RIB,");
				$script += (`optionMenu -q -v $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;
			
			case "Multi":
				//
				$script += ($slash + "Multi,");
				$script += (`optionMenu -q -v $rowl[3]` + ",");
				$script += (`optionMenu -q -v $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;
			
			case "Swiche":
				//
				$script += ($slash + "Swiche,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ "\n");
				break;
			
			case "UnityVis":
				//
				$script += ($slash + "UnityVis,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;

			case "Bend":
				$script += ($slash + "Bend," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ "," );
				$script += (`textField -q -text $rowl[8]`+ "\n");
				break;			
			case "AIM":
				//
				$script += ($slash + "AIM,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + "\n");
				break;
			
			case "Scale":
				//
				$script += ($slash + "Scale,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "SWING":
				//yjp_rig_SwingJointFKsetup(string $startjoint ,string $endjoint,string $topparent,string $endparent, string $charaName)
				$script += ($slash + "SWING,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ "\n");
				
				break;

			case "Div":
			case "Divide":
				//
				$script += ($slash + "Divide,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "NoIK":
				$script += ($slash + "NoIK,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "ADDIK":
				$script += ($slash + "ADDIK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`floatField -q -v $rowl[6]`+ "\n");
				break;
			
			case "SourcePsdk":
				$script += ($slash + "SourcePsdk,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "Collider":
				$script += ($slash + "Collider," + `textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "MEL":
				$script += ($slash + "MEL," + `textField -q -text $rowl[3]`+ "\n");
				break;
			case "CTRL":
				//
				int $co = `colorIndexSliderGrp -q -v $rowl[13]`-1; 
				//print( $co+ "\n");
				
				$script += ($slash + "CTRL,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`optionMenu -q -v $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");

				$script += (`textField -q -text $rowl[7]`+ ",");				
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]`+ ",");

				$script += (`textField -q -text $rowl[10]`+ ",");				
				$script += (`textField -q -text $rowl[11]`+ ",");
				$script += (`textField -q -text $rowl[12]`+ ",");
				$script += ($co+ "\n");
				break;
			case "Bridge":
				//
				$script += ($slash + "Bridge,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				
				$text = (`textField -q -text $rowl[6]`);
				string $array[] = stringToStringArray($text, ",");
				$script += stringArrayToString( $array, "," );
				$script += ",";
			
				$text = (`textField -q -text $rowl[7]`);
				$array = stringToStringArray($text, ",");
				stringArrayAddPrefix( $array, "!" );
				$script += stringArrayToString( $array, "," );
				$script += ("\n");
			break;
			case "eCurve":
				//
				$script += ($slash + "eCurve,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				
				$text = (`textField -q -text $rowl[5]`);
				$array = stringToStringArray($text, ",");
				$script += stringArrayToString( $array, "," );
				$script += ",";
				$script += ("\n");
			break;
			case "AngleRe":
				//
				$script += ($slash + "AngleRe,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]`+ ",");
				$script += (`textField -q -text $rowl[12]` + "\n");
				break;
			case "Dist":
				//
				$script += ($slash + "Dist,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]` + "\n");
				break;
		}
	}
	print ($script +"\n");
	
    $PFile =`fopen ($filePassName) "w"`;
    fprint ($PFile, $script);
    fclose ($PFile);
	print ("Save " + $filePassName + "\n") ;

    $PFile =`fopen ($backupfilePassName) "w"`;
    fprint ($PFile, $script);
    fclose ($PFile);
	print ("backupSave " + $backupfilePassName + "\n") ;
	
	yjp_RigSetUpTableLoad;
}
//////////////////////////////////////////////////////////////////////////////////////////////

global proc yjp_RigSetUpDeleteCommand(string $rl,int $num)
{

	if(`getModifiers` == 4)
	{
		deleteUI -lay $rl;
		global string $RigSetUpStringLine[];
		stringArrayRemoveAtIndex($num,$RigSetUpStringLine);
		yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
		if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////

global proc yjp_RigSetUpAddCommand(string $comd,int $num)
{
	global string $ss_RigCharaID ;
	global string $RigSetUpStringLine[];
	string $ID = $ss_RigCharaID ;
	string $IDset = $ID +"_set";
	
	string $che;
	for($che in $RigSetUpStringLine)print ($che+ "\n") ;
	print ($num + $RigSetUpStringLine[$num] + "\n") ;
	
	switch($comd)
	{
		case "comment":
			$comd = "//Comment\n";
			break;
		case "ID":
			$comd = $comd+","+$ID+ "\n";
			break;
		case "CSET":
			$comd = $comd+","+$IDset+ "\n";
			break;
		case "CENTER":
			$comd = $comd+",joint," + $IDset+ "\n";
			break;
		case "FK":
			$comd = $comd+",joint,joint,parent," + $IDset+ "\n";
			break;
		case "EFK":
			$comd = $comd+",node,2,parent," + $IDset+ "\n";
			break;
		case "ADDNODE":
			$comd = $comd+",node,0,0,0,0,0,0,parent,"+ $IDset+"\n";
			break;
		case "CLAMP":
			$comd = $comd+",ctrl,Target,Base,0,0,0,0,0,0,0,0.5,1.0,1,20,0,0\n";
			break;
		case "IK":
			$comd = $comd+",RootJoint,EndJoint,PVnode,parent," + $IDset + "\n";
			break;
		case "aIK":
			$comd = $comd+",RootJoint,EndJoint,PVnode,parent," + $IDset + "\n";
			break;
		case "iIK":
			$comd = $comd+",RootJoint,EndJoint,PVnode,parent," + $IDset + "\n";
			break;
		case "IKfoot":
			$comd = $comd+",joint,joint,joint,node,node,node,node\n";
			break;
		case "Parent":
			$comd = $comd+",joint,joint\n";
			break;
		case "SIK":
			$comd = $comd+",joint,joint,2,1,nz,0,joint,joint,"+ $IDset+"\n";
			break;
		case "SIKFK":
			$comd = $comd+",joint,joint,2,1,nz,0,joint,joint,"+ $IDset+"\n";
			break;
		case "SIK2":
			$comd = $comd+",joint,joint,0,joint,joint,"+ $IDset+"\n";
		case "RIB":
			$comd = $comd+",1,"+ $IDset +",parent,node\n";
			break;
		case "SWING":
			$comd = $comd+",joint,joint,joint,none,"+ $IDset+"\n";
			break;
		case "AIM":
			$comd = $comd+",CTRL,UPparent,TargetParent,x,y\n";
			break;
		case "ADDIK":
			$comd = $comd+",joint,joint,joint,0\n";
			break;
		case "SourceParent":
			$comd = $comd+",joint\n";
			break;
		case "SourcePsdk":
			$comd = $comd+",node,node\n";
			break;
		case "Div":
		case "Divide":
			$comd = $comd+",joint,ctrl\n";
			break;
		case "NoIK":
			$comd = $comd+",joint\n";
			break;
		case "Multi":
			$comd = $comd+",1,1,node,node\n";
			break;
		case "Swiche":
			$comd = $comd+","+$IDset+",node,node\n";
			break;
		case "UnityVis":
			$comd = $comd+",node,node\n";
			break;
		case "Scale":
			$comd = $comd+",joint\n";
			break;
		case "CONNECT":
			$comd = $comd+",node,attr,node,attr\n";
			break;
		case "Collider":
			$comd = $comd+",object,object...\n";
			break;
		case "MEL":
			$comd = $comd+",command\n";
			break;
		case "Bridge":
			$comd = $comd+",name,0.5,0.5,node,joint!\n";
			break;
		case "Bend":
			$comd = $comd+",sdk,joint,ctrl,1.0,0.0,20,\n";
			break;
		case "eCurve":
			$comd = $comd+",node,name,edgeID,\n";
			break;
		case "CTRL":
			$comd = $comd+",ctrl,Box,10,10,0,0,0,0,0,0,6\n";
			break;
		case "AngleRe":
			$comd = $comd+",Rootjoint,joint,x,x,90,React,attr,0,0,ctrl\n";
			break;
		case "Dist":
			$comd = $comd+",TargetA,TargetB,name,React,attr,val,ctrl\n";
			break;
	}
	
	stringArrayInsertAtIndex($num,$RigSetUpStringLine,$comd);
	yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
	if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
}
//////////////////////////////////////////////////////////////////////////////////////////////
//テキストを検索する処理
global proc yjp_RigEditTextSearch()
{
	string $sText = `textFieldGrp -q -tx RigEditTextSearchField`;
	if(size($sText) == 0)
	{
		yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
		return;
	}
	int$n,$f;
	
	$sText = "*" + $sText + "*";
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;
	for($n=0;$n<`size$LayoutArray`;$n++)
	{
		string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[$n]`;
		for($f=0;$f<`size$FieldArray`;$f++)
		{
			if(`gmatch $FieldArray[$f] "textField*"`)
			{
				string $tex = `textField -q -tx $FieldArray[$f]`;
				if(`gmatch $tex $sText`)
				{
					textField -e -bgc 0.0 0.5 0.0 $FieldArray[$f];
				}
				else
				{
					textField -e -bgc 0.0 0.0 0.0 $FieldArray[$f];
				}
			}
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigEditNodeSelect(string $tf)
{
	string $node = `textField -q -tx $tf`;
	
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;	
	string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[0]`;
	string $cn = `textField -q -tx $FieldArray[3]`;
	
	$node = $cn + ":" + $node;
	
	if(`objExists $node`)
	{
		select -r $node;
	}
	
}
//////////////////////////////////////////////////////////////////////////////////////////////

global proc yjp_RigSetUpNodeGet(string $tf)
{
	//ノード取得処理
	print("yjp_RigSetUpNodeGet "+ $tf + "\n");
	
	string $sel[] = `ls -sl`;
	if(size($sel)==0)return ;
	$node = `nameRoot $sel[0]`;
	textField -e -bgc 0 0 0 -tx $node $tf;
	if(`gmatch $tf "*ADDNODEtextField_*"`)
	{
		float $val[];
		$val[0] = `getAttr ($node+".tx")`;
		$val[1] = `getAttr ($node+".ty")`;
		$val[2] = `getAttr ($node+".tz")`;
		$val[3] = `getAttr ($node+".rx")`;
		$val[4] = `getAttr ($node+".ry")`;
		$val[5] = `getAttr ($node+".rz")`;

		string $UIpath[];
		tokenize $tf "ADDNODEtextField_" $UIpath;
		int $num = `tokenize $tf "|" $UIpath`;
		int $UInum = `substitute "ADDNODEtextField_" $UIpath[$num-1] ""`;
		for ($n=0; $n<6;$n++)
		{
			$UInum ++;
			$UIpath[$num-1] = "ADDNODEtextField_" + $UInum;
			$nexttf = stringArrayToString ($UIpath,"|");
			textField -e -text (`yjp_DPoint $val[$n] 0.01`) $nexttf;
		}
	}

	if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
}
global proc yjp_RigSetUpNodeCreate(string $tf)
{
	//ロケーター作成
	print("yjp_RigSetUpNodeCreate "+ $tf + "\n");
	string $locName = `textField -q -tx $tf`;

	if(!`objExists $locName`)spaceLocator -p 0 0 0 -n $locName;
	if(`gmatch $tf "*ADDNODEtextField_*"`)
	{
		string $atr[] = {"tx","ty","tz","rx","ry","rz"};
		string $UIpath[];
		tokenize $tf "ADDNODEtextField_" $UIpath;
		int $num = `tokenize $tf "|" $UIpath`;
		int $UInum = `substitute "ADDNODEtextField_" $UIpath[$num-1] ""`;
		for ($n=0; $n<6;$n++)
		{
			$UInum ++;
			$UIpath[$num-1] = "ADDNODEtextField_" + $UInum;
			$nexttf = stringArrayToString ($UIpath,"|");
			float $val = `textField -q -text $nexttf`;
			setAttr ($locName + "." + $atr[$n]) $val;
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////

global proc yjp_RigSetUpListOpen(int $type)
{
	string $filePassName;
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $charaName[] = `textScrollList -q -si RigPatternScrollList`;
	string $RefFile[] = `file -q -r`;
	string $sceneRefName = `dirname $RefFile[0]`;
	$localpath = `substitute "/scenes" $sceneRefName "/setup"`;

	if($type==1){
		$filePassName = `window -q -t  yjp_RigSetUpListEditWindow`;
		$filePassName = `substitute "RigSetUpTableEdit   " $filePassName ""`;
	}
	else if($type==2){
		string $src;
		$src = $localpath + "/" + $charaName[0] + ".rigp";
		print($src + "\n");
		$filePassName = $localpath + "/" + $charaName[0] + "EDIT.rigp";
		print($filePassName + "\n");
		
		sysFile -copy $filePassName $src; 
	}
	else{
		$filePassName = $file_path + "/" + $charaName[0] + ".rigp";
		for ($n=0; $n<size($RefFile);$n++)
		{
			$sceneRefName = `dirname $RefFile[$n]`;
			$localpath = `substitute "/scenes" $sceneRefName "/setup"`;
			if(`filetest -f ($localpath + "/" + $charaName[0] + ".rigp")`){
				$filePassName = $localpath + "/" + $charaName[0] + ".rigp";
				break;
			}
		}	
	}
	//print ($filePassName +"\n");
	filetest -f $filePassName;
	system ("load " + $filePassName);
	if(`window -ex "yjp_RigSetUpListEditWindow"`)
	{
		deleteUI "yjp_RigSetUpListEditWindow";
	}
	RigPatternListReLoad;
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableCreateButton(string $com,string $win,int $n)
{
	button  -l $com -p $win;
	if (`gmatch $win "*yjp_rigpEditcolumnLayout*"`)
	{
		popupMenu;
			//menuItem -label "insert ADDIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  ADDIK " + $n + "\"");
			menuItem -label "insert ADDNODE" -c ("evalDeferred \"yjp_RigSetUpAddCommand  ADDNODE " + $n + "\"");
			menuItem -label "insert AIM" -c ("evalDeferred \"yjp_RigSetUpAddCommand  AIM " + $n + "\"");
			menuItem -label "insert AngleRe" -c ("evalDeferred \"yjp_RigSetUpAddCommand  AngleRe " + $n + "\"");
			menuItem -label "insert Bridge" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Bridge " + $n + "\"");
			menuItem -label "insert Bend" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Bend " + $n + "\"");
			menuItem -label "insert CENTER" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CENTER " + $n + "\"");						
			menuItem -label "insert CLAMP" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CLAMP " + $n + "\"");
			menuItem -label "insert Distance" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Dist " + $n + "\"");
			menuItem -label "insert Div" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Divide " + $n + "\"");
			menuItem -label "insert comment" -c ("evalDeferred \"yjp_RigSetUpAddCommand  comment " + $n + "\"");
			menuItem -label "insert CSET" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CSET " + $n + "\"");						
			menuItem -label "insert CTRL" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CTRL " + $n + "\"");
			menuItem -label "insert EFK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  EFK " + $n + "\"");
			menuItem -label "insert FK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  FK " + $n + "\"");
			menuItem -label "insert IK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IK " + $n + "\"");
			menuItem -label "insert aIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  aIK " + $n + "\"");
			menuItem -label "insert iIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  iIK " + $n + "\"");
			menuItem -label "insert MEL" -c ("evalDeferred \"yjp_RigSetUpAddCommand  MEL " + $n + "\"");			
			menuItem -label "insert Multi" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Multi " + $n + "\"");
			menuItem -label "insert Parent" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Parent " + $n + "\"");
			menuItem -label "insert eCurve" -c ("evalDeferred \"yjp_RigSetUpAddCommand  eCurve " + $n + "\"");
			//menuItem -label "insert IKfoot" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IKfoot " + $n + "\"");
			menuItem -label "insert RIB" -c ("evalDeferred \"yjp_RigSetUpAddCommand  RIB " + $n + "\"");
			menuItem -label "insert Scale" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Scale " + $n + "\"");			
			menuItem -label "insert SIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIK " + $n + "\"");
			menuItem -label "insert SIKFK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIKFK " + $n + "\"");
			//menuItem -label "insert SIK2" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIK2 " + $n + "\"");
			menuItem -label "insert Swiche" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Swiche " + $n + "\"");
			menuItem -label "insert UnityVis" -c ("evalDeferred \"yjp_RigSetUpAddCommand  UnityVis " + $n + "\"");

			//menuItem -label "insert Collider" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Collider " + $n + "\"");
			//menuItem -label "insert SWING" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SWING " + $n + "\"");
			//menuItem -label "insert NoIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  NoIK " + $n + "\"");
	}
}

//////////////////////////////////////////////////////////////////////////////////////////////
global proc RigSetUpManual()
{
	string $path = `yjp_MELpath "RigSetUp"`;
	system("load " +$path + "/rigReadme.md");
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////Create Window
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_sRig()
{
	if(`window -q -ex RigSetUpWindow`)
	{
		deleteUI RigSetUpWindow;
	}
	int $AllJointmatch,$jointmatch,$yosJointJob;
	string $selectJoint,$jointbox,$SerchJointName;
	string $mat = "RigSet";
	string $ClipFolderPath = `optionVar -q "jptRigPatternListFolder"`;
	string $yjp_charaTab;
	string $yjp_SetUpTab;

	string $rf[] = `ls -rf`;
	if(size($rf) ==0)
	{
		warning("No reference model リファレンスモデルがありません");
		return;
	}
	string $charaID = `referenceQuery -namespace -shortName $rf[0]`;
	
	//print ("erheherh "+$charaID + "\n") ;
	window -wh 330 520 -s 1 -tlb 1 -menuBar true -t "RigSetUp 2.3" RigSetUpWindow;
	
	menu -label "Help" -pmc RigSetUpManual;
	
	string $yjp_SetUpform = `formLayout`;
	
	$yjp_charaTab = `columnLayout`;
		rowColumnLayout -nc 3 -cw 1 70 -cw 2 150 -cw 3 100;
			text -l "CharactorID ";
			textField -text $charaID -cc "Rig_CharactorIDMenu" yjp_CharactorIDText;
			optionMenu -w 90 -cc "Rig_CharactorIDChange" Rig_CharactorIDListMenu;
			/*
			text -l "CharactorID";
			textField -text ($charaID+"_set") -cc "Rig_CharactorIDMenu" yjp_CharactorIDText;
			optionMenu -w 90 -cc "Rig_CharactorIDChange" Rig_CharactorIDListMenu;
			*/
		setParent ..;

	setParent ..;	
	
	$yjp_SetUpTab = `tabLayout -en 0 -scr 1 -imw 0 -imh 0 SetUpTabLayout`;

	
	formLayout -edit
	-af $yjp_charaTab "top" 2
	-af $yjp_charaTab "left"  2
	-an $yjp_charaTab "bottom"
	-af $yjp_charaTab "right" 2
	
	-ac $yjp_SetUpTab "top" 2 $yjp_charaTab
	-af $yjp_SetUpTab "left"  2
	-af $yjp_SetUpTab "bottom" 2
	-af $yjp_SetUpTab "right" 2
	$yjp_SetUpform;
	
	//string $scrollLayout = `scrollLayout -horizontalScrollBarThickness 16 -verticalScrollBarThickness   16`;
	
		//frameLayout -label "RigTool" -labelAlign "top" -cll 1 -cl 0 RigToolframeLayout ;
	//-ec "GUIrig_frameLayout" -cc "GUIrig_frameLayout"
	$AutoSetUpTab = `formLayout`;
	
	string $AutoSetUpButton = `columnLayout `;
			rowColumnLayout -nc 3 -cw 1 100 -cw 2 90 -cw 3 90;
				button -h 25 -w 100 -l "rigp_FileReLoad" -c "RigPatternListReLoad" ;
				button -h 25 -w 100 -l "createFile" -c "createRigPatternFile" ;
				button -h 25 -w 100 -l "SetUp" -c "doAutoRigSetUp"  ;
				//button -h 25 -w 100 -bgc 0.3 0.4 0.3 -l "IKFKsetBody"  -c "Meda_BodyRigSetUP;Meda_ArmRigSetUp R;Meda_ArmRigSetUp L";
				//button -h 25 -w 100 -bgc 0.3 0.4 0.3 -l "OneSkinRigSet"  -c "Meda_RigSetUP";
			setParent ..;
			rowColumnLayout -nc 2 -cw 1 270 -cw 2 23;
				text "rigpFile folder";
				text "";
				textField RigPatternListFolderField;
					popupMenu;
						menuItem -label "FolderOpen" -c ("system (\"load " + $ClipFolderPath + "\");");
				symbolButton -i "navButtonBrowse.xpm" -c ("yjp_DirectoryDialogOption RigPatternListFolderField jptRigPatternListFolder 2;RigPatternListReLoad");
			setParent ..;
		setParent ..;
	string $scl = `textScrollList -w 200 -numberOfRows 18 -allowMultiSelection 0 -showIndexedItem 18  -dcc yjp_RigSetUpListEdit RigPatternScrollList`;
					popupMenu;
					menuItem -label "OpenFile" -c ("yjp_RigSetUpListOpen 0");
					menuItem -label "CopyFile" -c ("yjp_RigSetUpListOpen 2");
		formLayout -edit
	    -af $AutoSetUpButton "top" 2
	    -ac $scl "top"   2 $AutoSetUpButton
		-af $scl "right" 2
		-af $scl "left" 2
	    -af $scl "bottom" 2
		$AutoSetUpTab;
	setParent ..;
	
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	/*
	$ModuleTab = `columnLayout -adjustableColumn 0`;
	//
	//frameLayout -w 300 -label "GroundCTRL Create" -labelAlign "top" -bv 1 -cll 1 -cl 1 ;
	//	text -l "選択したノードの位置にグランドコントローラを作ります" -al "left";
	//	text -l "選択したノードを下のフィールドに入力。右クリックでGet" -al "left";
	//	textFieldGrp -h 20 -w 200 -cw2 50 240 -l "PosNode" GroundPosField;
	//		popupMenu;
	//			menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] GroundPosField;");
	//			menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" GroundPosField;");
	//	
	//	button -en 1 -h 25 -w 100 -l "GroundCTRL Create"  -c "doyjp_rig_GroundCTRL" -bgc 0.4 0.7 0.0 GroundCTRLCreateButton;
	//	
	setParent ..;
	//
	frameLayout -w 300 -label "Center Create" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4 ;
		text -l "選択したノードの位置にセンターコントローラを作ります" -al "left";
		text -l "選択したノードを下のフィールドに入力。右クリックでGet" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "PosNode" PosNodeField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] PosNodeField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" PosNodeField;");
		
		button -en 1 -h 25 -w 100 -l "Center Create"  -c "doyjp_RigCenterCtrlCreate" -bgc 0.4 0.7 0.0 CenterCreateButton;
		
	setParent ..;
	
	frameLayout -w 300 -label "FK SetUp" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4 ;
		text -l "RootJointからEndJointまでにFKが連続でセットアップされます" -al "left";
		text -l "RootJointだけ入力すると１つだけFKがセットアップされます" -al "left";
			textFieldGrp -h 20 -w 200 -cw2 50 240 -l "RootJoint" FKsetUpRootField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] FKsetUpRootField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" FKsetUpRootField;");
			textFieldGrp -h 20 -w 200 -cw2 50 240 -l "EndJoint" FKsetUpEndField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] FKsetUpEndField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" FKsetUpEndField;");
		button -en 1 -h 25 -w 100 -l "FK Control Create"  -c "YOS_FKControls" -bgc 0.4 0.7 0.0 ;
		
	setParent ..;
	
	frameLayout -w 300 -label "IK FK SetUp" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4 ;
		text -l "RootJointからEndJointまでにIKFKがセットアップされます" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "RootJoint" IK_FK_setUpRootField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] IK_FK_setUpRootField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" IK_FK_setUpRootField;");
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "EndJoint" IK_FK_setUpEndField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] IK_FK_setUpEndField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" IK_FK_setUpEndField;");
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "PVlocator" IK_FK_setUpPvField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] IK_FK_setUpPvField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" IK_FK_setUpPvField;");
		text -l "逆間接の場合はチェックオン"-al "left";
		checkBox -label "ReverseKnee" -v 0 ReverseKneeCheckBox;
		button -en 1 -h 25 -w 100 -l "IK FK Control Create"  -c "YOS_IKFKControls" -bgc 0.4 0.7 0.0 ;
		
	setParent ..;
	
	frameLayout -w 300 -label "IK Foot SetUp" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4 ;
		text -l "リバースフットとIKFKがセットアップされます" -al "left";
		textFieldGrp -h 20 -cw2 50 240 -l "RootJoint" yosIKFootStartText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] yosIKFootStartText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" yosIKFootStartText;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "EndJoint" yosIKFootEndText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] yosIKFootEndText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" yosIKFootEndText;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "PVlocator" yosIKFootPVlocatorText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] yosIKFootPVlocatorText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" yosIKFootPVlocatorText;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "Heel" RF_HeelNodeText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] RF_HeelNodeText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" RF_HeelNodeText;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "BankIn" RF_BankInNodeText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] RF_BankInNodeText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" IK_FK_seRF_BankInNodeTexttUpPvField;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "BankOut" RF_BankOutNodeText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] RF_BankOutNodeText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" RF_BankOutNodeText;");
		
		textFieldGrp -h 20 -cw2 50 240 -l "Swivel" RF_SwivelNodeText;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] RF_SwivelNodeText;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" RF_SwivelNodeText;");
		button -en 1 -h 25 -w 98 -l "IK Foot SetUp"  -c "YOS_IKFKfootControls;" -bgc 0.4 0.7 0.0 ;
	setParent ..;
	
	frameLayout -w 300 -label "Ctrl Parent" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		text -l "コントローラをペアレントします"-al "left";
		text -l "ペアレントできない場合はコンストレインします"-al "left";
			textFieldGrp -h 20 -w 200 -cw2 80 210 -l "Parent Ctrl" Ctrl_ParentField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] Ctrl_ParentField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" Ctrl_ParentField;");
			textFieldGrp -h 20 -w 200 -cw2 80 210 -l "Chaild Ctrl" Ctrl_ChaildField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] Ctrl_ChaildField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" Ctrl_ChaildField;");
			
			button -en 1 -h 25 -w 100 -l "Control Parent"  -c "YOS_ControlParent" -bgc 0.4 0.7 0.0 ;
		
	setParent ..;
	frameLayout -w 300 -label "Spline Controls" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
			textFieldGrp -h 20 -w 200 -cw2 50 240 -l "RootJoint" SplineRootJointField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] SplineRootJointField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" SplineRootJointField;");
			textFieldGrp -h 20 -w 200 -cw2 50 240 -l "EndJoint" SplineEndJointField;
				popupMenu;
					menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] SplineEndJointField;");
					menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" SplineEndJointField;");
			intSliderGrp -cw 1 40 -cw 2 40 -cw 3 40 -label "Division" -field true -min 1 -max 4 -fmn 1 -fmx 10 -v 3  sIKsplitSlider;
		rowColumnLayout -nc 3 -cw 1 100 -cw 2 60 -cw 3 70;
			radioButtonGrp -cw 1 20 -cw 2 30 -sl 1 -numberOfRadioButtons 2 -label "Up" -labelArray2 "Y" "Z" sIKupRadioButton;
			checkBox -label "Twist" -v 1 sIKtwistCheckBox;
			checkBox -label "Stretch" -v 0 sIKStretchCheckBox;
		setParent ..;
		button -en 1 -h 25 -w 110 -l "Spline Controls"  -c "YOS_SplineControls" -bgc 0.4 0.7 0.0 -ann "" ;
	setParent ..;
	
	
	frameLayout -w 300 -label "Multi Constraint" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		
		text -l "コンストレインされるコントローラを選択し右クリックでGet" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 70 220 -l "Constraint" MConstraintCtrlField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] MConstraintCtrlField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" MConstraintCtrlField;");
		
		text -l "コンストレインターゲットノードの順に複数選択して" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 70 220 -l "Target" MConstraintTargetField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;string $tag = stringArrayToString\($sel, \"\,\"\);textFieldGrp -e -text $tag MConstraintTargetField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" MConstraintTargetField;");
		rowColumnLayout -nc 3 -cw 1 100 -cw 2 60 -cw 3 70;
			checkBox -label "translate" -v 1 MultiConstraintTCheckBox;
			checkBox -label "rotate" -v 1 MultiConstraintRCheckBox;
		setParent ..;
		button -en 1 -h 25 -w 98 -l "Multi Constraint" -c "doyjp_rig_MultiConstraint" -bgc 0.4 0.7 0.0 ;
	setParent ..;
	
	
	frameLayout -w 300 -label "Mesh Display Swiches" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		text -l "複数のメッシュを排他的に表示切替する" -al "left";
		text -l "切替UIの名称を入力" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "Name" MeshDisplaySwichesNameField;
		text -l "複数のメッシュを選択して右クリックでGet" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "Mesh" MeshDisplaySwichesField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;string $tag = stringArrayToString\($sel, \"\,\"\);textFieldGrp -e -text $tag MeshDisplaySwichesField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" MeshDisplaySwichesField;");
		button -en 1 -h 25 -w 100 -l "Mesh Display Swiches" -c "doMeshSwichesSet" -bgc 0.4 0.7 0.0 ;
	setParent ..;
	
	
	frameLayout -w 300 -label "AimRig" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		text -l "エイムさせるノード" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 90 200 -l "AimSetNode" AimSetNodeField;
			popupMenu;
			menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] AimSetNodeField;");
			menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" AimSetNodeField;");
		text -l "Upベクトルノードを子にする親ノード" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 90 200 -l "Aim Parent Node" AimUpParentNodeField;
			popupMenu;
			menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] AimUpParentNodeField;");
			menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" AimUpParentNodeField;");
		text -l "ターゲットノードを子にする親ノード" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 90 200 -l "Aim Parent Node" AimTargetParentNodeField;
			popupMenu;
			menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] AimTargetParentNodeField;");
			menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" AimTargetParentNodeField;");
		rowColumnLayout -nc 4 -cw 1 65 -cw 2 65 -cw 3 65 -cw 4 65;
			text -l "Aimの方向" -al "left";
			optionMenu -h 25 AimDiroptionMenu;
				menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
				optionMenu -e -v "x" AimDiroptionMenu;
			text -l "Upの方向" -al "left";
			optionMenu -h 25 UpDiroptionMenu;
				menuItem -label "x";menuItem -label "y";menuItem -label "z";menuItem -label "xi";menuItem -label "yi";menuItem -label "zi";
				optionMenu -e -v "y" UpDiroptionMenu;
		setParent ..;
		button -en 1 -h 25 -w 100 -l "AimRig" -c "doyjp_AimRig" -bgc 0.4 0.7 0.0 ;
	
	setParent ..;
	
	frameLayout -w 300 -label "UV pattern" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		text -l "UV移動で表示切替する" -al "left";
		text -l "切替UIの名称を入力" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 70 240 -l "patternName" UVpatternNameField;
		text -l "マテリアルを選択して右クリックでGet" -al "left";
		textFieldGrp -h 20 -w 200 -cw2 70 240 -l "Material" UVpatternMaterialField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;string $tag = stringArrayToString\($sel, \"\,\"\);textFieldGrp -e -text $tag UVpatternMaterialField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" UVpatternMaterialField;");
		text -l "UV座標を入力" -al "left";
		columnLayout UVpatternPosColumnLayout;
		//text -l "U";text -l "V";
		
		string $uvp =`floatFieldGrp -pre 3 -nf 2 -v1 0.0 -v2 0.0` ;
		
		setParent ..;
		button -l "Add UV pattern" -c ("string $uvp =`floatFieldGrp -pre 3 -nf 2 -p \"UVpatternPosColumnLayout\" -v1 0.0 -v2 0.0`;");
		button -en 1 -h 25 -w 100 -l "UV pattern" -c "doyjp_UV_pattern" -bgc 0.4 0.7 0.0 ;
	setParent ..;

	//frameLayout -w 300 -label "Ctrl Scale" -labelAlign "top" -bv 1 -cll 1 -cl 1 ;
	//	text -l "コントローラーを記入して実行" -al "left";
	//	textFieldGrp -h 20 -w 200 -cw2 50 240 -l "Ctrl" CtrlScaleField;
	//		popupMenu;
	//			menuItem -label "Get" -c ("string $sel[] = `ls -sl`;textFieldGrp -e -text $sel[0] CtrlScaleField;");
	//			menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" CtrlScaleField;");
	//	button -h 25 -w 98 -l "Ctrl_Scale"  -c "doyjp_CtrlScaleConnect" -bgc 0.4 0.7 0.0 CtrlScaleButton;
	//setParent ..;

	//frameLayout -w 300 -label "Add_TK_RigSetUp" -labelAlign "top" -bv 1 -cll 1 -cl 1 ;
	//	button -en 1 -h 25 -w 100 -l "Add_TK_RigSetUp"  -c "YOS_Add_IK_RigSetUp" -bgc 0.4 0.7 0.0
	//					-ann "IKを重ねがけする。rootとendのジョイントを上記入力して実行" AddTKControlsButton;	
	//setParent ..;
	//
	//frameLayout -w 300 -label "Ctrl_Divide" -labelAlign "top" -bv 1 -cll 1 -cl 1 ;
	//	button -en 1 -h 25 -w 98 -l "Ctrl_Divide"  -c "YOS_ControlDivide"  -bgc 0.4 0.7 0.0
	//		-ann "割合を設定できる回転追従。ctrlを1段目、ジョイントを2段目に上記入力して実行。ジョイントの回転値をctrlにコネクト。強度アトリビュートがctrlに追加" ControlDivideButton;
	//
	//setParent ..;

	frameLayout -w 300 -label "NoIkAttr" -labelAlign "top" -bv 1 -cll 1 -cl 1 -mh 4 -mw 4;
		textFieldGrp -h 20 -w 200 -cw2 50 240 -l "Mesh" NoIkAttrField;
			popupMenu;
				menuItem -label "Get" -c ("string $sel[] = `ls -sl`;string $tag = stringArrayToString\($sel, \"\,\"\);textFieldGrp -e -text $tag NoIkAttrField;");
				menuItem -label "Delete" -c ("textFieldGrp -e -text \"\" NoIkAttrField;");
		button -en 1 -h 25 -w 98 -l "NoIkAttr"  -c "doAddMetaNoIkAttr" -bgc 0.4 0.7 0.0
					-ann "IKを入れないジョイントを選択して実行" NoIkAttrButton;
	
	setParent ..;
	
	setParent ..;
	*/
///tabEdit
	
		tabLayout -e
			-tl $AutoSetUpTab "AutoSetUp"
			//-tl $ModuleTab "module"
			$yjp_SetUpTab;
	setParent ..;
	window -e -wh 330 450 RigSetUpWindow;

	showWindow RigSetUpWindow;
	//Rig_CharactorIDChange;
	if(!`optionVar -ex "jptRigPatternListFolder"`){
		$currentScriptPath = `whatIs "yjp_sRig.mel"`;
		string $array[] = stringToStringArray($currentScriptPath, " ");
		$currentScriptPath = $array[size($array)-1];
		string $ScriptPath = `dirname $currentScriptPath`;
		$ClipFolderPath = `dirname $ScriptPath`+"/rig_module_scripts";
	}
	textField -e -text $ClipFolderPath RigPatternListFolderField;
	RigPatternListReLoad;
	Rig_CharactorIDMenu;
	Rig_CharactorIDChange;

	//使用MELリロード
	source yjp_Createswiches_ctrl.mel;
	source yjp_rig_SwichesAddAttr.mel;
	source yjp_rig_makeMetaRoot.mel;
	source yjp_rig_getMeta.mel;
	source yjp_rig_CenterCtrlCreate.mel;
	source yjp_rig_ControlParent.mel;
	source yjp_rig_Aim.mel;
	source yjp_rig_IKFKSetUp.mel;
	source yjp_rig_FKSetUp.mel;
	source yjp_rig_GroupCreate.mel;
	//source yjp_rig_makeFK.mel;
	source yjp_rig_makeMetaNode.mel;
	source yjp_rig_connectMeta.mel;
	source yjp_rig_GroundCTRL.mel;
	source yjp_rig_SplineIK.mel;
	//source RigCtrlCharacterSet.mel;
	source yjp_rig_MultiConstraint.mel;
	source MeshDisplaySwiches.mel;
	source yjp_rig_makePVLocator.mel;
	source SelectJointArray.mel;
	source yjp_unity_SwicheVis.mel;
	source yjp_rig_IKFKSwichesUI.mel;
	source ControlDivideRigSetUp.mel;
	source yjp_ui_numSwitchBar.mel;
	//source Add_IK_RigSetUp.mel;
	
	//source IKFKFootRigSetUp.mel;
	source getNodeNamespace.mel;

	source addMetaNoIkAttr.mel;

	source yjp_CtrlScaleConnect.mel;
	string $pluginlist[] = `pluginInfo -q -ls`;
	if(stringArrayFind( "matrixNodes", 0, $pluginlist ) == -1)loadPlugin matrixNodes;
}
