
//////////////////////////////////////////////////////////////////////////////////////////////

global proc string getUIType(string $uiName) {
    string $uiTypes[] = {"TextField", "FloatFieldGrp", "FloatField"};
    for ($type in $uiTypes) {
        if (`gmatch $uiName ("*"+$type+"*")`) {
            return $type;
        }
    }
    return "unknown";
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpNodeGet(string $tf)
{
	print("yjp_RigSetUpNodeGet "+ $tf + "\n");
	string $selNode[] = `ls -sl`;
	string $locName = `nameRoot $selNode[0]`;
	textField -e -text $locName $tf;

	string $atr[];
	string $UIpath[];
	int $num = `tokenize $tf "|" $UIpath`;
	string $UIlist[] = `layout -q -childArray $UIpath[4]`;
	float $val[];
	for($UI in $UIlist){
		string $uiname = `objectTypeUI $UI`;
		//print($uiname+"\n");
		if(`getUIType $UI` == "FloatField"){
			$atr = {"tx","ty","tz","rx","ry","rz"};
			for ($n=0; $n<`size $atr`;$n++){
				if(`gmatch $UI ("*Field_" + $atr[$n]+"*")`){
					print($locName + "." + $atr[$n]+"\n");
					$val[0] = `getAttr ($locName + "." + $atr[$n])`;
					$val[0] =`yjp_DPoint $val[0] 0.01`;
					floatField -e -v $val[0] $UI;
				}
			}
		}
		else if(`getUIType $UI` == "FloatFieldGrp"){
			$atr = {"trans","rot"};
			for ($n=0; $n<`size $atr`;$n++){
				if(`gmatch $UI ("*FieldGrp_" + $atr[$n]+"*")`){
					if($n==0)$val = `xform -q -ws -t $locName`;
					else if($n==1)$val = `xform -q -ws -ro $locName`;

					floatFieldGrp -e -v1 $val[0] $UI;
					floatFieldGrp -e -v2 $val[1] $UI;
					floatFieldGrp -e -v3 $val[2] $UI;
				}
			}
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpGuideCreate(string $tf)
{
	print("yjp_RigSetUpGuideCreate "+ $tf + "\n");
	string $fileName = `textFieldGrp -q -text RigEdit_rigpNameField`;
	string $locName = `textField -q -tx $tf`;
	string $aim = $locName + "_aim";
	string $up = $locName + "_up";
	
	if(`gmatch $tf "*ADDNODETextField*"`||`gmatch $tf "*RootJointTextField*"`){
		if(`objExists $locName`){
			print("LocatorCreate\n");
			delete $locName;
		}
		spaceLocator -n $locName;
		
	}
	
	if(`gmatch $tf "*AIMNODETextField*"`){
		if(`objExists $locName`)delete $locName ;
		if(`objExists $aim`)delete $aim;
		if(`objExists $up`)delete $up;
		
		RigCurveBox $locName 5 5 14;
		RigCurveRhombus $aim 5 5 13;
		RigCurveRhombus $up 5 5 18;
	}
	string $atr[] = {"tx","ty","tz","rx","ry","rz"};
	string $UIpath[];
	int $num = `tokenize $tf "|" $UIpath`;
	string $UIlist[] = `layout -q -childArray $UIpath[4]`;
	//int $UInum = `substitute "textField_" $UIpath[$num-1] ""`;
	float $val[];
	
	for($UI in $UIlist){
		if(`getUIType $UI` == "FloatField"){
			for ($n=0; $n<`size $atr`;$n++){
				if(`gmatch $UI ("*Field_" + $atr[$n] + "*")`){
					$val[0] = `floatField -q -v $UI`;
					setAttr ($locName + "." + $atr[$n]) $val[0];
				}
			}	
		}
		else if(`getUIType $UI` == "FloatFieldGrp"){
			$val[0] = `floatFieldGrp -q -v1 $UI`;
			$val[1] = `floatFieldGrp -q -v2 $UI`;
			$val[2] = `floatFieldGrp -q -v3 $UI`;
			float $Fieldval[];
			if(`gmatch $UI "*FieldGrp_trans*"`){
				//$Fieldval = `xform -q -ws -t ($fileName+":"+$locName)`;
				//print($Fieldval[0]);
				if(($val[0]+$val[1]+$val[2]) != 0.0){
					xform -ws -t $val[0] $val[1] $val[2] $locName;
				}
				else{
					if(`objExists ($fileName+":"+$locName)`){
						matchTransform -pos $locName ($fileName+":"+$locName);
					}
				}
			}
			else if(`gmatch $UI "*FieldGrp_rot*"`){
				//$Fieldval = `xform -q -ws -ro ($fileName+":"+$locName)`;
				if(($val[0]+$val[1]+$val[2]) != 0.0){
					xform -ws -ro $val[0] $val[1] $val[2] $locName;
				}
				else{
					if(`objExists ($fileName+":"+$locName)`){
						matchTransform -rot $locName ($fileName+":"+$locName);
					}
				}
			}			
		}
	}
	if(`objExists $up`){
		parent -r $aim $locName;
		setAttr ($aim + ".tx") 20;
		parent -w $aim;
		parent -r $up $locName;
		setAttr ($up + ".ty") 20;
		parent -w $up;
		aimConstraint -aim 1 0 0 -u 0 1 0 -wut "object" -wuo $up $aim $locName;		
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableRefresh(string $Layout)
{
	print ("yjp_RigSetUpTableRefresh\n");
	global string $ss_RigCharaID ;
	global string $RigSetUpStringLine[];
	
	string $joint[] = `ls -type joint`;
	string $ID = $ss_RigCharaID ;
	string $RefNameSpace = $ID+":";
	string $IDset = $ID +"_set";
	string $Line,$buffer[],$win,$tf;
	string $prin;
	string $none = "";
	string $delcome[];
	string $opA,$cB;
	string $target;
	string $jointList[],$jointarray[];
	int $val,$m,$intVal[];
	int $num = 1;
	int $OrderValue[];
	float $exist = 0;
	float $NodeVal[];
	string $pos,$temp;
	//string $Layout = "yjp_rigpEditcolumnLayout";
	string $clayout[] = `columnLayout -q -ca $Layout`;
	
	if(size($clayout) !=0)deleteUI $clayout;

	int $countLine = 0;
	int $MaxLine = (size($RigSetUpStringLine));
	//window -e -vis 0 "MayaWindow";
	
	progressWindow
	-title "rigFile Loading"
	-progress $countLine
	-isInterruptable true
	-min 0
	-maxValue $MaxLine;

	for($Line in $RigSetUpStringLine){
		$target = "";
		$buffer = stringToStringArray($Line, ",\n");
		
		switch($buffer[0]){
			default:
				//print ("default "+$buffer[0] +"\n");
				if(size($buffer) ==1){
					$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 800 -p $Layout`;
					button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
					text -l "";
					yjp_RigSetUpTableCreateButton "comment" $win $num;
					$num++;
					tokenize $buffer[0] "/" $delcome;
					textField -pht "comment" -tx $delcome[0];
					setParent ..;
				}
				break;
			case "":
			case "//":
				break;
			case "ID":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -p $Layout`;
				
				text -l "";
				text -l "";
				button  -l "ID";
				textField -tx $buffer[1];
				$ID = $buffer[1]+":";
				setParent ..;$num++;
				break;

			case "CENTER":
			case "//CENTER":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "centerJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "CENTER")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "CENTER" $win $num;
				$num++;
				$tf = `textField -pht "joint or node" -bgc 0 0 0 -tx $buffer[1] -sbm "Joint or Node" `;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
				/*
				$tf = `textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[2]`;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				*/
				setParent ..;
				break;
			case "FK":
			case "//FK":
			case "FKold":
			case "//FKold":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "FK")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" FK\n") ;
				yjp_RigSetUpTableCreateButton "FK" $win $num;
				$num++;
				$tf = `textField -pht "Root joint" -bgc 0 0 0 -tx $buffer[1] -sbm "Root Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[2]=="none"){
					$exist = 0;
				}
				else if(!`objExists ($RefNameSpace + $buffer[2])`){
					$exist = 0.3;
				}
				else{
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;
				}
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[3] -sbm "Parent Joint or None"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);

				setParent ..;
				break;
			case "FKaxis":
			case "//FKaxis":
				$win = `rowColumnLayout -nc 9 -cw 1 20 -cw 2 20 -cw 3 70 
					-cw 4 170 -cw 5 170 -cw 6 170 
					-cw 7 180
					-cw 8 180
					-cw 9 65 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "FKaxis")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" FK\n") ;
				yjp_RigSetUpTableCreateButton "FKaxis" $win $num;
				$num++;
				$tf = `textField -pht "Root joint" -bgc 0 0 0 -tx $buffer[1] -sbm "Root Joint" "AIMNODETextField#"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[2]=="none"){
					$exist = 0;
				}
				else if(!`objExists ($RefNameSpace + $buffer[2])`){
					$exist = 0.3;
				}
				else{
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;
				}
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$tf = `textField -pht "Parent Joint or None" -bgc $exist 0 0 -tx $buffer[3] -sbm "Parent Joint or None" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);

				$NodeVal[0] = string($buffer[4]);
				$NodeVal[1] = string($buffer[5]);
				$NodeVal[2] = string($buffer[6]);
				$NodeVal[3] = string($buffer[7]);
				$NodeVal[4] = string($buffer[8]);
				$NodeVal[5] = string($buffer[9]);
				$intVal[0] = string($buffer[10]);

				$tf = `floatFieldGrp -nf 3 -label "GuidPos" -cw 1 45 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] "FAaxisFloatFieldGrp_trans#"`;

				$tf = `floatFieldGrp -nf 3 -label "GuidRot" -cw 1 45 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[3] -v2 $NodeVal[4] -v3 $NodeVal[5] "FAaxisFloatFieldGrp_rot#"`;

				checkBoxGrp -l "Xreverse" -v1 $intVal[0] -cw2 42 20 -cal 1 "center"-cal 2 "center";
	
				setParent ..;
				break;
			case "EFK":
			case "//EFK":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "EFK")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" EFK\n") ;
				yjp_RigSetUpTableCreateButton "EFK" $win $num;
				$num++;
				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[1] -sbm "Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[2]=="none"){
					$exist = 0;
				}
				else if(!`objExists ($RefNameSpace + $buffer[2])`){
					$exist = 0.3;
				}
				else{
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;
				}
				$tf = `textField -pht "size" -bgc $exist 0 0 -tx $buffer[2] -sbm "Size"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[3] -sbm "Parent Joint or None"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);;
				/*
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[4] `;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(size($jointarray[0]) != 0){
					$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
					$jointList = stringArrayCatenate($jointList, $jointarray);
				}
				*/
				setParent ..;
				break;
			case "ADDNODE":
			case "//ADDNODE":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170
				-cw 5 180
				-cw 6 180
				-cw 7 170 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "ADDNODE")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" ADDNODE\n") ;
				yjp_RigSetUpTableCreateButton "ADDNODE" $win $num;
				$num++;
				$tf = `textField -pht "CreateName" -bgc $exist 0 0 -tx $buffer[1] -sbm "Right-click to create node and Get" "ADDNODETextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
				
				$NodeVal[0] = string($buffer[2]);
				$NodeVal[1] = string($buffer[3]);
				$NodeVal[2] = string($buffer[4]);
				$NodeVal[3] = string($buffer[5]);
				$NodeVal[4] = string($buffer[6]);
				$NodeVal[5] = string($buffer[7]);

				$tf = `floatFieldGrp -nf 3 -label "GuidPos" -cw 1 45 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] "addNodeFloatFieldGrp_trans#"`;

				$tf = `floatFieldGrp -nf 3 -label "GuidRot" -cw 1 45 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[3] -v2 $NodeVal[4] -v3 $NodeVal[5] "addNodeFloatFieldGrp_rot#"`;

				$tf = `textField -pht "parent joint or none" -bgc $exist 0 0 -tx $buffer[8] -sbm "Parent Joint or None"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "none" -c ("textField -e -tx \"none\"" + $tf);
				/*
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[9]` ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				*/
				setParent ..;
				break;
			case "CLAMP":
			case "//CLAMP":
				$win = `rowColumnLayout -nc 11 -cw 1 20 -cw 2 20 -cw 3 70
					-cw 4 160 -cw 5 120 -cw 6 150
					-cw 7 140 -cw 8 140 -cw 9 140
					-cw 10 60
					-cw 11 160
					-p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "CLAMP")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" CLAMP\n") ;
				yjp_RigSetUpTableCreateButton "CLAMP" $win $num;
				$num++;
				$tf = `textField -pht "Driver Node(CTRL)" -bgc $exist 0 0 -tx $buffer[1] -sbm "Driver Node(CTRL)"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "Driven Node(joint)" -bgc $exist 0 0 -tx $buffer[2] -sbm "Driven Node(joint)"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "node" -bgc 0 0 0 -tx $buffer[3] -sbm "node(_0)"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$NodeVal[0] = string($buffer[4]);
				$NodeVal[1] = string($buffer[5]);
				$NodeVal[2] = string($buffer[6]);
				$NodeVal[3] = string($buffer[7]);
				$NodeVal[4] = string($buffer[8]);
				$NodeVal[5] = string($buffer[9]);
				$NodeVal[6] = string($buffer[10]);
				$NodeVal[7] = string($buffer[11]);
				$NodeVal[8] = string($buffer[12]);
				$NodeVal[9] = string($buffer[13]);
				$NodeVal[10] = string($buffer[14]);
				$NodeVal[11] = string($buffer[15]);
				$NodeVal[12] = string($buffer[16]);

				floatFieldGrp -nf 3 -label "min" -cw 1 25 -cw 2 35 -cw 3 35 -cw 4 35 -tze 0 -pre 1 -sbm "minRotate"
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] ;

				floatFieldGrp -nf 3 -label "max" -cw 1 25 -cw 2 35 -cw 3 35 -cw 4 35 -tze 0 -pre 1 -sbm "maxRotate"
				-v1 $NodeVal[3] -v2 $NodeVal[4] -v3 $NodeVal[5] ;

				floatFieldGrp -nf 3 -label "mag" -cw 1 25 -cw 2 35 -cw 3 35 -cw 4 35 -tze 0 -pre 1 -sbm "magnitude"
				-v1 $NodeVal[6] -v2 $NodeVal[7] -v3 $NodeVal[8] ;
				
				$opA = `optionMenu  -h 25 -l "Dir"`;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[13] $opA;
				
				floatFieldGrp -nf 3 -label "Hit Pos" -cw 1 45 -cw 2 35 -cw 3 35 -cw 4 35 -tze 0 -pre 1 -sbm "Hit Node offset"
				-v1 $NodeVal[10] -v2 $NodeVal[11] -v3 $NodeVal[12] ;

				setParent ..;
				
				break;
			case "IK":
			case "//IK":
			case "IKd":
			case "//IKd":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170 -cw 5 170 -cw 6 100 -cw 7 170
				-cw 8 80 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "IK"||$buffer[0] == "IKd")$val=1;
				string $buttonName = `substitute "//" $buffer[0] ""`;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton $buttonName $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Root joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "End joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "PV Node" -bgc $exist 0 0 -tx $buffer[3] -sbm "PV Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				if(`objExists ($RefNameSpace + $buffer[4])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent node" -bgc $exist 0 0 -tx $buffer[4] -sbm "Parent Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if($buffer[5] == "1"){
					$buffer[5] = "pz";
				}
				else if($buffer[5] == "-1"){
					$buffer[5] = "nz";
				}
				$opA = `optionMenu -label "PVdir" -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					optionMenu -e -v $buffer[5] $opA;

			/*
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "6";menuItem -label "13";menuItem -label "17";
					optionMenu -e -v $buffer[4] $opA;
			
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[5] ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "IKsds":
			case "//IKsds":
			case "aIK":
			case "//aIK":
				$win = `rowColumnLayout -nc 9 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170 -cw 5 170 -cw 6 100 -cw 7 170
				-cw 8 80 -cw 9 170 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "IKsds"||$buffer[0] == "aIK"){$val=1;}
				$buttonName = `substitute "//" $buffer[0] ""`;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton $buttonName $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root Joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Root Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "PV Node" -bgc $exist 0 0 -tx $buffer[3] -sbm "PV Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				if(`objExists ($RefNameSpace + $buffer[4])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Parent Node" -bgc $exist 0 0 -tx $buffer[4] -sbm "Parent Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$opA = `optionMenu -label "PVdir" -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					optionMenu -e -v $buffer[5] $opA;

				//if(`objExists ($RefNameSpace + $buffer[5])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "aux Node" -bgc $exist 0 0 -tx $buffer[6] -sbm "aux Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				/*
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "6";menuItem -label "13";menuItem -label "17";
					optionMenu -e -v $buffer[4] $opA;
			
				$tf =`textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[5] ;
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "Parent":
			case "//Parent":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Parent")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "Parent" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Parent ctrl" -bgc $exist 0 0 -tx $buffer[1] -sbm "Parent ctrl"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Child ctrl" -bgc $exist 0 0 -tx $buffer[2] -sbm "Child ctrl"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				setParent ..;
				break;
			case "SIK":
			case "//SIK":
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 40 -cw 8 40 -cw 9 40 -cw 10 150  -cw 11 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIK")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "SIK" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root Joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Root Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 -l " span"`;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[3] $opA;

				$intVal[0] = string($buffer[4]);
				checkBoxGrp -l " twist " -v1 $intVal[0] -cw2 35 15 -cal 1 "center"-cal 2 "center";

				$opA = `optionMenu  -h 25 `;
					menuItem -label "py";menuItem -label "ny";menuItem -label "nz";menuItem -label "pz";menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[5] $opA;

				$intVal[0] = string($buffer[6]);
				checkBoxGrp -l " Stretch " -v1 $intVal[0] -cw2 50 15 -cal 1 "center"-cal 2 "center";
			
				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[7]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "up Node" -bgc $exist 0 0 -tx $buffer[7] -sbm "up Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[8])`){
					$jointarray[0] = ($RefNameSpace + $buffer[8]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Parent Joint" -bgc $exist 0 0 -tx $buffer[8] -sbm "Parent Joint" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "SIKFK":
			case "//SIKFK":
				$win = `rowColumnLayout -nc 12 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170 -cw 5 170 -cw 6 70 -cw 7 55 -cw 8 50 -cw 9 70
				-cw 10 150
				-cw 11 180 -cw 12 65 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIKFK")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "SIKFK" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root Joint" -bgc $exist 0 0 -tx $buffer[1]
				 -sbm "root joint : Right-click to create node and Get" "RootJointTextField#"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						menuItem -label "UpGuid_Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
						menuItem -label "UpGuid_Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 -l " span"`;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[3] $opA;

				$intVal[0] = string($buffer[4]);
				checkBoxGrp -l " Twist " -v1 $intVal[0] -cw2 35 15 -cal 1 "center"-cal 2 "center";

				$opA = `optionMenu  -h 25 `;
					menuItem -label "py";menuItem -label "ny";menuItem -label "nz";menuItem -label "pz";menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[5] $opA;

				$intVal[0] = string($buffer[6]);
				checkBoxGrp -l " Stretch " -v1 $intVal[0] -cw2 50 15 -cal 1 "center"-cal 2 "center";

				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[8]);
					$exist = 0;
				}
				else{
					$exist = 0.3;
				}
				$tf = `textField -pht "Parent Joint" -bgc $exist 0 0 -tx $buffer[7] -sbm "Parent Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
						
				if (`yjp_isNumeric $buffer[8]`){
					$NodeVal[0] = 0.0 ;
				}
				else{
					$NodeVal[0] = string($buffer[8]);
				}

    			if (`yjp_isNumeric $buffer[9]`){
					$NodeVal[1] = 0.0 ;
				}
				else{
					$NodeVal[1] = string($buffer[9]);
				}

				if (`yjp_isNumeric $buffer[10]`){
					$NodeVal[2] = 0.0 ;
				}
				else{
					$NodeVal[2] = string($buffer[10]);
				}
				$NodeVal[0] = string($buffer[8]);
				$NodeVal[1] = string($buffer[9]);
				$NodeVal[2] = string($buffer[10]);
				$intVal[0] = string($buffer[11]);

				$tf = `floatFieldGrp -nf 3 -label "UpPos" -cw 1 45 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 2
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] "addNodeFloatFieldGrp_trans#"`;

				checkBoxGrp -l "Xreverse" -v1 $intVal[0] -cw2 42 20 -cal 1 "center"-cal 2 "center";

				setParent ..;
				break;
			case "SIK2":
			case "//SIK2":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 40 -cw 7 150  -cw 8 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "SIK2")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "SIK2" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root Joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Root Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "End Joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";
					optionMenu -e -v $buffer[3] $opA;
			
				if(`objExists ($RefNameSpace + $buffer[4])`){
					$jointarray[0] = ($RefNameSpace + $buffer[4]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "up node" -bgc $exist 0 0 -tx $buffer[4] -sbm "up Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[5])`){
					$jointarray[0] = ($RefNameSpace + $buffer[5]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Parent Joint" -bgc $exist 0 0 -tx $buffer[5] -sbm "Parent Joint" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				/*
				textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[6];
					popupMenu;
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				*/
				setParent ..;
				break;
			case "RIB":
			case "//RIB":
			//RIB,1,ID00_set,parent,jointjointjoint
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 40 -cw 5 170 -cw 6 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "RIB")$val=1;
				checkBox -l "" -v $val;
				
				yjp_RigSetUpTableCreateButton "RIB" $win $num;
				$num++;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "0";menuItem -label "1";menuItem -label "2";menuItem -label "3";menuItem -label "4";menuItem -label "5";
					optionMenu -e -v $buffer[1] $opA;
			
				//textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[2];
			
				$tf = `textField -pht "parent" -bgc $exist 0 0 -tx $buffer[2] -sbm "Parent Node"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				for($m=4;$m<size($buffer);$m++){
					$target += ($buffer[$m]+",");
				}
				
				textField -pht "joint,joint,joint..." -bgc $exist 0 0 -tx $target;
				setParent ..;
				break;
			case "iIK":
			case "//iIK":
			case "IKid":
			case "//IKid":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 100 -cw 7 170 -cw 8 80 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "iIK"||$buffer[0] == "IKid")$val=1;
				checkBox -l "" -v $val ;
				yjp_RigSetUpTableCreateButton "IKid" $win $num;
				$num++;
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Root joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Root joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "End joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "End joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[3])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "pv node" -bgc $exist 0 0 -tx $buffer[3] -sbm "PV Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists ($RefNameSpace + $buffer[4])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "parent node" -bgc $exist 0 0 -tx $buffer[4] -sbm "Parent Node"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$opA = `optionMenu  -label "PVdir" -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					optionMenu -e -v $buffer[5] $opA;

				setParent ..;
				break;

			case "Const":
			case "//Const":
			case "Multi":
			case "//Multi":
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 125 -cw 5 45 -cw 6 180 -cw 7 700 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Const")$val=1;
				checkBox -l "" -v $val;
				
				yjp_RigSetUpTableCreateButton "Const" $win $num;
				$num++;
				print($buffer[1]+"\n");
				string $menuString = $buffer[1];
				if($buffer[1] == "0"){
					$menuString = "rotate";
				}
				else if($buffer[1] == "1"){
					$menuString = "both";
				}
				else if($buffer[1] == "2"){
					$menuString = "trans";
				}				
				$opA = `optionMenu -label " TransRot" `;
					menuItem -label "both";menuItem -label "rotate";menuItem -label "trans";
					optionMenu -e -v $menuString $opA;
				
				int $mo = string($buffer[2]);
				checkBoxGrp -l "mo" -v1 $mo -cw2 25 20 -cal 1 "center"-cal 2 "center" -sbm "maintainOffset";
				
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[3] `;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				string $MultTarget[];
				for($m=4;$m<size($buffer);$m++){
					if(!`stringArrayContains $buffer[$m] $MultTarget`){
						$MultTarget[size($MultTarget)] = $buffer[$m];
					}
				}
				$target = stringArrayToString($MultTarget, ",");
				textField -pht "ctrl,ctrl,ctrl..." -bgc $exist 0 0 -tx $target ;
				setParent ..;
				break;
			case "Bridge":
			case "//Bridge":
			//Bridge,name,0.5,0.5,node,node,node,node,joint,joint
				$win = `rowColumnLayout -nc 7 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 100 -cw 5 80 -cw 6 450 -cw 7 450-p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Bridge")$val=1;
				checkBox -l "" -v $val ;
				
				yjp_RigSetUpTableCreateButton "Bridge" $win $num;
				$num++;
				
				$tf = `textField -pht "name" -bgc $exist 0 0 -tx $buffer[1] -sbm "SurfaceName"`;
				
				$NodeVal[0] = $buffer[2];
				$NodeVal[1] = $buffer[3];
				
				floatFieldGrp -nf 2 -label "UV" -cw 1 17 -cw 2 28 -cw 3 28 -tze 0 -pre 1
				-sbm "UV" -v1 $NodeVal[0] -v2 $NodeVal[1] ;
				
				for($m=4;$m<`size$buffer`;$m++){
					if(`gmatch $buffer[$m] "*!*"`){
						 $temp += `substitute "!" $buffer[$m] ""`+",";
					}
					else{
						$pos += $buffer[$m]+",";
					}
				}
				textField -pht "node or vtx" -bgc $exist 0 0 -tx $pos -sbm "node or vtx" ;
			
				textField -pht "joint,joint,joint..." -bgc $exist 0 0 -tx $temp -sbm "joint,joint,joint..." ;
				setParent ..;
				break;
			case "NabPoint":
			case "//NabPoint":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 100 -cw 5 100 -cw 6 20 -cw 7 20 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "NabPoint")$val=1;
				checkBox -l "" -v $val ;
				
				yjp_RigSetUpTableCreateButton "NabPoint" $win $num;
				$num++;
				
				$tf = `textField -pht "SurfaceName" -bgc $exist 0 0 -tx $buffer[1] -sbm "SurfaceName"`;
				$tf = `textField -pht "makePointName" -bgc $exist 0 0 -tx $buffer[3] -sbm "makePointName"`;
				
				$NodeVal[0] = $buffer[4];
				$NodeVal[1] = $buffer[5];

				floatFieldGrp -nf 2 -label "UV" -cw 1 20 -cw 2 20 -cw 3 20 -tze 0 -pre 1
				-sbm "UV" -v1 $NodeVal[0] -v2 $NodeVal[1] ;
				
				setParent ..;
				break;
			case "eCurve":
			case "//eCurve":
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 100 -cw 5 100 -cw 6 400-p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "eCurve")$val=1;
				checkBox -l "" -v $val ;
				
				yjp_RigSetUpTableCreateButton "eCurve" $win $num;
				$num++;
				
				$tf = `textField -pht "node" -bgc $exist 0 0 -tx $buffer[1]`;
				
				$tf = `textField -pht "name" -bgc 0 0 0 -tx $buffer[2]`;
				
				string $edgindex;
				for($m=3;$m<`size$buffer`;$m++){
					$edgindex +=  $buffer[$m] +",";
				}
				textField -pht "edgindex,edgindex,..." -bgc $exist 0 0 -tx $edgindex ;
			
				setParent ..;
				break;
				//
			case "AngleRe":
			case "//AngleRe":
				$win = `rowColumnLayout -nc 13 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 40 -cw 8 40 -cw 9 150 -cw 10 120 -cw 11 40 -cw 12 40 -cw 13 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "AngleRe")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "AngleRe" $win $num;
				$num++;
				//root joint cw 4
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "root joint" -bgc $exist 0 0 -tx $buffer[1] -sbm  "Root Joint"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				//Angle joint cw 5
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "Angle joint" -bgc $exist 0 0 -tx $buffer[2] -sbm "Angle Joint" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				//axis cw 6
				$opA = `optionMenu  -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					optionMenu -e -v $buffer[3] $opA;
				
				//axis cw 7
				$opA = `optionMenu  -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					optionMenu -e -v $buffer[4] $opA;
				
				$tf = `textField -pht "90" -bgc $exist 0 0 -tx $buffer[5] -sbm "Val"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				$tf = `textField -pht "React SDK" -bgc $exist 0 0 -tx $buffer[6] -sbm "React SDK"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				$tf = `textField -pht "attr" -bgc $exist 0 0 -tx $buffer[7] -sbm "attr" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				$tf = `textField -pht "float" -bgc $exist 0 0 -tx $buffer[8] -sbm "attr Val min" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				string $AttrADDctrl = $buffer[9];
				float $attrValmax = 0;

				if(!`gmatch $buffer[9] "?[a-z]*"`){
					$attrValmax = $buffer[9];
					$AttrADDctrl = $buffer[10];
				}
				$tf = `textField -pht "float" -bgc $exist 0 0 -tx $attrValmax -sbm "attr Val max" ` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
				
				if(`objExists ($RefNameSpace + $AttrADDctrl)`){
					$jointarray[0] = ($RefNameSpace + $AttrADDctrl);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $AttrADDctrl -sbm "Attr ADD ctrl"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				setParent ..;
				break;
			case "Bend":
			case "//Bend":
				//$Driven,string $Driver,string $ctrl,float $bendVal ,float $rollVal float $axisvalx)
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 170 -cw 8 90 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "Bend")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" Bend\n") ;
				yjp_RigSetUpTableCreateButton "Bend" $win $num;
				$num++;
				$tf = `textField -pht "Driven" -bgc $exist 0 0 -tx $buffer[1] -sbm "Driven #_FK_SDK"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
							
				$tf = `textField -pht "Driver" -bgc $exist 0 0 -tx $buffer[2] -sbm "Driver Joint"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[3] -sbm "#_FK_ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
				
				$NodeVal[0] = string($buffer[4]);
				$NodeVal[1] = string($buffer[5]);
				$NodeVal[2] = string($buffer[6]);
				
				floatFieldGrp -nf 2 -label "Bend Roll mag" -cw 1 80 -cw 2 42 -cw 3 42 -tze 0 -pre 1
				-sbm "bendVal rollVal" -v1 $NodeVal[0] -v2 $NodeVal[1] ;
				floatFieldGrp -nf 1 -label "axis val" -cw 1 40 -cw 2 42 -tze 0 -pre 1
				-sbm "axis val" -v1 $NodeVal[2]  ;

				setParent ..;
				break;

			case "Uparm":
			case "//Uparm":
				$win = `rowColumnLayout -nc 10 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 56 -cw 8 150 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "Uparm")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" Uparm\n") ;
				yjp_RigSetUpTableCreateButton "Uparm" $win $num;
				$num++;
				$tf = `textField -pht "UpArm_FK_SDK" -bgc $exist 0 0 -tx $buffer[1] -sbm "UpArm_FK_SDK"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
							
				$tf = `textField -pht "Shoulder" -bgc $exist 0 0 -tx $buffer[2] -sbm "Shoulder"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "UpArm_FK_ctrl" -bgc $exist 0 0 -tx $buffer[3] -sbm "UpArm_FK_ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
				
				$OrderValue[0] = string($buffer[4]);
				$NodeVal[0] = string($buffer[5]);
				$NodeVal[1] = string($buffer[6]);
				$NodeVal[2] = string($buffer[7]);

				intFieldGrp -nf 1 -label "Order" -cw 1 30 -cw 2 20 -v1 $OrderValue[0];
				
				floatFieldGrp -nf 3 -label "RHV val" -cw 1 40 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] -sbm "RHV val" ;

				setParent ..;
				break;

			case "rDriver":
			case "//rDriver":
				$win = `rowColumnLayout -nc 9 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170 -cw 5 170 -cw 6 170 
				-cw 7 56 -cw 9 150 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -ann "rotationDriver" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "rDriver")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" rDriver\n") ;
				yjp_RigSetUpTableCreateButton "rDriver" $win $num;
				$num++;
				$tf = `textField -pht "UpArm_FK_SDK" -bgc $exist 0 0 -tx $buffer[1] -sbm "UpArm_FK_SDK"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "Shoulder" -bgc $exist 0 0 -tx $buffer[2] -sbm "Shoulder"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "UpArm_FK_ctrl" -bgc $exist 0 0 -tx $buffer[3] -sbm "UpArm_FK_ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
				
				$OrderValue[0] = string($buffer[4]);
				$NodeVal[0] = string($buffer[5]);
				$NodeVal[1] = string($buffer[6]);
				$NodeVal[2] = string($buffer[7]);

				checkBoxGrp -l "Order" -v1 $OrderValue[0] -cw2 30 20 -cal 1 "center"-cal 2 "center" -sbm "reverseOrder";
				
				floatFieldGrp -nf 3 -label "RHV val" -cw 1 40 -cw 2 42 -cw 3 42 -cw 4 42 -tze 0 -pre 1
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] -sbm "RHV val";
				
				setParent ..;
				break;

			case "FixTwist":
			case "//FixTwist":
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 60 -cw 8 190 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -ann "FixTwist" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "FixTwist")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" FixTwist\n") ;
				yjp_RigSetUpTableCreateButton "FixTwist" $win $num;
				$num++;
				$tf = `textField -pht "Shoulder:Hip" -bgc $exist 0 0 -tx $buffer[1] -sbm "Shoulder:Hip"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "Elbow:Knee_FK_ctrl" -bgc $exist 0 0 -tx $buffer[2] -sbm "Elbow:Knee_FK_ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						
				$tf = `textField -pht "UpArm_FK_ctrl:none" -bgc $exist 0 0 -tx $buffer[3] -sbm "UpArm_FK_ctrl:none"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
				/*
				$OrderValue[0] = string($buffer[4]);
				$NodeVal[0] = string($buffer[5]);
				$NodeVal[1] = string($buffer[6]);
				$NodeVal[2] = string($buffer[7]);

				intFieldGrp -nf 1 -label "Order" -cw 1 30 -cw 2 20 -v1 $OrderValue[0];
				
				floatFieldGrp -nf 3 -label "RHV val" -cw 1 40 -cw 2 50 -cw 3 50 -cw 4 50 -tze 0 -pre 1 -co4 3 3 3 3
				-v1 $NodeVal[0] -v2 $NodeVal[1] -v3 $NodeVal[2] -sbm "RHV val" ;
				*/
				setParent ..;
				break;

			case "RevFoot":
			case "//RevFoot":
				$win = `rowColumnLayout -nc 10 -cw 1 20 -cw 2 20 -cw 3 70
				 -cw 4 60 -cw 5 170 -cw 6 120 -cw 7 120 -cw 8 120 -cw 9 120 -cw 10 120 -p $Layout`;
				//text -l "";text -l "" ;button -l "" -vis 0;text -l "RootJoint";text -l "EndJoint";text -l "ParentJoint";text -l "characterSet";
				button -l "del" -ann "ReverseFoot" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				
				$val=0;
				if($buffer[0] == "RevFoot")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+" FixTwist\n") ;
				yjp_RigSetUpTableCreateButton "RevFoot" $win $num;
				$num++;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "Toe";menuItem -label "NoToe";
					menuItem -label "Toe2";menuItem -label "NoToe2";
					optionMenu -e -v $buffer[1] $opA;

				$tf = `textField -pht "Foot_IKR_ctrl" -bgc $exist 0 0 -tx $buffer[2] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);		
				$tf = `textField -pht "Toe" -bgc $exist 0 0 -tx $buffer[3] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
				$tf = `textField -pht "ToePivot" -bgc $exist 0 0 -tx $buffer[4] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
				$tf = `textField -pht "Heel" -bgc $exist 0 0 -tx $buffer[5] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
				$tf = `textField -pht "Arch" -bgc $exist 0 0 -tx $buffer[6] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);
				$tf = `textField -pht "Sole" -bgc $exist 0 0 -tx $buffer[7] "ADDNODEtextField#"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Create" -c ("yjp_RigSetUpGuideCreate " + $tf);

				break;
			case "Dist":
			case "//Dist":
				$win = `rowColumnLayout -nc 10 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 40 -cw 7 150 -cw 8 100 -cw 9 40 -cw 10 150  -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Dist")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "Dist" $win $num;
				$num++;
				//TargetA cw 4
				if(`objExists ($RefNameSpace + $buffer[1])`){
					$jointarray[0] = ($RefNameSpace + $buffer[1]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "TargetA" -bgc $exist 0 0 -tx $buffer[1] -sbm "TargetA"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				//TargetB cw 5
				if(`objExists ($RefNameSpace + $buffer[2])`){
					$jointarray[1] = ($RefNameSpace + $buffer[2]);
					$exist = 0;}else{$exist = 0.3;}
			
				$tf = `textField -pht "TargetB" -bgc $exist 0 0 -tx $buffer[2] -sbm "TargetB"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);

				//maxLength cw 6
				$tf = `textField -pht "maxLength" -bgc $exist 0 0 -tx $buffer[3] -sbm "maxLength"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//React cw 7
				if(`objExists ($RefNameSpace + $buffer[6])`){
					$jointarray[0] = ($RefNameSpace + $buffer[4]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "React" -bgc $exist 0 0 -tx $buffer[4] -sbm "React"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;
				
				//attr cw 8
				$tf = `textField -pht "attr" -bgc $exist 0 0 -tx $buffer[5] -sbm "attr"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//val cw 9
				$tf = `textField -pht "val" -bgc $exist 0 0 -tx $buffer[6] -sbm "val"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

				//ctrl cw 10
				if(`objExists ($RefNameSpace + $buffer[7])`){
					$jointarray[0] = ($RefNameSpace + $buffer[7]);
					$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[7] -sbm "ctrl"` ;
				textField -e -ec ("yjp_RigSetUpTableCheck "+ $tf) $tf;

			/*
				$jointarray = `SelectJointArray $jointarray[0] $jointarray[1]`;
				$jointList = stringArrayCatenate($jointList, $jointarray);
			*/
				setParent ..;
				break;
			case "Swiche":
			case "//Swiche":
			//Swiche,ID00_set,face_upper,eye00,eye01,eye02,eye03,eye04,eye05,eye06,eye07
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 500 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Swiche")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "Swiche" $win $num;
				$num++;
				//textField -pht "characterSet" -bgc 0 0 0 -tx $buffer[1];
				textField -pht "Add Attr Name" -bgc $exist 0 0 -tx $buffer[1] -sbm "Add Attr Name";
				for($m=2;$m<size($buffer);$m++){
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target -sbm "obj,obj,obj...Separate many nodes with [,]";
				setParent ..;
				break;
			case "UnityVis":
			case "//UnityVis":
			//UnityVis,outNoad,mesh,mesh,mesh,mesh,mesh,mesh
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 700 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "UnityVis")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "UnityVis" $win $num;
				$num++;
				textField -pht "outputNode" -bgc $exist 0 0 -tx $buffer[1] -sbm "outputNode";
				for($m=2;$m<size($buffer);$m++){
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target -sbm "obj,obj,obj...Separate many nodes with [,]";
				setParent ..;
				break;
			case "AIM":
			case "//AIM":
			////yjp_AimRig(,string $CtrlNode,string $BaseNode,string $AimDir,string $UpDir,string $charaName,string $TergetNode[]);
				$win = `rowColumnLayout -nc 8 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 170 -cw 5 170 -cw 6 170 -cw 7 40 -cw 8 40 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "AIM")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "AIM" $win $num;
				$num++;
				string $UpParentNoad = $buffer[2];
				string $TargetParentNoad = $buffer[3];
				string $AIMDir = $buffer[4];
				string $AIMUpDir = $buffer[5];
				//string $AIMcharaName = $buffer[5];
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[1] -sbm "ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				$tf = `textField -pht "baseNode" -bgc $exist 0 0 -tx $UpParentNoad -sbm "baseNode"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				$tf = `textField -pht "baseNode" -bgc $exist 0 0 -tx $TargetParentNoad -sbm "baseNode"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				$opA = `optionMenu  -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "n";
					menuItem -label "dx";menuItem -label "dy";menuItem -label "dz";menuItem -label "dxi";menuItem -label "dyi";menuItem -label "dzi";
				optionMenu -e -v $AIMDir $opA;
				$opA = `optionMenu  -h 25 `;
					menuItem -label "px";menuItem -label "py";menuItem -label "pz";menuItem -label "nx";menuItem -label "ny";menuItem -label "nz";
					menuItem -label "dx";menuItem -label "dy";menuItem -label "dz";menuItem -label "dxi";menuItem -label "dyi";menuItem -label "dzi";
				optionMenu -e -v $AIMUpDir $opA;
				
				//textField -pht "characterSet" -bgc 0 0 0 -tx $AIMcharaName;
				
				for($m=6;$m<size($buffer);$m++){
					if(`objExists ($RefNameSpace + $buffer[$m])`){$exist = 0;}else{$exist = 0.3;}
					$target += $buffer[$m]+",";
				}
				//textField -pht "obj,obj,obj..." -bgc $exist 0 0 -tx $target;
				setParent ..;
				break;
			case "Scale":
			case "//Scale":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Scale")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "Scale" $win $num;
				$num++;
				$tf = `textField -bgc 0 0 0 -tx $buffer[1] -sbm ""` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "Div":
			case "Divide":
				$win = `rowColumnLayout -nc 5 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 200 -cw 5 200 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "Divide")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "Divide" $win $num;
				$num++;
				if(`objExists ($RefNameSpace +$buffer[1])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "joint" -bgc $exist 0 0 -tx $buffer[1] -sbm "Joint"` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				if(`objExists ($RefNameSpace +$buffer[2])`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -pht "ctrl" -bgc $exist 0 0 -tx $buffer[2] -sbm "ctrl"` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				setParent ..;
				break;
			case "NoIK":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 600 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "NoIK")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "NoIK" $win $num;
				$num++;
				if(`objExists $buffer[1]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[1]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				setParent ..;
				break;

			case "IKfoot":
				$win = `rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 150 -cw 5 150 -cw 6 150
												-cw 7 20 -cw 8 20 -cw 9 70 -cw 10 150 -cw 11 150 -cw 12 150
												-cw 13 20 -cw 14 20 -cw 15 70 -cw 16 150 -cw 17 150 -cw 18 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "IKfoot")$val=1;
				checkBox -l "" -v $val;
				yjp_RigSetUpTableCreateButton "IKfoot" $win $num;
				$num++;
				if(`objExists $buffer[1]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[1]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[2]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[2]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[3]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[3]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				text -l "";text -l "";text -l "";
				
				if(`objExists $buffer[4]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[4]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[5]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[5]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[6]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[6]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				text -l "";text -l "";text -l "";
				
				if(`objExists $buffer[7]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[7]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[8]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[8]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
			
				if(`objExists $buffer[9]`){$exist = 0;}else{$exist = 0.3;}
				$tf = `textField -bgc $exist 0 0 -tx $buffer[9]` ;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				setParent ..;
				break;

			case "MEL":
			case "//MEL":
				$win = `rowColumnLayout -nc 4 -cw 1 20 -cw 2 20 -cw 3 70 -cw 4 800 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "MEL")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ "MEL\n") ;
				yjp_RigSetUpTableCreateButton "MEL" $win $num;
				$num++;
				textField -pht "command" -bgc 0 0 0 -tx $buffer[1] -sbm "MEL script";
				
				setParent ..;
				break;
			case "CTRL":
			case "//CTRL":
				$win = `rowColumnLayout -nc 9 -cw 1 20 -cw 2 20 -cw 3 70
				-cw 4 170 -cw 5 100
				-cw 6 130
				-cw 7 170
				-cw 8 170 
				-cw 9 150 -p $Layout`;
				button -l "del" -c ("yjp_RigSetUpDeleteCommand " + $win + " " + $num);
				$val=0;
				if($buffer[0] == "CTRL")$val=1;
				checkBox -l "" -v $val;
				//print ($num+ $buffer[1]+"CTRL\n") ;
				yjp_RigSetUpTableCreateButton "CTRL" $win $num;
				$num++;
				$tf = `textField -pht "ctrl" -bgc 0 0 0 -tx $buffer[1] -sbm "ctrl"`;
					popupMenu;
						menuItem -label "Get" -c ("yjp_RigSetUpNodeGet " + $tf);
						menuItem -label "Select" -c ("yjp_RigEditNodeSelect " + $tf);
						menuItem -label "Delete" -c ("textField -e -tx \"\"" + $tf);
				
				$opA = `optionMenu  -h 25 `;
					menuItem -label "Box";
					menuItem -label "Square";
					menuItem -label "Square2";
					menuItem -label "Circle";
					menuItem -label "Circle2";
					menuItem -label "Cross";
					menuItem -label "Sphere";
					menuItem -label "Pyramid";
					menuItem -label "Rhombus";
					menuItem -label "BoxCenter";
					menuItem -label "FootBox";
				
				optionMenu -e -v $buffer[2] $opA;
				$NodeVal[0] = $buffer[3];
				$NodeVal[1] = $buffer[4];
				$NodeVal[2] = $buffer[5];
				$NodeVal[3] = $buffer[6];
				$NodeVal[4] = $buffer[7];
				$NodeVal[5] = $buffer[8];
				$NodeVal[6] = $buffer[9];
				$NodeVal[7] = $buffer[10];

				floatFieldGrp -nf 2 -label "WH val" -cw 1 40 -cw 2 40 -cw 3 40 -tze 0 -pre 1 -co3 2 2 2
				-sbm "WH val" -v1 $NodeVal[0] -v2 $NodeVal[1] ;

				floatFieldGrp -nf 3 -label "pos val" -cw 1 40 -cw 2 40 -cw 3 40 -cw 4 40 -tze 0 -pre 1 -co4 2 2 2 2
				-sbm "pos val" -v1 $NodeVal[2] -v2 $NodeVal[3] -v3 $NodeVal[4];

				floatFieldGrp -nf 3 -label "rot val" -cw 1 40 -cw 2 40 -cw 3 40 -cw 4 40 -tze 0 -pre 1 -co4 2 2 2 2
				-sbm "rot val" -v1 $NodeVal[5] -v2 $NodeVal[6] -v3 $NodeVal[7];

				int $color = 6;
				if($buffer[11] !="")$color = int($buffer[11])+1;
				colorIndexSliderGrp -cw2 20 130 -min 1 -max 31 -value $color ;
				//-cw 1 20-cw 2 150
				setParent ..;
				break;

		}
		$countLine ++;
		print ($countLine+ "\n") ;
		progressWindow -edit -progress $countLine -status $countLine;		
		//print ($num+ "\n") ;
	}
	progressWindow -edit -endProgress;
	//print ("//////Joints not set up//////" + "\n") ;
	string $RestJoint[] = stringArrayRemove ($jointList, $joint);
	$RestJoint = stringArrayRemoveDuplicates($RestJoint);
	//for($prin in $RestJoint){print ($prin+ "\n");}
	select $RestJoint;
	clear $jointarray;
	
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableCreateButton(string $com,string $win,int $n)
{
	button  -l $com -p $win;
	if (`gmatch $win "*yjp_rigpEditcolumnLayout*"`){
		popupMenu;
			//menuItem -label "insert ADDIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  ADDIK " + $n + "\"");
			menuItem -label "insert ADDNODE" -c ("evalDeferred \"yjp_RigSetUpAddCommand  ADDNODE " + $n + "\"");
			menuItem -label "insert AIM" -c ("evalDeferred \"yjp_RigSetUpAddCommand  AIM " + $n + "\"");
			menuItem -label "insert AngleRe" -c ("evalDeferred \"yjp_RigSetUpAddCommand  AngleRe " + $n + "\"");
			menuItem -label "insert Bridge" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Bridge " + $n + "\"");
			menuItem -label "insert Bend" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Bend " + $n + "\"");
			menuItem -label "insert Uparm" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Uparm " + $n + "\"");			
			menuItem -label "insert rotationDriver" -c ("evalDeferred \"yjp_RigSetUpAddCommand  rDriver " + $n + "\"");
			menuItem -label "insert FixTwist" -c ("evalDeferred \"yjp_RigSetUpAddCommand  FixTwist " + $n + "\"");
			menuItem -label "insert AimClamp" -c ("evalDeferred \"yjp_RigSetUpAddCommand  AimClamp " + $n + "\"");			
			menuItem -label "insert CENTER" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CENTER " + $n + "\"");
			menuItem -label "insert CLAMP" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CLAMP " + $n + "\"");
			menuItem -label "insert Distance" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Dist " + $n + "\"");
			menuItem -label "insert Div" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Divide " + $n + "\"");
			menuItem -label "insert comment" -c ("evalDeferred \"yjp_RigSetUpAddCommand  comment " + $n + "\"");
			//menuItem -label "insert CSET" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CSET " + $n + "\"");
			menuItem -label "insert CTRL" -c ("evalDeferred \"yjp_RigSetUpAddCommand  CTRL " + $n + "\"");
			menuItem -label "insert FKaxis" -c ("evalDeferred \"yjp_RigSetUpAddCommand  FKaxis " + $n + "\"");
			menuItem -label "insert EFK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  EFK " + $n + "\"");
			menuItem -label "insert FKold" -c ("evalDeferred \"yjp_RigSetUpAddCommand  FK " + $n + "\"");
			menuItem -label "insert IKd" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IKd " + $n + "\"");
			menuItem -label "insert IKsds" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IKsds " + $n + "\"");
			menuItem -label "insert IKid" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IKid " + $n + "\"");
			menuItem -label "insert ReverseFoot" -c ("evalDeferred \"yjp_RigSetUpAddCommand  RevFoot " + $n + "\"");
			menuItem -label "insert MEL" -c ("evalDeferred \"yjp_RigSetUpAddCommand  MEL " + $n + "\"");
			menuItem -label "insert Const" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Const " + $n + "\"");
			menuItem -label "insert Parent" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Parent " + $n + "\"");
			menuItem -label "insert eCurve" -c ("evalDeferred \"yjp_RigSetUpAddCommand  eCurve " + $n + "\"");
			//menuItem -label "insert IKfoot" -c ("evalDeferred \"yjp_RigSetUpAddCommand  IKfoot " + $n + "\"");
			menuItem -label "insert RIB" -c ("evalDeferred \"yjp_RigSetUpAddCommand  RIB " + $n + "\"");
			menuItem -label "insert Scale" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Scale " + $n + "\"");
			menuItem -label "insert SIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIK " + $n + "\"");
			menuItem -label "insert SIKFK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIKFK " + $n + "\"");
			//menuItem -label "insert SIK2" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SIK2 " + $n + "\"");
			menuItem -label "insert Swiche" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Swiche " + $n + "\"");
			menuItem -label "insert UnityVis" -c ("evalDeferred \"yjp_RigSetUpAddCommand  UnityVis " + $n + "\"");

			//menuItem -label "insert Collider" -c ("evalDeferred \"yjp_RigSetUpAddCommand  Collider " + $n + "\"");
			//menuItem -label "insert SWING" -c ("evalDeferred \"yjp_RigSetUpAddCommand  SWING " + $n + "\"");
			//menuItem -label "insert NoIK" -c ("evalDeferred \"yjp_RigSetUpAddCommand  NoIK " + $n + "\"");
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableCheck(string $tf)
{
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;	
	string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[0]`;
	string $rf = `textField -q -tx $FieldArray[3]`;
	
	float $exist = 0.0;
	string $tex = `textField -q -text $tf`;
	$tex = $rf +":" +$tex;
	print ($tex+ "\n") ;
	if(!`objExists $tex`)$exist = 0.3;
	textField -e -bgc $exist  0 0 $tf;
	//if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
}
//////////////////////////////////////////////////////////////////////////////////////////////
//Save edits to file
global proc yjp_RigSetUpTableSave(int $as)
{
	//yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
	//global string $RigSetUpStringLine[];
	//save
	string $comline[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $rigpName = `textFieldGrp -q -text RigEdit_rigpNameField`;
	//string $charaName[] = `textScrollList -q -si RigPatternScrollList`;
	//
	string $localpath = `workspace -q -rd`;
	$localpath = $localpath + "setup";
	
	if(!`filetest -d $localpath`)sysFile -md $localpath;

	string $rigFilePath = `window -q -t  yjp_RigSetUpListEditWindow`;
	$rigFilePath = `substitute "RigSetUpTableEdit   " $rigFilePath ""`;

	if($as){
		string $tempFolder = `textField RigPatternListFolderField`;
		string $bakehistory = `promptDialog
			-title "Save Temp"
			-message "Temp Name:"
			-button "Save" -button "Cancel"
			-defaultButton "Save" -cancelButton "Cancel"
			-dismissString "Cancel"`;
		if($bakehistory == "Save"){
			$rigpName = `promptDialog -query -text`;
			$rigFilePath = $tempFolder +"/" + $rigpName + ".rigp";
		}
		else if($bakehistory == "Cancel"){
			return;
		}
	}

	$file_path = dirname($rigFilePath);

	//$rigFilePath = $file_path + "/" + $rigpName + ".rigp";
	string $daya =`date -sd`;
	$daya = `substitute "/" $daya ""`;
	string $time =`date -st`;
	$daya = "_" + $daya + `substitute ":" $time ""`;
	string $backupfilePassName = $file_path + "/backup/" + $rigpName + $daya+".rigp";
	//

	if(!`filetest -f $rigFilePath`){
		$PFile =`fopen ($rigFilePath)`;
		fclose $PFile;
	}
	if(!`filetest -w $rigFilePath`)error"File is in a state where it cannot be written";
	if(!`filetest -d ($file_path + "/backup/")`){
		sysFile -md ($file_path + "/backup/");
	}
	int $n;
	string  $slash;
	string $rowl[],$cm,$script;
	$script += ("//\n");
	for($n=0;$n<size($comline);$n++){
		//print ("comline "+$comline[$n] +"\n");
		$rowl = `rowColumnLayout -q -ca $comline[$n]`;
		//print ("$rowl " + $rowl[2] +"\n");
		$cm =`button -q -l $rowl[2]`;
		if($cm !="comment" && $cm !="ID" && $cm !=""){
			if(`checkBox -q -v $rowl[1]`)
			{$slash = "";}
			else
			{$slash = "//";}
		}
		//print ($cm +"\n");
		switch($cm){
			case "comment":
				$script += ("//" + `textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "ID":
				$script += ($slash + "ID,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "CENTER":
				$script += ($slash + "CENTER," );
				$script += (`textField -q -text $rowl[3]`+ "\n" );
				break;
			
			case "FK":
			case "FKold":
				$script += ($slash + "FK," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "\n" );
				break;
			case "FKaxis":
				$script += ($slash + "FKaxis," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`floatFieldGrp -q -v1 $rowl[6]`+ "," );
				$script += (`floatFieldGrp -q -v2 $rowl[6]`+ "," );
				$script += (`floatFieldGrp -q -v3 $rowl[6]`+ "," );
				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v2 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v3 $rowl[7]`+ "," );
				$script += (`checkBoxGrp -q -v1 $rowl[8]`+ "\n");
				break;
			case "EFK":
				$script += ($slash + "EFK," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "\n" );
				break;

			case "ADDNODE":
				$script += ($slash + "ADDNODE," );
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[4]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[4]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[4]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[5]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[5]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;

			case "CLAMP":
				$script += ($slash + "CLAMP," );
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");

				$script += (`floatFieldGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[6]`+ ",");

				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[7]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[7]`+ ",");

				$script += (`floatFieldGrp -q -v1 $rowl[8]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[8]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[8]`+ ",");

				$script += (`optionMenu -q -v $rowl[9]`+ "," );

				$script += (`floatFieldGrp -q -v1 $rowl[10]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[10]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[10]`+ "\n");
				break;

			case "IKd":
			case "IK":
				$script += ($slash + "IKd,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]`+ "\n");
				break;

			case "IKsds":
			case "aIK":
				$script += ($slash + "IKsds,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]` + "\n");
				break;

			case "IKid":
			case "iIK":
				$script += ($slash + "IKid,");
				$script += (`textField -q -text $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]`+ "\n");
				break;
			
			case "Parent":
				$script += ($slash + "Parent,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "IKfoot":
				//
				$script += ($slash + "IKfoot,");
				$script += (`textField -q -text $rowl[2]`+ ",");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`floatField -q -v $rowl[5]`+ "\n");
				break;

			case "RevFoot":
				$script += ($slash + "RevFoot," );
				$script += (`optionMenu -q -v $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]`+ "\n");
				break;

			case "SourceP":
			case "SourceParent":
				$script += ($slash + "SourceP,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "SIK":
				//
				$script += ($slash + "SIK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`checkBoxGrp -q -v1 $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + ",");
				$script += (`checkBoxGrp -q -v1 $rowl[8]` + ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]` + "\n");
				break;
			case "SIKFK":
				//
				$script += ($slash + "SIKFK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`checkBoxGrp -q -v1 $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + ",");
				$script += (`checkBoxGrp -q -v1 $rowl[8]` + ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[10]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[10]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[10]`+ ",");
				$script += (`checkBoxGrp -q -v1 $rowl[11]` + "\n");
				break;

			case "SIK2":
				//
				$script += ($slash + "SIK2,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ "\n");
				break;

			case "RIB":
				//
				$script += ($slash + "RIB,");
				$script += (`optionMenu -q -v $rowl[3]` + ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ "\n");
				break;
			
			case "Const":
				//
				$script += ($slash + "Const,");
				$script += (`optionMenu -q -v $rowl[3]` + ",");
				$script += (`checkBoxGrp -q -v1 $rowl[4]` + ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ "\n");
				break;
			
			case "Swiche":
				//
				$script += ($slash + "Swiche,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "UnityVis":
				//
				$script += ($slash + "UnityVis,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;

			case "Bend":
				$script += ($slash + "Bend," );
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[6]`+ "\n");
				break;

			case "Uparm":
				$script += ($slash + "Uparm," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`intFieldGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v2 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v3 $rowl[7]`+ "\n");
				break;

			case "rDriver":
				$script += ($slash + "rDriver," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "," );
				$script += (`checkBoxGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v2 $rowl[7]`+ "," );
				$script += (`floatFieldGrp -q -v3 $rowl[7]`+ "\n" );
				break;

			case "FixTwist":
				$script += ($slash + "FixTwist," );
				$script += (`textField -q -text $rowl[3]`+ "," );
				$script += (`textField -q -text $rowl[4]`+ "," );
				$script += (`textField -q -text $rowl[5]`+ "\n" );
				/*
				$script += (`intFieldGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[8]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[9]`+ "\n");
				*/
				break;

			case "AIM":
				//
				$script += ($slash + "AIM,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`optionMenu -q -v $rowl[7]` + "\n");
				break;
			
			case "Scale":
				//
				$script += ($slash + "Scale,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;

			case "Div":
			case "Divide":
				//
				$script += ($slash + "Divide,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "NoIK":
				$script += ($slash + "NoIK,");
				$script += (`textField -q -text $rowl[3]`+ "\n");
				break;
			
			case "ADDIK":
				$script += ($slash + "ADDIK,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`floatField -q -v $rowl[6]`+ "\n");
				break;
			
			case "SourcePsdk":
				$script += ($slash + "SourcePsdk,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ "\n");
				break;
			
			case "MEL":
				$script += ($slash + "MEL," + `textField -q -text $rowl[3]`+ "\n");
				break;
			case "CTRL":
				//
				int $co = `colorIndexSliderGrp -q -v $rowl[8]`-1; 
				//print( $co+ "\n");
				
				$script += ($slash + "CTRL,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`optionMenu -q -v $rowl[4]` + ",");
				$script += (`floatFieldGrp -q -v1 $rowl[5]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[5]`+ ",");

				$script += (`floatFieldGrp -q -v1 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[6]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[6]`+ ",");

				$script += (`floatFieldGrp -q -v1 $rowl[7]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[7]`+ ",");
				$script += (`floatFieldGrp -q -v3 $rowl[7]`+ ",");
				$script += ($co+ "\n");
				break;
			case "Bridge":
				//
				$script += ($slash + "Bridge,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`floatFieldGrp -q -v1 $rowl[4]` + ",");
				$script += (`floatFieldGrp -q -v2 $rowl[4]` + ",");
				
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += ("\n");
			break;

			case "NabPoint":
				//
				$script += ($slash + "NabPoint,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				$script += (`floatFieldGrp -q -v1 $rowl[5]`+ ",");
				$script += (`floatFieldGrp -q -v2 $rowl[5]`+ ",");
				$script += ("\n");
			break;
			
			case "eCurve":
				//
				$script += ($slash + "eCurve,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]` + ",");
				
				$text = (`textField -q -text $rowl[5]`);
				$array = stringToStringArray($text, ",");
				$script += stringArrayToString( $array, "," );
				$script += ",";
				$script += ("\n");
			break;
			case "AngleRe":
				//
				$script += ($slash + "AngleRe,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`optionMenu -q -v $rowl[5]` + ",");
				$script += (`optionMenu -q -v $rowl[6]` + ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]`+ ",");
				$script += (`textField -q -text $rowl[10]`+ ",");
				$script += (`textField -q -text $rowl[11]`+ ",");
				$script += (`textField -q -text $rowl[12]` + "\n");
				break;
			case "Dist":
				//
				$script += ($slash + "Dist,");
				$script += (`textField -q -text $rowl[3]`+ ",");
				$script += (`textField -q -text $rowl[4]`+ ",");
				$script += (`textField -q -text $rowl[5]`+ ",");
				$script += (`textField -q -text $rowl[6]`+ ",");
				$script += (`textField -q -text $rowl[7]`+ ",");
				$script += (`textField -q -text $rowl[8]`+ ",");
				$script += (`textField -q -text $rowl[9]` + "\n");
				break;
		}
	}
	print ($script +"\n");
	
    $PFile =`fopen ($rigFilePath) "w"`;
    fprint ($PFile, $script);
    fclose ($PFile);
	print ("Save " + $rigFilePath + "\n") ;

    $PFile =`fopen ($backupfilePassName) "w"`;
    fprint ($PFile, $script);
    fclose ($PFile);
	print ("backupSave " + $backupfilePassName + "\n") ;
	
	yjp_RigSetUpTableLoad $rigFilePath;
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpDeleteCommand(string $rl,int $num)
{
	if(`getModifiers` == 4){
		deleteUI -lay $rl;
		global string $RigSetUpStringLine[];
		stringArrayRemoveAtIndex($num,$RigSetUpStringLine);
		yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
		//if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpAddCommand(string $comd,int $num)
{
	global string $ss_RigCharaID ;
	global string $RigSetUpStringLine[];
	string $ID = $ss_RigCharaID ;
	
	string $che;
	for($che in $RigSetUpStringLine)print ($che+ "\n") ;
	print ($num + $RigSetUpStringLine[$num] + "\n") ;
	
	switch($comd){
		case "comment":
			$comd = "//Comment\n";
			break;
		case "ID":
			$comd = $comd+","+$ID+ "\n";
			break;
		case "CENTER":
			$comd = $comd+",joint\n";
			break;
		case "FKold":
			$comd = $comd+",joint,joint,parent\n";
			break;
		case "FKaxis":
			$comd = $comd+",joint,joint,parent,0,0,0,0,0,0,on\n";
			break;
		case "EFK":
			$comd = $comd+",makeName,2,parent or none\n";
			break;
		case "ADDNODE":
			$comd = $comd+",makeName,0,0,0,0,0,0,parent or none\n";
			break;
		case "CLAMP":
			$comd = $comd+",ctrl,Target,Base,0,0,0,0,0,0,0,0.5,1.0,1,20,0,0\n";
			break;
		case "IKd":
			$comd = $comd+",RootJoint,EndJoint,PVnode,1,parent\n";
			break;
		case "IKsds":
			$comd = $comd+",RootJoint,EndJoint,PVnode,1,auxjoint,parent\n";
			break;
		case "IKid":
			$comd = $comd+",RootJoint,EndJoint,PVnode,1,parent\n";
			break;
		case "IKfoot":
			$comd = $comd+",joint,joint,joint,node,node,node,node\n";
			break;
		case "Parent":
			$comd = $comd+",joint,joint\n";
			break;
		case "SIK":
			$comd = $comd+",joint,joint,2,1,nz,0,parent,upposx\n";
			break;
		case "RevFoot":
			$comd = $comd+",Toe,Foot_IKR_ctrl,Toe,ToePivot,Heel,Arch,Sole\n";
			break;
		case "SIKFK":
			$comd = $comd+",joint,joint,2,1,nz,0,parent,0,0,0,0\n";
			break;
		case "SIK2":
			$comd = $comd+",joint,joint,0,joint,joint\n";
		case "RIB":
			$comd = $comd+",1,parent,node\n";
			break;
		case "AIM":
			$comd = $comd+",CTRL,UPparent,TargetParent,x,y\n";
			break;
		case "ADDIK":
			$comd = $comd+",joint,joint,joint,0\n";
			break;
		case "SourceParent":
			$comd = $comd+",joint\n";
			break;
		case "SourcePsdk":
			$comd = $comd+",node,node\n";
			break;
		case "Div":
		case "Divide":
			$comd = $comd+",joint,ctrl\n";
			break;
		case "NoIK":
			$comd = $comd+",joint\n";
			break;
		case "Const":
			$comd = $comd+",both,1,ctrl,ctrl\n";
			break;
		case "Swiche":
			$comd = $comd+",makeName,mesh\n";
			break;
		case "UnityVis":
			$comd = $comd+",node,mesh\n";
			break;
		case "Scale":
			$comd = $comd+",joint\n";
			break;
		case "CONNECT":
			$comd = $comd+",node,attr,node,attr\n";
			break;
		case "MEL":
			$comd = $comd+",command\n";
			break;
		case "Bridge":
			$comd = $comd+",makeName,0.5,0.5,node,joint!\n";
			break;
		case "NabPoint":
			$comd = $comd+",Surface,makeName,0.5,0.5\n";
			break;
		case "Bend":
			$comd = $comd+",sdk,joint,ctrl,1.0,0.0,20\n";
			break;
		case "Uparm":
			$comd = $comd+",sdk,Shoulder,UpArm_FK_ctrl,0,0.5,1.0,1.0\n";
			break;
		case "rDriver":
			$comd = $comd+",#_FK_SDK,joint,#_FK_ctrl,0,0.1,1.0,1.0\n";
			break;
		case "FixTwist":
			$comd = $comd+",Shoulder:Hip,Elbow:Knee_FK_ctrl,UpArm_FK_ctrl\n";
			break;
		case "AimClamp":
			$comd = $comd+",UpArmL_FK_ctrl,ShoulderL,ClavicleL_FK_ctrl,-80,0,0,80,0,0.0,-0.5,0.0,0.0\n";
			break;
		case "eCurve":
			$comd = $comd+",node,name,edgeID,\n";
			break;
		case "CTRL":
			$comd = $comd+",ctrl,Box,10,10,0,0,0,0,0,0,6\n";
			break;
		case "AngleRe":
			$comd = $comd+",Rootjoint,joint,px,px,90,React,attr,0,0,ctrl\n";
			break;
		case "Dist":
			$comd = $comd+",TargetA,TargetB,name,React,attr,val,ctrl\n";
			break;
	}
	
	stringArrayInsertAtIndex($num,$RigSetUpStringLine,$comd);
	yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
	//if(`checkBox -q -v RigEditAutoSavecheckBox`)yjp_RigSetUpTableSave 0;
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigEditTextSearch()
{
	string $sText = `textFieldGrp -q -tx RigEditTextSearchField`;
	if(size($sText) == 0){
		yjp_RigSetUpTableRefresh "yjp_rigpEditcolumnLayout";
		return;
	}
	int$n,$f;
	
	$sText = "*" + $sText + "*";
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;
	for($n=0;$n<`size$LayoutArray`;$n++){
		string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[$n]`;
		for($f=0;$f<`size$FieldArray`;$f++){
			if(`gmatch $FieldArray[$f] "textField*"`){
				string $tex = `textField -q -tx $FieldArray[$f]`;
				if(`gmatch $tex $sText`){
					textField -e -bgc 0.0 0.5 0.0 $FieldArray[$f];
				}
				else{
					textField -e -bgc 0.0 0.0 0.0 $FieldArray[$f];
				}
			}
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigEditNodeSelect(string $tf)
{
	string $node = `textField -q -tx $tf`;
	
	string $LayoutArray[] = `columnLayout -q -ca yjp_rigpEditcolumnLayout`;	
	string $FieldArray[] = `rowColumnLayout -q -ca $LayoutArray[0]`;
	string $cn = `textField -q -tx $FieldArray[3]`;
	
	$node = $cn + ":" + $node;
	
	if(`objExists $node`){
		select -r $node;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yjp_RigSetUpTableLoad(string $rigFilePath)
{
	global string $RigSetUpStringLine[];
	clear $RigSetUpStringLine;
	global string $ss_RigCharaID ;
	//sRigMEL tempFolder path
	string $file_path = `textField -q -text RigPatternListFolderField`;
	string $fileName = `textFieldGrp -q -text RigEdit_rigpNameField`;
	if($ss_RigCharaID == "")$ss_RigCharaID = $fileName;

	string $TempPath = $file_path + "/" + $fileName + ".rigp";
	print($TempPath + "\n");
	
	if(`filetest -f $rigFilePath`){
		$RigSetUpStringLine = `freadAllLines $rigFilePath`;
		if(`filetest -w $rigFilePath`){
			window -e -t ("RigSetUpTableEdit   " + $rigFilePath) yjp_RigSetUpListEditWindow;
		}
		else{
			window -bgc 0.3 0.1 0.1 -e -t ("RigSetUpTableEdit   "+$rigFilePath) yjp_RigSetUpListEditWindow;
		}
	}
	else if(`filetest -f $TempPath`){
		window -e -t ("RigSetUpTableEdit   " + $TempPath) yjp_RigSetUpListEditWindow;
	}
}

//////////////////////////////////////////////////////////////////////////////

global proc yjp_sRig_SetUpTableEdit(string $rigFilePath)
{
	if(`window -q -ex yjp_RigSetUpListEditWindow`)deleteUI yjp_RigSetUpListEditWindow;
	string $yjp_RigSetUpListEditWindow = `window -wh 860 800 -s 1 -t "RigSetUpTableEdit" yjp_RigSetUpListEditWindow`;
	window -e -t ("RigSetUpTableEdit   " + $rigFilePath) $yjp_RigSetUpListEditWindow;
	string $fileName = `basename $rigFilePath ".rigp"`;
	string $form = `formLayout`;
	string $Buttton = `columnLayout -adjustableColumn true`;
		rowLayout -nc 9 ;
			textFieldGrp -h 20 -w 265 -cw2 60 200 -l "TextSearch" -cc "yjp_RigEditTextSearch" RigEditTextSearchField;
				popupMenu;
					menuItem -label "Delete" -c ("textFieldGrp -e -tx \"\" RigEditTextSearchField");
			textFieldGrp -h 20 -w 165 -cw2 60 100 -l "fileName" -text $fileName RigEdit_rigpNameField;
			//checkBox -h 20 -w 90 -l "AutoSave" -v 0 RigEditAutoSavecheckBox;
			button -h 25 -w 90 -l "Save" -c ("yjp_RigSetUpTableSave 0") ;
			button -h 25 -w 90 -l "tempSave" -c ("yjp_RigSetUpTableSave 1") ;
			button -h 25 -w 90 -l "FileOpen" -c ("yjp_RigSetUpListOpen 1");

			button -h 25 -w 90 -l "Add_comment" -c ("yjp_RigSetUpAddCommand comment 1000;") ;
			button -h 25 -w 90 -l "Add_MEL" -c ("yjp_RigSetUpAddCommand MEL 1000;") ;
			button -h 25 -w 90 -l "close" -c ("deleteUI " + $yjp_RigSetUpListEditWindow );
			setParent ..;
	
	setParent ..;
    string $MLS = `scrollLayout -horizontalScrollBarThickness 16 -verticalScrollBarThickness 16 `;
    string $rigEditLayout = `columnLayout -adjustableColumn true "yjp_rigpEditcolumnLayout"`;
        setParent ..;
    setParent ..;
	formLayout -edit
		-attachForm     $Buttton    "top" 0
		-attachNone     $Buttton    "bottom"
	    -attachForm     $Buttton    "left"   5
	    -attachForm     $Buttton    "right"  5
	
		-attachForm  $MLS    "top" 30
		-attachForm     $MLS    "bottom" 0
	    -attachForm     $MLS    "left"   0
	    -attachForm     $MLS    "right"  0
		$form;
	showWindow yjp_RigSetUpListEditWindow;
	yjp_RigSetUpTableLoad $rigFilePath;
	yjp_RigSetUpTableRefresh $rigEditLayout;
}