global proc yjp_doPVLocatorEdit(string $node, string $PVname, int $dirpv)
{
    global string $ss_RigCharaID ;
	string $ID = $ss_RigCharaID+":";
    float $val;

    if(`objExists $node`){
        if(!`objExists $PVname`){
            spaceLocator -n $PVname;
            parent $PVname ($ID+"NOTOUTPUT");
        }
        $val = `getAttr ($node+".tx")`;
        matchTransform -pos $PVname $node;
        move -r -ls -wd 0 0 (abs($val)*$dirpv) $PVname;       
    }
}